### ISSUE TITLE
OpenCTI is not reachable when integrating with MISP

### ISSUE THREAD

**Issue by oradious** [OpenCTI-Platform/opencti#1028]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I'm trying to integrate OpenCTI 4.0.3 connector with the MISP platform. So far, I've tried the ``docker-compose up`` method and tried to follow this article: ``https://blog.agood.cloud/posts/2020/04/24/adding-misp-to-opencti/``, but every time it just returns the OpenCTI API is not reachable ValueError. I've also referred to past issues regarding MISP connectors/unreachable APIs, but to no avail. I also went through every file in the MISP directory to change the version so that it matches 4.0.3
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1 LTS
2. OpenCTI version: 4.0.3
3. OpenCTI client: python
4. Other environment details:

## Expected Output

{ Please describe what you expected to happen. }

Here is the output when I run ``docker-compose up``

``
connector-misp_1  | INFO:root:Listing Threat-Actors with filters null.
connector-misp_1  | INFO:root:<!DOCTYPE html>
connector-misp_1  | <html lang="en">
connector-misp_1  | <head>
connector-misp_1  | <meta charset="utf-8">
connector-misp_1  | <title>Error</title>
connector-misp_1  | </head>
connector-misp_1  | <body>
connector-misp_1  | <pre>Cannot POST //graphql</pre>
connector-misp_1  | </body>
connector-misp_1  | </html>
connector-misp_1  |
connector-misp_1  | Traceback (most recent call last):
connector-misp_1  |   File "misp.py", line 1272, in <module>
connector-misp_1  |     mispConnector = Misp()
connector-misp_1  |   File "misp.py", line 84, in __init__
connector-misp_1  |     self.helper = OpenCTIConnectorHelper(config)
connector-misp_1  |   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 299, in __init__
connector-misp_1  |     self.api = OpenCTIApiClient(
connector-misp_1  |   File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 143, in __init__
connector-misp_1  |     raise ValueError(
connector-misp_1  | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
``
## Additional information
Here is the configuration of my ``docker-compose.yml`` file in the misp directory:

version: '3' 
services:
&nbsp;&nbsp;connector-misp:
&nbsp;&nbsp;&nbsp;&nbsp;image: opencti/connector-misp:4.0.3
&nbsp;&nbsp;&nbsp;&nbsp;environment:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- OPENCTI_URL=http://192.168.217.145:8080/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- OPENCTI_TOKEN=``<openCTI token UUID here>``
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_ID=``<connector ID UUID here>``
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_TYPE=EXTERNAL_IMPORT
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_NAME=MISP
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_SCOPE=misp
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_CONFIDENCE_LEVEL=3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_UPDATE_EXISTING_DATA=false
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- CONNECTOR_LOG_LEVEL=info
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_URL=``<URL here>`` # Required
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_KEY=``<MISP key here>`` # Required
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_SSL_VERIFY=False # Required
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_CREATE_REPORTS=True # Required, create report for MISP event
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_CREATE_INDICATORS=True # Required, create indicators from attributes
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_CREATE_OBSERVABLES=True # Required, create observables from attributes
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_IMPORT_FROM_DATE=2020-01-01 # Optional, import all event from this date
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_IMPORT_TAGS=opencti:import,type:OSINT # Optional, list of tags used for import events
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_IMPORT_TAGS_NOT= # Optional, list of tags to not include
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MISP_INTERVAL=2 # Required, in minutes
&nbsp;&nbsp;&nbsp;&nbsp;restart: always

One thing I've noted however, is when I did it via the ``docker-compose up`` method, the misp-connector container is not created. If I do it via the management panel (port 3000), the OpenCTI platform (port 8080) will fail.

**Comment by SamuelHassine** [comment]
Hello @oradious,

Please remove the trailing slash in the `OPENCTI_URL`. The query is done on `//graphql` which lead to a 404 error.

Kind regards,
Samuel
