### ISSUE TITLE
can not start work by Manual deployment

### ISSUE THREAD

**Issue by xiaochao** [OpenCTI-Platform/opencti#1104]
## Environment

1. OS: CentOS Linux release 7.9.2009 (Core)
2. OpenCTI version: opencti-release-4.2.3

Setup node 12.20
Setup elasticsearch
Setup rabbitMQ
Setup redis

when run pytho3 work.py, i go errors below:

503 http://localhost:4000/graphql
INFO:root:
Traceback (most recent call last):
  File "/root/opencti/opencti/worker/worker.py", line 295, in <module>
    worker = Worker()
  File "/root/opencti/opencti/worker/worker.py", line 221, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/python/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 143, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...

**Comment by richard-julien** [comment]
Is OpenCTI is correctly up and running?

**Comment by xiaochao** [comment]
My fault.I set http proxy for my terminal envirment.
