### ISSUE TITLE
[OpenCTI]: Unhandled 'error' event

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1137]
## Description
The service starts and the webpage goes down in a few seconds.

## Environment
1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 4.1.0
4. Other environment details: OpenCTI runs as a service, not docker

## Error log:
```
yarn run v1.22.5
$ node build/index.js
{"version":"4.2.0","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-03-07T20:24:27.045Z"}
{"version":"4.2.0","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-03-07T20:24:27.068Z"}
{"version":"4.2.0","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-03-07T20:24:27.085Z"}
{"version":"4.2.0","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-03-07T20:24:27.146Z"}
{"version":"4.2.0","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-03-07T20:24:27.146Z"}
{"version":"4.2.0","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-03-07T20:24:27.455Z"}
{"version":"4.2.0","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2021-03-07T20:24:27.463Z"}
{"version":"4.2.0","level":"info","message":"[INIT] admin user initialized","timestamp":"2021-03-07T20:24:27.862Z"}
{"version":"4.2.0","level":"info","message":"[MIGRATION] Read 0 migrations from the database","timestamp":"2021-03-07T20:24:27.874Z"}
{"version":"4.2.0","level":"info","message":"[MIGRATION] Platform already up to date, nothing to migrate","timestamp":"2021-03-07T20:24:27.875Z"}
{"version":"4.2.0","level":"info","message":"[MIGRATION] Migration process completed","timestamp":"2021-03-07T20:24:27.875Z"}
{"version":"4.2.0","level":"info","message":"[STREAM] Starting streaming processor","timestamp":"2021-03-07T20:24:28.613Z"}
{"version":"4.2.0","level":"info","message":"[OPENCTI] Servers ready on port 4000","timestamp":"2021-03-07T20:24:28.615Z"}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - failed to perform operation on queue 'push_bbe7fd05-fe35-42d3-ac3b-09e0440
f494c' in vhost '/' due to timeout"
    at ConfirmChannel.C.accept (/usr/share/opencti/node_modules/amqplib/lib/channel.js:422:17)
    at Connection.mainAccept [as accept] (/usr/share/opencti/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/usr/share/opencti/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on ChannelModel instance at:
    at Connection.emit (events.js:314:20)
    at Connection.C.onSocketError (/usr/share/opencti/node_modules/amqplib/lib/connection.js:353:10)
    at Connection.emit (events.js:314:20)
    at Socket.go (/usr/share/opencti/node_modules/amqplib/lib/connection.js:481:12)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
```

Regards,
ٌKhalid,

**Comment by khalidrehan** [comment]
I have fixed the issue.
It was a RabbitMQ server issue.
I have followed this article to resolve it: https://medium.com/@pratibhasharmadba/rabbitmq-server-issue-vhost-is-down-b9f5a718ec4f

```
# systemctl stop rabbitmq-server
# rm -rf /var/lib/rabbitmq/mnesia/rabbit@hostname_1/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L
# systemctl start rabbitmq-server
```


628WB79CIFDYO9LJI6DKMI09L in this case.
