### ISSUE TITLE
[Worker] No retrying on errors

### ISSUE THREAD

**Issue by maertv** [OpenCTI-Platform/opencti#1148]
## Description

Maybe the OpenCTI Worker retry functionality has changed and I missed it, but at the moment it seems to me that the OpenCTI Worker does not retry an operation after a failure. I am running two OpenCTI Workers that are processing YARA indicators with related reports. It is possible that one worker is creating an indicator and the other one is creating a relationship between the report and the indicator at the same time. The relationship creation fails with a _Missing reference to handle creation_ error which is expected. I would expect that after that error the worker would retry the relationship creation but the retry does not seem to happen.

I am not sure if this is related to this issue but it seems that these errors do not appear in the UI either (i.e., in the Data > Connectors & workers > [Connector] > Work ERRORS).

Excerpt from the OpenCTI Worker log:
```
INFO:root:Processing a new message (delivery_tag=216), launching a thread...
INFO:root:Importing a report (id: report--adfbf4b3-8172-11eb-b271-f496342c8d8c)
INFO:root:Creating Report {XXX Group Deploys New Evasive Python Malware}.
INFO:root:Adding StixObjectOrStixRelationship {indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c} to Report {966f121d-4d55-41c4-bd9e-bf6fd5a26e10}
ERROR:root:Missing reference to handle creation
ERROR:root:Missing reference indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c
INFO:root:Report expectation for opencti-work--c179c7ac-6781-4106-98f1-7c6b7b4ecf06
INFO:root:Message processed, thread terminated
INFO:root:Message (delivery_tag=216) acknowledged
```

Only these two errors appear in the OpenCTI Worker log.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.5 LTS
2. OpenCTI version: _master_
3. OpenCTI client: Frontend: _master_, Python: 4.2.4

**Comment by maertv** [comment]
```
...
ERROR:root:Missing reference indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c
...
```

The error above seems to be coming from the OpenCTI Python client:
https://github.com/OpenCTI-Platform/client-python/blob/1167aa0bf261e633c973ef0675974a216656e884/pycti/utils/opencti_stix2.py#L623.

There is an _except_ statement that catches everything.

**Comment by richard-julien** [comment]
Hi @maertv ,
After a quick look i think this behavior is here since a long time. object_refs are not splitted and so handle as a unit by the worker.
The retry will be done if the report fail to be created. For the element inside the report, the current implementation is to log and forget the relation to create :(

Maybe the simplest approach is to change this code to reject the creation of the chunk in order to retry the creation of the full report. Wdyt @SamuelHassine ?

**Comment by richard-julien** [comment]
After some discussion with @SamuelHassine , can you check if the indicator "indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c" really exists in the platform?

**Comment by maertv** [comment]
Yes, the indicator and the report are present in the platform, but there is no relationship between. Adding the relationship failed:
```
INFO:root:Adding StixObjectOrStixRelationship {indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c} to Report {966f121d-4d55-41c4-bd9e-bf6fd5a26e10}
ERROR:root:Missing reference to handle creation
ERROR:root:Missing reference indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c
```

I could be wrong but I think that the exception is not bubbled up to the worker. The exception is eaten when `ERROR:root:Missing reference indicator--adfbf4b2-8172-11eb-b271-f496342c8d8c` line is logged.

**Comment by richard-julien** [comment]
Yes, its done on purpose to create as much as possible relations that exists. For example if your indicator cannot be created because of a bad yara rule, we dont want to fail/retry to create the full report because of that.
This race condition should be really rare. Do you have the timestamp of creation of the indicator and the report?

**Comment by maertv** [comment]
I had to run it again.

In the OpenCTI Worker log:
```
INFO:root:Processing a new message (delivery_tag=228), launching a thread...
INFO:root:Importing a report (id: report--6edd4404-818e-11eb-b271-f496342c8d8c)
INFO:root:Creating Report {XXX}.
INFO:root:Adding StixObjectOrStixRelationship {indicator--6edd4403-818e-11eb-b271-f496342c8d8c} to Report {479a75b0-8950-43e4-85e7-58ee7ea0017c}
ERROR:root:Missing reference to handle creation
ERROR:root:Missing reference indicator--6edd4403-818e-11eb-b271-f496342c8d8c
INFO:root:Report expectation for opencti-work--018d208b-120b-4ca5-8f5b-070441ad3918
INFO:root:Message processed, thread terminated
INFO:root:Message (delivery_tag=228) acknowledged
```

It imported the report _report--6edd4404-818e-11eb-b271-f496342c8d8c_ (_479a75b0-8950-43e4-85e7-58ee7ea0017c_) successfully. However, it failed to create a relationship between the indicator _indicator--6edd4403-818e-11eb-b271-f496342c8d8c_ and said report (_479a75b0-8950-43e4-85e7-58ee7ea0017c_) because the indicator was not found.

The indicator _indicator--6edd4403-818e-11eb-b271-f496342c8d8c_ exists in the platform and so does the report _report--6edd4404-818e-11eb-b271-f496342c8d8c_ (additional IDs for the same report _report--84b23f24-8167-5bc4-a959-95d13131c7ef_ and _479a75b0-8950-43e4-85e7-58ee7ea0017c_).

The indicator in the platform (this is returned when I use the ID _indicator--6edd4403-818e-11eb-b271-f496342c8d8c_):
```
"indicator": {
    "id": "97b2e415-1c19-419f-9f7b-1cba113a796d",
    "standard_id": "indicator--abf6a0de-1e3f-5ff2-82ea-302e16aa5cf5",
    "x_opencti_stix_ids": [],
    "name": "apt_XXX_YYY_Payload_20200911",
    "created": "2020-08-10T19:01:20.000Z",
    "modified": "2020-08-10T19:01:20.000Z",
    "created_at": "2021-03-10T10:51:35.026Z",
    "updated_at": "2021-03-10T10:51:35.026Z"
}
```

The report in the platform (this is returned when I use the ID _report--6edd4404-818e-11eb-b271-f496342c8d8c_):
```
"report": {
    "id": "479a75b0-8950-43e4-85e7-58ee7ea0017c",
    "standard_id": "report--84b23f24-8167-5bc4-a959-95d13131c7ef",
    "x_opencti_stix_ids": [],
    "name": "XXX",
    "created": "2021-03-10T00:00:00.000Z",
    "modified": "2021-03-10T10:51:34.905Z",
    "created_at": "2021-03-10T10:51:33.937Z",
    "updated_at": "2021-03-10T10:51:34.905Z"
}
```

The error message from the OpenCTI log:
```
{
   "user":{
      "ip":"::ffff:127.0.0.1",
      "user_id":"88ce0c6a-13ec-5e39-b486-354fe4a7084f",
      "applicant_id":"88ce0a6c-13ce-5e39-b486-354fe4a7084f",
      "call_retry_number":"1"
   },
   "type":"WRITE_ERROR",
   "operation_query":"mutation ReportEditRelationAdd($id:ID!$input:StixMetaRelationshipAddInput){reportEdit(id:$id){relationAdd(input:$input){id}}}",
   "inner_relation_creation":0,
   "operation":"ReportEditRelationAdd",
   "time":23,
   "size":141,
   "error":{
      "data":{
         "reason":"Missing reference to handle creation",
         "http_status":404,
         "category":"business",
         "input":{
            "relationship_type":"object",
            "toId":"indicator--6edd4403-818e-11eb-b271-f496342c8d8c",
            "fromId":"479a75b0-8950-43e4-85e7-58ee7ea0017c"
         },
         "unresolvedIds":[
            "indicator--6edd4403-818e-11eb-b271-f496342c8d8c"
         ]
      },
      "stacktrace":[
         "MissingReferenceError: Element not found",
         "at error (webpack-internal:///./src/config/errors.js:33:10)",
         "at MissingReferenceError (webpack-internal:///./src/config/errors.js:101:39)",
         "at inputResolveRefs (webpack-internal:///./src/database/middleware.js:884:87)",
         "at async createRelation (webpack-internal:///./src/database/middleware.js:2333:25)"
      ]
   },
   "version":"4.3.0",
   "level":"warn",
   "message":"API Call",
   "timestamp":"2021-03-10T10:51:34.964Z"
}
```

**Comment by faustus25** [comment]
I have the same error running the Cryptolaemus connector:

`INFO:root:Creating Identity {Cryptolaemus Team}.
INFO:root:Creating External Reference {Cryptolaemus Team's Emotet C2 update of 2021-01-25T23:59:00+00:00}.
INFO:root:Creating Malware {Emotet}.
INFO:root:Creating Indicator {84.232.229.24}.
INFO:root:Creating Stix-Cyber-Observable {IPv4-Addr} with indicator at False.
INFO:root:Creating stix_core_relationship 'based-on' {4fb08db5-a759-46ea-a08e-d66d03774a4a, 186877b6-7a1c-4f0b-841a-37ae15f12f4f}.
INFO:root:Creating stix_core_relationship 'indicates' {4fb08db5-a759-46ea-a08e-d66d03774a4a, 04e50121-64fe-464f-963e-7d0919571c92}.
ERROR:root:Missing reference to handle creation
ERROR:root:{'name': 'MissingReferenceError', 'message': 'Missing reference to handle creation'}
`
The Indicator already exists in OpenCTI: 
Creation date
October 22, 2021, 6:09:20 PM
Modification date
January 26, 2022, 12:01:35 AM

It fetches the same indicator and loops with the same error message above.
