### ISSUE TITLE
ModuleNotFoundError: "sigma.parser"

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#1248]
## Description
OpenCTI log:
```
cti@cti:/usr/share/opencti$ tail -f logs/opencti.log.2021-04-08
{"version":"4.3.5","level":"info","message":"[BRIDGE] Traceback (most recent call last):","timestamp":"2021-04-08T23:56:41.139Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE]   File \"src/python/check_indicator.py\", line 6, in <module>","timestamp":"2021-04-08T23:56:41.139Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE]     from sigma.parser.collection import SigmaCollectionParser","timestamp":"2021-04-08T23:56:41.139Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE] ModuleNotFoundError: No module named 'sigma.parser'","timestamp":"2021-04-08T23:56:41.139Z"}
{"version":"4.3.5","level":"warn","message":"[BRIDGE] extractObservables error > ModuleNotFoundError: No module named 'sigma.parser'","timestamp":"2021-04-08T23:56:41.143Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE] Traceback (most recent call last):","timestamp":"2021-04-08T23:56:41.243Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE]   File \"src/python/check_indicator.py\", line 6, in <module>","timestamp":"2021-04-08T23:56:41.243Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE]     from sigma.parser.collection import SigmaCollectionParser","timestamp":"2021-04-08T23:56:41.243Z"}
{"version":"4.3.5","level":"info","message":"[BRIDGE] ModuleNotFoundError: No module named 'sigma.parser'","timestamp":"2021-04-08T23:56:41.243Z"}
{"version":"4.3.5","level":"warn","message":"[BRIDGE] extractObservables error > ModuleNotFoundError: No module named 'sigma.parser'","timestamp":"2021-04-08T23:56:41.277Z"}
```

##Error Log
```
cti@cti:/usr/share/opencti$ tail -f logs/error.log.2021-04-10
..
..
{"user":{"ip":"::1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","applicant_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","call_retry_number":""},"type":"WRITE_ERROR","operation_query":"mutation StixCoreRelationshipAdd($input:StixCoreRelationshipAddInput!){stixCoreRelationshipAdd(input:$input){id standard_id entity_type parent_types}}","inner_relation_creation":1,"operation":"StixCoreRelationshipAdd","time":103,"variables":{"input":{"fromId":"intrusion-set--c3fd6944-9625-11eb-8af7-005056bbef90","toId":"identity--c3fd6945-9625-11eb-8af7-005056bbef90","stix_id":"relationship--892b1c69-2d25-4190-876e-d19c911bbad2","relationship_type":"targets","description":"","start_time":null,"stop_time":null,"revoked":null,"confidence":15,"lang":null,"created":"2021-04-05T15:44:12.029315Z","modified":"2021-04-05T15:44:12.029315Z","createdBy":"identity--8e6dcb8c-953d-11eb-8af7-005056bbef90","objectMarking":["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"],"objectLabel":[],"externalReferences":[],"killChainPhases":[],"update":false}},"size":614,"error":{"data":{"reason":"Missing reference to handle creation","http_status":404,"category":"business","input":{"stix_id":"relationship--892b1c69-2d25-4190-876e-d19c911bbad2","fromId":"intrusion-set--c3fd6944-9625-11eb-8af7-005056bbef90","toId":"identity--c3fd6945-9625-11eb-8af7-005056bbef90","relationship_type":"targets","description":"","start_time":null,"stop_time":null,"confidence":15,"revoked":null,"lang":null,"createdBy":"identity--8e6dcb8c-953d-11eb-8af7-005056bbef90","objectMarking":["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"],"objectLabel":[],"externalReferences":[],"killChainPhases":[],"created":"2021-04-05T15:44:12.029Z","modified":"2021-04-05T15:44:12.029Z","update":false},"unresolvedIds":["identity--c3fd6945-9625-11eb-8af7-005056bbef90"]},"stacktrace":["MissingReferenceError: Element not found","at t (/usr/share/opencti/build/index.js:1:66904)","at D (/usr/share/opencti/build/index.js:1:68087)","at pe (/usr/share/opencti/build/index.js:1:13180)","at async Ae (/usr/share/opencti/build/index.js:1:29223)","at async /usr/share/opencti/build/index.js:1:231217"]},"version":"4.3.5","level":"error","message":"API Call","timestamp":"2021-04-10T14:55:02.450Z"}

```
## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 4.3.5

## 
[11-4-21.zip](https://github.com/OpenCTI-Platform/opencti/files/6291937/11-4-21.zip)

# Attached resent log files.

Regards,
Khalid

**Comment by SamuelHassine** [comment]
Hello,

Are you sure you've properly installed Python dependencies of the `requirements.txt` file under the`src/python` path in the OpenCTI GraphQL API?

This is documented here: https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1#fdbb8f9188ac4c2d95663a2d46a78a03.

Kind regards,
Samuel

**Comment by khalidrehan** [comment]
> Hello,
> 
> Are you sure you've properly installed Python dependencies of the `requirements.txt` file under the`src/python` path in the OpenCTI GraphQL API?
> 
> This is documented here: https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1#fdbb8f9188ac4c2d95663a2d46a78a03.
> 
> Kind regards,
> Samuel

Hello @SamuelHassine 

No, I did not install it, I just did and still receiving the same error.
![image](https://user-images.githubusercontent.com/37035465/114361829-4d99a980-9b7f-11eb-9b93-06ccffd568e1.png)


Regards,
Khalid.

**Comment by SamuelHassine** [comment]
Hello @khalidrehan,

Did you restart your platform? Please check that the sigma Python library is accessible from the Platform environment.

Kind regards,
Samuel

**Comment by khalidrehan** [comment]
> Hello @khalidrehan,
> 
> Did you restart your platform? Please check that the sigma Python library is accessible from the Platform environment.
> 
> Kind regards,
> Samuel

Hello @SamuelHassine ,

I restarted the platform, and still getting the same errors.
How to make sure the sigma Python library is accessible from the Platform environment?

Regards,
Khalid

**Comment by manonviallet** [comment]
Good afternoon @khalidrehan
Did you manage to solve your problem, or is it still active ?

**Comment by SamuelHassine** [comment]
Close this due to inactivity.
