### ISSUE TITLE
if (!isEmpty(unmanagedErrors)) throw new ApplicationError(error); throws an error 

### ISSUE THREAD

**Issue by kostiadovhyi** [OpenCTI-Platform/opencti#1330]
Everytime I login the dashboard, this works, I press escape and just ignore it but when I go to the connectors tab I see this:

![screenshot](https://i.imgur.com/s91XJZh.png)

and I can't get access to it.

**Comment by LeOndaz** [comment]
```
{"user":{"ip":"::ffff:127.0.0.1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"http://localhost:3000/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":12,"variables":{},"size":2,"error":{"stacktrace":["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)"]},"category":"APP","version":"4.5.0","level":"error","message":"API Call","timestamp":"2021-05-08T16:11:54.355Z"}
{"user":{"ip":"::ffff:127.0.0.1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"http://localhost:3000/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"ConnectorsStatusQuery","time":21,"variables":{},"size":2,"error":{"stacktrace":["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)"]},"category":"APP","version":"4.5.0","level":"error","message":"API Call","timestamp":"2021-05-08T16:11:54.370Z"}

```

What is expected to be running on the specified port but is not?

**Comment by kostiadovhyi** [comment]
```
{"user":{"ip":"::ffff:127.0.0.1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"http://localhost:3000/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"WorkersStatusQuery","time":12,"variables":{},"size":2,"error":{"stacktrace":["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)"]},"category":"APP","version":"4.5.0","level":"error","message":"API Call","timestamp":"2021-05-08T16:11:54.355Z"}
{"user":{"ip":"::ffff:127.0.0.1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"http://localhost:3000/dashboard/data/connectors"},"type":"READ_ERROR","operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}","inner_relation_creation":0,"operation":"ConnectorsStatusQuery","time":21,"variables":{},"size":2,"error":{"stacktrace":["Error: connect ECONNREFUSED 127.0.0.1:15672","at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)"]},"category":"APP","version":"4.5.0","level":"error","message":"API Call","timestamp":"2021-05-08T16:11:54.370Z"}
```
What is expected to be running but is not?

**Comment by SamuelHassine** [comment]
Hello @mykolasolonynka,

It seems that the RabbitMQ Management is not accessible. We will introduce a pre-check for that. Can you verify your RabbitMQ management? 

Kind regards,
Samuel
