### ISSUE TITLE
Elasticsearch multi-node connexion 

### ISSUE THREAD

**Issue by Tonnulus** [OpenCTI-Platform/opencti#1369]
## Problem to Solve

Allow to configure Elasticsearch cluster with Multiple Nodes.

## Current Workaround

I'm running OpenCTI 4.5.3 with a 3 nodes Elasticsearch cluster. 

OpenCTI seem to accept only one Elasticsearch URL on the configuration : 

```- ELASTICSEARCH__URL=http://elasticsearch1:9200```

If `elasticsearch1` runs out all my platform runs out. I wish I could configure multi-node:

```- ELASTICSEARCH__URL= ['http://elasticsearch1:9200', 'http://elasticsearch2:9200']```

I tried with several configurations, but it didn't work.

```
TypeError [ERR_INVALID_URL]: Invalid URL: '["http://elasticsearch:9200"]'
    at new NodeError (node:internal/errors:329:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    at getUsernameAndPassword (/opt/opencti/node_modules/@elastic/elasticsearch/index.js:304:38)
    at getAuth (/opt/opencti/node_modules/@elastic/elasticsearch/index.js:294:16)
    at new Client (/opt/opencti/node_modules/@elastic/elasticsearch/index.js:92:25)
    at Object.7018 (/opt/opencti/build/index.js:1:13417)
    at i (/opt/opencti/build/index.js:1:1855830)
    at Object.7914 (/opt/opencti/build/index.js:1:233252)
    at i (/opt/opencti/build/index.js:1:1855830)
    at Object.2784 (/opt/opencti/build/index.js:1:128917)
    at i (/opt/opencti/build/index.js:1:1855830)
    at /opt/opencti/build/index.js:1:1856501
    at Object.<anonymous> (/opt/opencti/build/index.js:1:1856527)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) {
  input: `'["http://elasticsearch:9200"]'`,
  code: 'ERR_INVALID_URL'
```

**Comment by SamuelHassine** [comment]
Hello @Tonnulus,

Can you please try:

```
- "ELASTICSEARCH__URL=[\"http://elastic1:9200\",\"http://elastic2:9200\"]" 
```
?

Kind regards,
Samuel

**Comment by Tonnulus** [comment]
Hello @SamuelHassine 
Thanks for your reply 
OpenCTI container seem to work, I have no errors. But history connector is not working:
```
docker logs -f opencti_connector-history_1
INFO:root:Listing Threat-Actors with filters null.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): opencti.:8080
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 144
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 534
INFO:root:Connector registered with ID:6d927475-bab9-4e26-b8d9-f3d2cc20979f
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): opencti.:8080
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 232
ERROR:root:No reason specify
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 98, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 21, in __init__
    self.logger_config = self.helper.api.get_logs_worker_config()
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 354, in get_logs_worker_config
    result = self.query(query)
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 271, in query
    raise ValueError(
ValueError: {'name': 'UnknownError', 'message': 'No reason specify'}
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti.
ERROR:root:Error pinging the API
DEBUG:urllib3.connectionpool:Starting new HTTP connection (3): opencti.:8080
ERROR:root:Error pinging the API
DEBUG:urllib3.connectionpool:Starting new HTTP connection (4): opencti.:8080
ERROR:root:Error pinging the API
DEBUG:urllib3.connectionpool:Starting new HTTP connection (5): opencti.:8080
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 141
ERROR:root:API Ping back to normal
INFO:root:Listing Threat-Actors with filters null.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): opencti.:8080
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 144
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 534
INFO:root:Connector registered with ID:6d927475-bab9-4e26-b8d9-f3d2cc20979f
INFO:root:Starting ping alive thread
INFO:root:Getting logs worker config...
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): opencti.:8080
DEBUG:urllib3.connectionpool:http://opencti.:8080 "POST /opencti/graphql HTTP/1.1" 200 232
ERROR:root:No reason specify
Traceback (most recent call last):
  File "/opt/opencti-connector-history/history.py", line 98, in <module>
    HistoryInstance = HistoryConnector()
  File "/opt/opencti-connector-history/history.py", line 21, in __init__
    self.logger_config = self.helper.api.get_logs_worker_config()
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 354, in get_logs_worker_config
    result = self.query(query)
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 271, in query
    raise ValueError(
ValueError: {'name': 'UnknownError', 'message': 'No reason specify'}
```

**Comment by ghost** [comment]
Hello, 
is there a solution?
I have the same problem on 'history' connector
thank you

**Comment by SamuelHassine** [comment]
Hello @lyess-ow, we will work on solving this bug.
