### ISSUE TITLE
Grakn Storage Fails to Start when using Docker-Compose on Debian

### ISSUE THREAD

**Issue by Bahia18** [OpenCTI-Platform/opencti#137]
Environment

    Debian 9
    OpenCTI latest version

Output

grakn_1          | Starting Storage......FAILED!
grakn_1          | Unable to start Storage.
...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
integration_1    | Waiting for token in shared config...
worker_1         | Waiting for token in shared config...
opencti_1        | Waiting Grakn to launch...
...

Grakn storage fails to start using docker-compose even though I pulled the latest version. I am working on a virtualbox vm.

**Comment by richard-julien** [comment]
Its a bit difficult to really help here because its more a grakn issue, but do you have enough memory on your JVM? I think you need at least 4Go available for grakn.

**Comment by Bahia18** [comment]
Thank you for your reply. Yes I checked if I had enough memory. The memory is above 4Go.

**Comment by richard-julien** [comment]
Can you get the grakn log file of your container to try to understand the problem?

**Comment by Bahia18** [comment]
I only have this in my container logs

Starting Storage.....FAILED!
Unable to start Storage.

**Comment by richard-julien** [comment]
According to grakn documentation you should have explanation in logs/cassandra.log or logs/grakn.log

**Comment by Bahia18** [comment]
Apparently it is caused by a timeout, ElasticSearch being too long to start. And even when grakn success to start there is a problem with opencti with the error: (node:416) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: failed to connect to all addresses

**Comment by SamuelHassine** [comment]
Hello @Bahia18: could you please checkout the last release (pull the repository), clear your docker deployment (by stopping Docker, removing all files from the Docker directory - /var/lib/docker - and starting Docker) and retry?

The problem should now be solved.

**Comment by richard-julien** [comment]
Closed for inactivity, dont hesitate to reopen the issue if needed.

**Comment by richard-julien** [comment]
Closed for inactivity, dont hesitate to reopen the issue if needed.

**Comment by toshiro92** [comment]
I have the same error as mentioned by this issue, with version 1.6.0 and 1.5.9:

```
====================================================================================================,
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______,
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|,
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |,
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____,
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|,
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____,
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|,
,
                                         THE KNOWLEDGE GRAPH,
====================================================================================================,
                                                                                      Version: 1.6.0,
Unable to start Storage.,
Starting Storage.....FAILED!,
Process exited with code '100': '',
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.,
Process exited with code '100': '',
	at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188),
	at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140),
	at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72),
2020-01-22 13:15:04,685 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.,
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '100': '',
	at grakn.core.daemon.executor.Storage.start(Storage.java:223),
	at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147),
	at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188),
	at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140),
	at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72),
```

However, when I use the following command:
> docker run -d -p 48555:48555 graknlabs/grakn:1.6.0

Everything work:

```
====================================================================================================,
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______,
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|,
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |,
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____,
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|,
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____,
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|,
,
                                         THE KNOWLEDGE GRAPH,
====================================================================================================,
                                                                                      Version: 1.6.0,
Starting Storage.......SUCCESS,
Starting Grakn Core Server......SUCCESS,
2020-01-22 13:18:28,345 [main] INFO  grakn.core.server.Grakn - Grakn started in 1.834 s,
```

There is the part of my docker-compose.yml file for grakn:
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.6.0
    container_name: opencti_grakn
    ports:
      - 48555:48555
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
```

**Comment by toshiro92** [comment]
Note: In 1.5.9, the error isn't as detailed as in 1.6.0:

```
====================================================================================================,
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______,
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|,
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |,
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____,
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|,
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____,
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|,
,
                                         THE KNOWLEDGE GRAPH,
====================================================================================================,
                                                                                      Version: 1.5.9,
Unable to start Storage.,
Starting Storage.....FAILED!
```

**Comment by LotoQ** [comment]
Hello, I have the same issue as Toshiro. 

things I have tried:
- stopped docker, removed all files in var/lib/docker, restarted docker and ran docker-compose again
- set in sysctl.conf the vm.max_map_count = 1048575

```
opencti@ubuntu:~/docker$ sudo docker logs 488e0584d89f
====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                       Version:1.5.9
Starting Storage.....FAILED!
Unable to start Storage.
```
But like Toshiro when I run it alone it succeeds:

```
sudo docker run -d -p 48555:48555 graknlabs/grakn:1.5.9
cad871cc7a671ff14b830d1eb66151389729806ddc149488e7d8c748ccc49baf

opencti@ubuntu:~/docker$ sudo docker logs cad871cc7a67
====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                       Version:1.5.9
Starting Storage......SUCCESS
Starting Grakn Core Server.....SUCCESS
2020-01-24 15:50:46,838 [main] INFO  grakn.core.server.Grakn - Grakn started in 325.4 ms

```

My docker-compose.yml grakn portion is as follows:

```

version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.9
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always

```


This is the output in my terminal when I do sudo docker-compose --compatibility up:



```
connector-export-file-stix_1  | INFO:root:Listing Threat-Actors with filters null.
connector-export-file-stix_1  | Traceback (most recent call last):
connector-export-file-stix_1  |   File "export-file-stix.py", line 62, in <module>
connector-export-file-stix_1  |     connectorExportFileStix = ExportFileStix()
connector-export-file-stix_1  |   File "export-file-stix.py", line 13, in __init__
connector-export-file-stix_1  |     self.helper = OpenCTIConnectorHelper(config)
connector-export-file-stix_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 181, in __init__
connector-export-file-stix_1  |     self.opencti_url, self.opencti_token, self.log_level
connector-export-file-stix_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
connector-export-file-stix_1  |     raise ValueError("OpenCTI API seems down")
connector-export-file-stix_1  | ValueError: OpenCTI API seems down
connector-import-file-stix_1  | INFO:root:Listing Threat-Actors with filters null.
connector-import-file-stix_1  | Traceback (most recent call last):
connector-import-file-stix_1  |   File "import-file-stix.py", line 29, in <module>
connector-import-file-stix_1  |     connectorImportFileStix = ImportFileStix()
connector-import-file-stix_1  |   File "import-file-stix.py", line 12, in __init__
connector-import-file-stix_1  |     self.helper = OpenCTIConnectorHelper(config)
connector-import-file-stix_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 181, in __init__
connector-import-file-stix_1  |     self.opencti_url, self.opencti_token, self.log_level
connector-import-file-stix_1  |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
connector-import-file-stix_1  |     raise ValueError("OpenCTI API seems down")
connector-import-file-stix_1  | ValueError: OpenCTI API seems down
connector-mitre_1             | INFO:root:Listing Threat-Actors with filters null.
connector-mitre_1             | Traceback (most recent call last):
connector-mitre_1             |   File "mitre.py", line 88, in <module>
connector-mitre_1             |     mitreConnector = Mitre()
connector-mitre_1             |   File "mitre.py", line 15, in __init__
connector-mitre_1             |     self.helper = OpenCTIConnectorHelper(config)
connector-mitre_1             |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 181, in __init__
connector-mitre_1             |     self.opencti_url, self.opencti_token, self.log_level
connector-mitre_1             |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
connector-mitre_1             |     raise ValueError("OpenCTI API seems down")
connector-mitre_1             | ValueError: OpenCTI API seems down
elasticsearch_1               | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
grakn_1                       | ====================================================================================================
grakn_1                       |       ________  _____     _______  __    __  __    __      _______  _______  _____     _______
grakn_1                       |      |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
grakn_1                       |      |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
grakn_1                       |      |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
grakn_1                       |      |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
grakn_1                       |      |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
grakn_1                       |      |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|
grakn_1                       | 
grakn_1                       |                                          THE KNOWLEDGE GRAPH
grakn_1                       | ====================================================================================================
grakn_1                       |                                                                                        Version:1.5.9
minio_1                       | 
minio_1                       |  You are running an older version of MinIO released 3 months ago 
minio_1                       |  Update: docker pull minio/minio:RELEASE.2020-01-16T22-40-29Z 
minio_1                       | 
minio_1                       | 
minio_1                       | Endpoint:  http://172.19.0.6:9000  http://127.0.0.1:9000
minio_1                       | 
minio_1                       | Browser Access:
minio_1                       |    http://172.19.0.6:9000  http://127.0.0.1:9000
minio_1                       | 
minio_1                       | Object API (Amazon S3 compatible):
minio_1                       |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_1                       |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_1                       |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_1                       |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_1                       |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
opencti_1                     | yarn run v1.19.1
opencti_1                     | $ node --max_old_space_size=8192 build/index.js
redis_1                       | 1:C 24 Jan 2020 15:46:54.962 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                       | 1:C 24 Jan 2020 15:46:54.962 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                       | 1:C 24 Jan 2020 15:46:54.962 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 * Running mode=standalone, port=6379.
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 # Server initialized
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                       | 1:M 24 Jan 2020 15:46:54.963 * Ready to accept connections
worker_1                      | INFO:root:Listing Threat-Actors with filters null.
worker_1                      | Traceback (most recent call last):
worker_1                      |   File "worker.py", line 174, in <module>
worker_1                      |     worker = Worker()
worker_1                      |   File "worker.py", line 120, in __init__
worker_1                      |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_1                      |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
worker_1                      |     raise ValueError("OpenCTI API seems down")
worker_1                      | ValueError: OpenCTI API seems down
opencti_1                     | error: [GRAKN] Seems down
opencti_1                     | error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
opencti_1                     |     at K (/opt/opencti/build/index.js:1:5450)
opencti_1                     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
opencti_1                     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
opencti_1                     | error Command failed with exit code 1.
connector-opencti_1           | INFO:root:Listing Threat-Actors with filters null.
connector-opencti_1           | Traceback (most recent call last):
connector-opencti_1           |   File "opencti.py", line 88, in <module>
connector-opencti_1           |     openCTIConnector = OpenCTI()
connector-opencti_1           |   File "opencti.py", line 15, in __init__
connector-opencti_1           |     self.helper = OpenCTIConnectorHelper(config)
connector-opencti_1           |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 181, in __init__
connector-opencti_1           |     self.opencti_url, self.opencti_token, self.log_level
connector-opencti_1           |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 110, in __init__
connector-opencti_1           |     raise ValueError("OpenCTI API seems down")
connector-opencti_1           | ValueError: OpenCTI API seems down
docker_connector-import-file-stix_1 exited with code 1
docker_connector-mitre_1 exited with code 1
docker_connector-export-file-stix_1 exited with code 1
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,833Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [79.7gb], net total_space [97.9gb], types [ext4]" }
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,863Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "heap size [990.7mb], compressed ordinary object pointers [true]" }
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,865Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "node name [d482310fca99], node ID [vb2lmS12QLCPBYdo8gadjQ], cluster name [docker-cluster]" }
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,866Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "version[7.5.2], pid[1], build[default/docker/8bec50e1e0ad29dad5653712cf3bb580cd1afcdf/2020-01-15T12:11:52.313576Z], OS[Linux/4.15.0-74-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.1/13.0.1+9]" }
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,867Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
elasticsearch_1               | {"type": "server", "timestamp": "2020-01-24T15:47:58,984Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "d482310fca99", "message": "JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-11692779750382853619, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
docker_worker_1 exited with code 1
docker_connector-opencti_1 exited with code 1
grakn_1                       | Starting Storage.....FAILED!
grakn_1                       | Unable to start Storage.

```

**Comment by LotoQ** [comment]
Hello, 

Just wanted to update that I did a clean install of Ubuntu 18.04 desktop, docker, docker-compose, etc. and no longer have this issue, however sometimes Grakn does fail to start, but simply aborting the docker-compose and relaunching seems to fix it for me. I do not know why it does this.

**Comment by SamuelHassine** [comment]
We migrate to Grakn 1.6.2 and this issue should now be fixed if you follow our documentation especially for the sysctl control. I close this issue, please re-open it if you still have some problems to launch Grakn Core Server.

**Comment by darcosion** [comment]
> 
> 
> Hello,
> 
> Just wanted to update that I did a clean install of Ubuntu 18.04 desktop, docker, docker-compose, etc. and no longer have this issue, however sometimes Grakn does fail to start, but simply aborting the docker-compose and relaunching seems to fix it for me. I do not know why it does this.

Hello, I have same error here with GRAKN 1.6.2, I've deployed with docker-compose and the standard docker-compose.yml file and sometimes, OpenCTI work, but often, they are a crash of Grakn Storage and after, OpenCTI API seem down.

**Comment by darcosion** [comment]
I try to debug the Grakn container, so I create a shell in : 
`docker exec -it [container_id] /bin/bash`

then, i do a `ps aux` for testing Grakn existence : 

    root@2d35fced9b61:/# ps aux
    USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    root         1  0.0  0.0  19720  3048 ?        Ss   14:54   0:00 bash ./grakn-docker.sh
    root        36 40.5 10.3 4816020 843672 ?      Sl   14:55   7:50 java -cp /grakn-core-all-linux/server/services/lib/*:/grakn-core-all
    root       224 42.5 11.7 4726580 956176 ?      Sl   14:56   7:45 java -cp /grakn-core-all-linux/server/services/lib/*:/grakn-core-all
    root       267  0.0  0.0   5968   648 ?        S    14:56   0:00 tail -f logs/grakn.log
    root      3905  0.5  0.0  19944  3544 pts/0    Ss   15:13   0:00 /bin/bash
    root      4449  0.0  0.0   5932   664 ?        S    15:13   0:00 sleep 60
    root      4727  0.0  0.0  38380  3072 pts/0    R+   15:14   0:00 ps aux

So Grakn seem to be started and functional.
But Grakn seem to have unusual and interesting logs, I'm doing the good way of debugging ? 
There is the interesting logs : 


    grakn.core.kb.server.exception.InvalidKBException: A structural validation error has occurred. Please correct the [`1`] errors found.
    There is more than one thing of type [Connector] that owns the key [ChangeMe] of type [internal_id_key].

**Comment by smclinden** [comment]
The online documentation implies that you only need to create the values for AUTH variables but that is a misinterpretation.

Everywhere in the docker-compose.json file where you see the comment **_# Valid UUDv4_** you need to put in a **_unique_** UUID. That is why you are getting the error. The Installation guide should be more clear about this.


>grakn.core.kb.server.exception.InvalidKBException: A structural validation error has occurred. Please correct the [`1`] errors found.
> There is more than one thing of type [Connector] that owns the key [ChangeMe] of type [internal_id_key].
> ```

**Comment by darcosion** [comment]
Thanks, I've fixed that, but the troubleshoot of Grakn storage seem to be unrelated to that, and more related to Grakn version instability.

**Comment by darcosion** [comment]
Hello @SamuelHassine I confirm than with new version, the instability of Grakn seem to be fixed. \o/
