### ISSUE TITLE
Project Setup: Facing while setting up project from guide

### ISSUE THREAD

**Issue by maxifjaved** [OpenCTI-Platform/opencti#1384]
I am trying to build the project from source and follow the instructions from the developer guide https://www.notion.so/luatix/Environment-setup-606996f36d904fcf8d434c6d0eae4a00

After following each step i have this issue.

```
{"category":"APP","version":"4.5.4","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-05-31T13:42:23.100Z"}
{"category":"APP","version":"4.5.4","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-05-31T13:42:23.174Z"}
{"error":{"name":"UnknownError","data":{"message":"The Access Key Id you provided does not exist in our records.","_stack":"S3Error: The Access Key Id you provided does not exist in our records.\n    at Object.parseError (/opencti/opencti-platform/opencti-graphql/node_modules/minio/dist/main/xml-parsers.js:79:11)\n    at /opencti/opencti-platform/opencti-graphql/node_modules/minio/dist/main/transformers.js:156:22\n    at DestroyableTransform._flush (/opencti/opencti-platform/opencti-graphql/node_modules/minio/dist/main/transformers.js:80:10)\n    at DestroyableTransform.prefinish (/opencti/opencti-platform/opencti-graphql/node_modules/readable-stream/lib/_stream_transform.js:129:10)\n    at DestroyableTransform.emit (events.js:376:20)\n    at prefinish(/opencti/opencti-platform/opencti-graphql/node_modules/readable-stream/lib/_stream_writable.js:611:14)\n    at finishMaybe (/opencti/opencti-platform/opencti-graphql/node_modules/readable-stream/lib/_stream_writable.js:620:5)\n    at endWritable (/opencti/opencti-platform/opencti-graphql/node_modules/readable-stream/lib/_stream_writable.js:643:3)\n    at DestroyableTransform.Writable.end (/opencti/opencti-platform/opencti-graphql/node_modules/readable-stream/lib/_stream_writable.js:571:22)\n    at IncomingMessage.onend (internal/streams/readable.js:684:10)\n    at Object.onceWrapper (events.js:482:28)\n    at IncomingMessage.emit (events.js:388:22)\n    at endReadableNT (internal/streams/readable.js:1336:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"}},"category":"APP","version":"4.5.4","level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-05-31T13:42:23.181Z"}
```

while running worker it says

```
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "worker.py", line 334, in <module>
    worker = Worker()
  File "worker.py", line 251, in __init__
    self.api = OpenCTIApiClient(
  File "/home/maxifjaved/.local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 141, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```

**Comment by SamuelHassine** [comment]
Hello @maxifjaved,

It seems the Access Key you've defined in MinIO is not the same you provide in the MINIO_ACCESS_KEY of the platform. Therefore OpenCTI is not able to access to your S3 bucket.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Closing this due to inactivity.
