### ISSUE TITLE
Sort report observables causes crash

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/opencti#1394]
## Description

When attempting to sort the observables in a report by "VALUE", the frontend crashes and displays:
> An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS Ubuntu 20.04
2. OpenCTI version: 4.5.4
3. OpenCTI client: frontend
4. Other environment details: docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create new report
2. Open newly created report
3. Go to the observables (in the report(
4. Click on "values" to sort the observables by value
5. Error/Crash
6. 
Note: This crash can be reproduced with reports which do contain observables. With an empty reports it's just the easiest to reproduce.

## Expected Output

Observables are sorted by value

## Actual Output

Browser Console:
```
Error:
    o https://opencti/static/js/2.438a8a33.chunk.js:2
    a https://opencti/static/js/2.438a8a33.chunk.js:2
    a https://opencti/static/js/main.de26727c.chunk.js:1
    render https://opencti/static/js/main.de26727c.chunk.js:1
    render https://opencti/static/js/2.438a8a33.chunk.js:2
    Ha https://opencti/static/js/2.438a8a33.chunk.js:2
    qa https://opencti/static/js/2.438a8a33.chunk.js:2
    Vs https://opencti/static/js/2.438a8a33.chunk.js:2
    Ec https://opencti/static/js/2.438a8a33.chunk.js:2
    Sc https://opencti/static/js/2.438a8a33.chunk.js:2
    Oc https://opencti/static/js/2.438a8a33.chunk.js:2
    vc https://opencti/static/js/2.438a8a33.chunk.js:2
    Gi https://opencti/static/js/2.438a8a33.chunk.js:2
    unstable_runWithPriority https://opencti/static/js/2.438a8a33.chunk.js:2
    Hi https://opencti/static/js/2.438a8a33.chunk.js:2
    Gi https://opencti/static/js/2.438a8a33.chunk.js:2
    Vi https://opencti/static/js/2.438a8a33.chunk.js:2
    fc https://opencti/static/js/2.438a8a33.chunk.js:2
    enqueueSetState https://opencti/static/js/2.438a8a33.chunk.js:2
    setState https://opencti/static/js/2.438a8a33.chunk.js:2
    handleDataChange https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    r https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    _error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    r https://opencti/static/js/2.438a8a33.chunk.js:2
    error https://opencti/static/js/2.438a8a33.chunk.js:2
    subscribe https://opencti/static/js/2.438a8a33.chunk.js:2
2.438a8a33.chunk.js:2:3045341

``` 

OpenCTI Log:

> {"user":{"ip":"::ffff:172.XX.XX.XX","user_id":"123123123123123123123123","referer":"https://opencti/dashboard/analysis/reports/b65731b7-3c16-4456-a555-f02f65d13df6/observables?sortBy=observable_value&orderAsc=true&searchTerm="},"type":"READ_ERROR","operation_query":"query ContainerStixCyberObservablesLinesQuery($id:String!$types:[String]$search:String$count:Int!$cursor:ID$orderBy:StixObjectOrStixRelationshipsOrdering$orderMode:OrderingMode$filters:[StixObjectOrStixRelationshipsFiltering]){container(id:$id){__typename ...ContainerStixCyberObservablesLines_container_4GmerJ id}}fragment ContainerStixCyberObservableLine_node on StixCyberObservable{__isStixCyberObservable:__typename id observable_value entity_type parent_types created_at createdBy{__typename ...on Identity{__isIdentity:__typename id name entity_type}}objectMarking{edges{node{id definition x_opencti_color}}}}fragment ContainerStixCyberObservablesLines_container_4GmerJ on Container{__isContainer:__typename id objects(types:$types search:$search first:$count after:$cursor orderBy:$orderBy orderMode:$orderMode filters:$filters){edges{node{__typename ...ContainerStixCyberObservableLine_node}cursor}pageInfo{endCursor hasNextPage globalCount}}}","inner_relation_creation":0,"operation":"ContainerStixCyberObservablesLinesQuery","time":1,"variables":{"id":"b65731b7-3c16-4456-a555-f02f65d13df6","types":["Stix-Cyber-Observable"],"search":"","count":25,"cursor":null,"orderBy":"observable_value","orderMode":"asc","filters":null},"size":178,"error":{"stacktrace":["GraphQLError: Variable \"$orderBy\" got invalid value \"observable_value\"; Value \"observable_value\" does not exist in \"StixObjectOrStixRelationshipsOrdering\" enum.","at /opt/opencti/node_modules/graphql/execution/values.js:116:15","at coerceInputValueImpl (/opt/opencti/node_modules/graphql/utilities/coerceInputValue.js:131:9)","at coerceInputValue (/opt/opencti/node_modules/graphql/utilities/coerceInputValue.js:37:10)","at _loop (/opt/opencti/node_modules/graphql/execution/values.js:109:69)","at coerceVariableValues (/opt/opencti/node_modules/graphql/execution/values.js:121:16)","at getVariableValues (/opt/opencti/node_modules/graphql/execution/values.js:50:19)","at buildExecutionContext (/opt/opencti/node_modules/graphql/execution/execute.js:203:61)","at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:101:20)","at Object.execute (/opt/opencti/node_modules/graphql/execution/execute.js:60:35)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:261:48","at Generator.next (<anonymous>)","at /opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","at new Promise (<anonymous>)","at __awaiter (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","at execute (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:240:20)","at Object.<anonymous> (/opt/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:177:42)"]},"category":"APP","version":"4.5.4","level":"error","message":"API Call","timestamp":"2021-06-02T18:35:00.316Z"}

## Additional information

The annoying thing is that the error persists for the report. Even after entirely refreshing the page. (Shift + Strg + R)

**Comment by nor3th** [comment]
Hey

I know this issue was fixed, but is there no alternative approach to this problem rather than simply removing the sorting ability? 

I have a report with like 1000 observables and having a sorting functionality (by type, value, marking definition, ...) would be helpful. As you can see in the screenshot, only the creation date is sortable, which isn't very helpful since all observables were created on the same day.

![screen](https://user-images.githubusercontent.com/73965465/132105610-1aec3546-c7c4-419b-a023-306b3e9c86fa.png)

Regards,
