### ISSUE TITLE
Error Displaying Intrusion Sets

### ISSUE THREAD

**Issue by kw2583** [OpenCTI-Platform/opencti#1502]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Navigating to the Intrusion Sets page produces an error that reads: Error An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 4.5.5
3. OpenCTI client: Frontend
4. Other environment details: Deployed with default Docker containers

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click "Threats" in left navigation window
2. Click "Intrusion Sets"
3. Error

`Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers. `

![Screen Shot 2021-08-04 at 07 42 27](https://user-images.githubusercontent.com/10215395/128183404-e88baaef-8abf-45e6-8d5d-f3d922747d86.png)

## Expected Output

Display tiles with intrusion sets

## Actual Output

See screenshot above.
 
## Additional information

Logs show a read error:

2021-08-04T11:45:01.452651316Z {"user":{"ip":"::ffff:192.168.100.61","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f","referer":"https://redacted.xyz/dashboard/threats/intrusion_sets?sortBy=name&orderAsc=true&searchTerm=&filters=%7B%7D"},"type":"**READ_ERROR**","operation_query":"query StixDomainObjectBookmarksQuery($types:[String]){...StixDomainObjectBookmarks_bookmarks_1OKkmt}fragment StixDomainObjectBookmark_node on StixDomainObject{__isStixDomainObject:__typename id entity_type parent_types created_at updated_at modified ...on AttackPattern{name x_mitre_id}...on Campaign{name}...on CourseOfAction{name}...on Individual{name}...on Organization{name}...on Sector{name}...on Indicator{name}...on Infrastructure{name}...on IntrusionSet{name}...on Position{name}...on City{name}...on Country{name}...on Region{name}...on Malware{name}...on ThreatActor{name}...on Tool{name}...on Vulnerability{name}...on Incident{name}createdBy{__typename ...on Identity{__isIdentity:__typename id name entity_type}}objectLabel{edges{node{id value color}}}objectMarking{edges{node{id definition x_opencti_color}}}}fragment StixDomainObjectBookmarks_bookmarks_1OKkmt on Query{bookmarks(types:$types first:200){edges{node{__typename id ...StixDomainObjectBookmark_node}cursor}pageInfo{endCursor hasNextPage}}}","inner_relation_creation":0,"operation":"StixDomainObjectBookmarksQuery","time":134,"variables":{"types":["Intrusion-Set"]},"size":27,"error":{"stacktrace":["Error: Cannot return null for non-nullable field StixDomainObjectEdge.node.","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:559:13)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)","at /opt/opencti/node_modules/graphql/execution/execute.js:620:25","at Array.map (<anonymous>)","at safeArrayFrom (/opt/opencti/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)","at completeListValue (/opt/opencti/node_modules/graphql/execution/execute.js:607:53)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:572:12)","at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)","at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)","at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)","at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)","at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)"]},"category":"APP","version":"4.5.5","level":"error","message":"API Call","timestamp":"2021-08-04T11:45:01.451Z"}

**Comment by richard-julien** [comment]
Thanks for the report.

Looks like bookmark deletion issue. @SamuelHassine ?

**Comment by SamuelHassine** [comment]
Yes I confirm @richard-julien. This will be fixed in 5.0.0.

**Comment by kw2583** [comment]
Are there any known workarounds that would fix the issue until a new release? Thanks
