### ISSUE TITLE
ElasticSearchMetrics GraphQL error: Int cannot represent non 32-bit signed integer value

### ISSUE THREAD

**Issue by h1lll0ck** [OpenCTI-Platform/opencti#1539]
## Description

It appears that an error is returned, either via the web UI or directly using the GraphQL API, when the Elasticsearch metric counts exceed the signed 32-bit integer maximum.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
1. OpenCTI version: 4.5.5
1. OpenCTI client: Web UI or GraphQL API

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Ingest/query data into/from Elasticsearch so that totals/counts are large (> 2147483647)
1. Web UI: Go to "Data" -> "Connectors" (or `/dashboard/data/connectors`)
1. API:
```
query WorkersStatusQuery {
  ...WorkersStatus_data
}
fragment WorkersStatus_data on Query {
  elasticSearchMetrics {
    docs {
      count
    }
    search {
      query_total
      fetch_total
    }
    indexing {
      index_total
      delete_total
    }
    get {
      total
    }
  }
  rabbitMQMetrics {
    consumers
    overview {
      queue_totals {
        messages
        messages_ready
        messages_unacknowledged
      }
      message_stats {
        ack
        ack_details {
          rate
        }
      }
    }
  }
}
```

## Expected Output

Web UI: Shows the worker, connector, etc. information and controls
API: Non-null values for the various totals (and no error message)

## Actual Output

Web UI: No worker or connector information/controls are displayed, instead an error message is shown:
```
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.
```

API: Response contains an error and one value is null (`"query_total": null`)
```
{
  "errors": [
    {
      "message": "An unknown error has occurred",
      "name": "UnknownError",
      "time_thrown": "2021-08-XXTXX:XX:XX.XXXZ",
      "data": {
        "reason": "No reason specify",
        "http_status": 500,
        "category": "technical"
      }
    }
  ],
  "data": {
    "elasticSearchMetrics": {
      "docs": {
        "count": 2517132
      },
      "search": {
        "query_total": null,
        "fetch_total": 95666763
      },
      "indexing": {
        "index_total": 1337393,
        "delete_total": 25280
      },
      "get": {
        "total": 371467
      }
    },
    "rabbitMQMetrics": {
      "consumers": 10,
      "overview": {
        "queue_totals": {
          "messages": 0,
          "messages_ready": 0,
          "messages_unacknowledged": 0
        },
        "message_stats": {
          "ack": null,
          "ack_details": null
        }
      }
    }
  }
}
```

## Additional information

Platform log entry:
```
{
  "user": {
    "ip": "XXXX",
    "user_id": "XXXX",
    "referer": "https://XXXX/opencti/graphql"
  },
  "type": "READ_ERROR",
  "operation_query": "query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}",
  "inner_relation_creation": 0,
  "operation": "WorkersStatusQuery",
  "time": 32,
  "variables": {},
  "size": 2,
  "error": {
    "stacktrace": [
      "GraphQLError: Int cannot represent non 32-bit signed integer value: 5375172659",
      "at GraphQLScalarType.serializeInt [as serialize] (/opt/opencti/node_modules/graphql/type/scalars.js:53:11)",
      "at completeLeafValue (/opt/opencti/node_modules/graphql/execution/execute.js:653:37)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:578:12)",
      "at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)",
      "at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)",
      "at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)",
      "at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)",
      "at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)",
      "at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)",
      "at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)",
      "at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)",
      "at /opt/opencti/node_modules/graphql/execution/execute.js:469:16",
      "at runMicrotasks (<anonymous>)",
      "at processTicksAndRejections (node:internal/process/task_queues:94:5)"
    ]
  },
  "category": "APP",
  "version": "4.5.5",
  "level": "error",
  "message": "API Call",
  "timestamp": "2021-08-XXTXX:XX:XX.XXXZ"
}
```

**Comment by h1lll0ck** [comment]
This same error was posted in issue 1401: https://github.com/OpenCTI-Platform/opencti/issues/1401#issuecomment-864990984
