### ISSUE TITLE
Problem with MISP

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/opencti#154]
Hi,

I update to the last version, but it seems that there is an issue with MISP connector, in particular misp.py:

```
connector-misp_1     | INFO:root:Fetching new MISP events...
connector-misp_1     | misp.py:75: DeprecationWarning: Call to deprecated method search. (Use ExpandedPyMISP.search) -- Deprecated since version 2.4.111.
connector-misp_1     |   result = self.misp.search('events', tags=[self.config['tag']])
```

Result is no import, of course.

Thanks

**Comment by SamuelHassine** [comment]
@weSh: it seems that you are not using the last version. Could you please `docker pull opencti/connector-misp`?

**Comment by AntoninHL** [comment]
Hey!

did it...

And now:

```
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
opencti_1            | Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
opencti_1            | Arguments:
opencti_1            | [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2019-07-25 7:32:53, _f: undefined, _strict: undefined, _locale: [object Object]
opencti_1            | Error
opencti_1            |     at Function.createFromInputFallback (/opt/opencti/node_modules/moment/moment.js:320:98)
opencti_1            |     at configFromString (/opt/opencti/node_modules/moment/moment.js:2385:15)
opencti_1            |     at configFromInput (/opt/opencti/node_modules/moment/moment.js:2611:13)
opencti_1            |     at prepareConfig (/opt/opencti/node_modules/moment/moment.js:2594:13)
opencti_1            |     at createFromConfig (/opt/opencti/node_modules/moment/moment.js:2561:44)
opencti_1            |     at createLocalOrUTC (/opt/opencti/node_modules/moment/moment.js:2648:16)
opencti_1            |     at createLocal (/opt/opencti/node_modules/moment/moment.js:2652:16)
opencti_1            |     at hooks (/opt/opencti/node_modules/moment/moment.js:12:29)
opencti_1            |     at n (/opt/opencti/dist/domain/queue.js:20:99)
opencti_1            |     at _map (/opt/opencti/node_modules/ramda/src/internal/_map.js:6:19)
opencti_1            |     at map (/opt/opencti/node_modules/ramda/src/map.js:64:14)
opencti_1            |     at /opt/opencti/node_modules/ramda/src/internal/_dispatchable.js:41:15
opencti_1            |     at f2 (/opt/opencti/node_modules/ramda/src/internal/_curry2.js:29:14)
opencti_1            |     at getMetrics (/opt/opencti/dist/domain/queue.js:20:38)
opencti_1            |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...
connector-misp_1     | Waiting RabbitMQ to launch...

```

Strange

**Comment by SamuelHassine** [comment]
Hello @weSh, it seems that the MISP connector has not the correct configuration for RabbitMQ, can you check the associated environments variables and verify that it matches your configuration? The message `Waiting RabbitMQ to launch` indicates that RabbitMQ could not be reached by the connector.

**Comment by AntoninHL** [comment]
Yep,

you're right... typo in my yml conf file.

After corrected it, same message as previously:

```
opencti_1            | 🚀 OpenCTI started in production mode with embedded file
connector-misp_1     | INFO:root:Fetching new MISP events...
connector-misp_1     | misp.py:75: DeprecationWarning: Call to deprecated method search. (Use ExpandedPyMISP.search) -- Deprecated since version 2.4.111.
connector-misp_1     |   result = self.misp.search('events', tags=[self.config['tag']])
```

If I grep scheduler.log and misp.log, everything regarding MISP are stropped just before the upgrade...

**Comment by SamuelHassine** [comment]
@weSh: You made the `docker pull` but you did not destroy the docker that is still on the old version. We fixed the `DeprecationWarning` in the last days. You can do it easily by `docker-compose down && docker pull opencti/connector-misp && docker-compose up`

**Comment by AntoninHL** [comment]
@SamuelHassine that's what I did... few times...

```
root@opencti:/opt/opencti/opencti-docker# docker-compose down --remove-orphans && docker pull opencti/connector-misp && docker-compose up
WARNING: Some services (worker-export, worker-import) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Stopping openctidocker_connector-mitre_1   ... done
Stopping openctidocker_connector-misp_1    ... done
Stopping openctidocker_worker-import_1     ... done
Stopping openctidocker_connector-opencti_1 ... done
Stopping openctidocker_worker-export_1     ... done
Stopping openctidocker_opencti_1           ... done
Stopping openctidocker_grakn_1             ... done
Stopping openctidocker_elasticsearch_1     ... done
Stopping openctidocker_rabbitmq_1          ... done
Stopping openctidocker_redis_1             ... done
Removing openctidocker_connector-mitre_1   ... done
Removing openctidocker_connector-misp_1    ... done
Removing openctidocker_worker-import_1     ... done
Removing openctidocker_connector-opencti_1 ... done
Removing openctidocker_worker-export_1     ... done
Removing openctidocker_opencti_1           ... done
Removing openctidocker_grakn_1             ... done
Removing openctidocker_elasticsearch_1     ... done
Removing openctidocker_rabbitmq_1          ... done
Removing openctidocker_redis_1             ... done
Removing network openctidocker_default
Using default tag: latest
latest: Pulling from opencti/connector-misp
Digest: sha256:f1e99f30b90723d2a4e8b45d614cebab5c6642ab0f3f74434210900ba0d6dbcf
Status: Image is up to date for opencti/connector-misp:latest
WARNING: Some services (worker-export, worker-import) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Creating network "openctidocker_default" with the default driver
Creating openctidocker_elasticsearch_1 ...
Creating openctidocker_grakn_1 ...
Creating openctidocker_redis_1 ...
Creating openctidocker_rabbitmq_1 ...
Creating openctidocker_redis_1
Creating openctidocker_elasticsearch_1
Creating openctidocker_rabbitmq_1
Creating openctidocker_rabbitmq_1 ... done
Creating openctidocker_opencti_1 ...
Creating openctidocker_opencti_1 ... done
Creating openctidocker_connector-misp_1 ...
Creating openctidocker_worker-import_1 ...
Creating openctidocker_worker-import_1
Creating openctidocker_connector-mitre_1 ...
Creating openctidocker_worker-export_1 ...
Creating openctidocker_worker-export_1
Creating openctidocker_connector-opencti_1 ...
Creating openctidocker_connector-misp_1
Creating openctidocker_connector-mitre_1
Creating openctidocker_worker-import_1 ... done
```

**Comment by AntoninHL** [comment]
always down...
I reinstall everything. And same problem.

**Comment by SamuelHassine** [comment]
@weSh: we just released the new version of the MISP connector. In this version your problem should be solved.!

**Comment by manonviallet** [comment]
Good morning @weSh . Could you tell us if your issue has been solved with the new release, so we can close it if so ?

**Comment by AntoninHL** [comment]
Hey @manonviallet !
Since the upgrade, it seems that MISP (and many other things...) are working.
But because everything is slow... slow... slow... I need to wait to be sure that it works well.

Many thanks!

**Comment by manonviallet** [comment]
Good if it has been fixed and thanks for the answer, I am closing the issue. As for the slowness, it is a problem we are dealing with (issue #185) and which should be fixed in the coming release :)
