### ISSUE TITLE
Investigations error when contains `resolves-to` relationship

### ISSUE THREAD

**Issue by h1lll0ck** [OpenCTI-Platform/opencti#1548]
## Description

The `resolves-to` link/relationship between Domain name and IPv4/v6 address Observables causes errors when included in Investigations.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
1. OpenCTI version: 4.5.5
1. OpenCTI client: Web UI

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Via the web UI or otherwise, create a Domain name Observable and an IPv4 address Observable
1. Go to the Domain name Observable, then "Knowledge" (`/dashboard/observations/observables/XXXX/knowledge`)
1. Use the `+` next to "Linked Observables" to create a `resolves-to` relationship between the Domain name and the IPv4 address
1. Go to "Investigations" then create a new Investigation (`/dashboard/workspaces/investigations/XXXX`)
1. Add the above Observables to the Investigation
1. Select both and expand to add entities of type Observable (all types of relationship - there is no `resolves-to` option)
1. Remove any non-Observable entities that are added (e.g. labels, markings, reports, etc.) - this seems to be a separate issue - leaving just the two Observables and the `resolves-to` link within the investigation
1. Go to a different page, e.g. the list of Investigations
1. Go back to the previously created Investigation to re-open it

## Expected Output

Displays Investigation as before, with the two Observables and the `resolves-to` link between them

## Actual Output

The Investigation is not shown, only an error message:
```
Error
An unknown error occurred. Please contact your administrator or the OpenCTI maintainers.
```
 
## Additional information

Platform log output:
```
{
  "user": {
    "ip": "XXXX",
    "user_id": "XXXX",
    "referer": "https://XXXX/opencti/dashboard/workspaces/investigations/XXXX"
  },
  "type": "READ_ERROR",
  "operation_query": "query InvestigationGraphQuery($id:String){workspace(id:$id){...InvestigationGraph_workspace id}}fragment InvestigationGraph_workspace on Workspace{id name description manifest graph_data tags owner{id name}objects(all:true){edges{node{__typename ...on BasicObject{__isBasicObject:__typename id entity_type parent_types}...on StixCoreObject{__isStixCoreObject:__typename created_at createdBy{__typename ...on Identity{__isIdentity:__typename id name entity_type}}objectMarking{edges{node{id definition}}}}...on StixDomainObject{__isStixDomainObject:__typename created}...on AttackPattern{name x_mitre_id}...on Campaign{name first_seen}...on CourseOfAction{name}...on Note{attribute_abstract content}...on ObservedData{first_observed last_observed}...on Opinion{opinion}...on Report{name published}...on Individual{name}...on Organization{name}...on Sector{name}...on Indicator{name valid_from}...on Infrastructure{name}...on IntrusionSet{name}...on Position{name}...on City{name}...on Country{name}...on Region{name}...on Malware{name first_seen last_seen}...on ThreatActor{name first_seen last_seen}...on Tool{name}...on Vulnerability{name}...on Incident{name first_seen last_seen}...on StixCyberObservable{__isStixCyberObservable:__typename observable_value}...on StixFile{observableName:name}...on StixMetaObject{__isStixMetaObject:__typename created}...on Label{value color}...on MarkingDefinition{definition x_opencti_color}...on ExternalReference{url source_name}...on BasicRelationship{__isBasicRelationship:__typename id entity_type parent_types}...on StixRelationship{__isStixRelationship:__typename from{__typename ...on BasicObject{__isBasicObject:__typename id entity_type parent_types}...on BasicRelationship{__isBasicRelationship:__typename id entity_type parent_types}...on StixCoreRelationship{relationship_type}}to{__typename ...on BasicObject{__isBasicObject:__typename id entity_type parent_types}...on BasicRelationship{__isBasicRelationship:__typename id entity_type parent_types}...on StixCoreRelationship{relationship_type}}}...on StixMetaRelationship{created_at}...on StixCoreRelationship{relationship_type start_time stop_time confidence created created_at createdBy{__typename ...on Identity{__isIdentity:__typename id name entity_type}}objectMarking{edges{node{id definition}}}}}}}}",
  "inner_relation_creation": 0,
  "operation": "InvestigationGraphQuery",
  "time": 109,
  "variables": {
    "id": "XXXX"
  },
  "size": 45,
  "error": {
    "stacktrace": [
      "GraphQLError: Abstract type \"StixObjectOrStixRelationship\" was resolve to a type \"ResolvesTo\" that does not exist inside schema.",
      "at ensureValidRuntimeType (/opt/opencti/node_modules/graphql/execution/execute.js:698:11)",
      "at completeAbstractValue (/opt/opencti/node_modules/graphql/execution/execute.js:680:42)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:584:12)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:556:21)",
      "at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)",
      "at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)",
      "at collectAndExecuteSubfields (/opt/opencti/node_modules/graphql/execution/execute.js:748:10)",
      "at completeObjectValue (/opt/opencti/node_modules/graphql/execution/execute.js:738:10)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:590:12)",
      "at /opt/opencti/node_modules/graphql/execution/execute.js:620:25",
      "at Array.map (<anonymous>)",
      "at safeArrayFrom (/opt/opencti/node_modules/graphql/jsutils/safeArrayFrom.js:36:23)",
      "at completeListValue (/opt/opencti/node_modules/graphql/execution/execute.js:607:53)",
      "at completeValue (/opt/opencti/node_modules/graphql/execution/execute.js:572:12)",
      "at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:472:19)",
      "at executeFields (/opt/opencti/node_modules/graphql/execution/execute.js:292:18)"
    ]
  },
  "category": "APP",
  "version": "4.5.5",
  "level": "error",
  "message": "API Call",
  "timestamp": "2021-09-XXTXX:XX:XX.XXXZ"
}
```

**Comment by h1lll0ck** [comment]
Being unable to open the Investigation in the web UI also means that it can't be deleted via the web UI
