### ISSUE TITLE
Minor spelling mistake in some relationship error messages

### ISSUE THREAD

**Issue by h1lll0ck** [OpenCTI-Platform/opencti#1549]
## Description

Some error messages misspell "through" as "trough".

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
1. OpenCTI version: 4.5.5
1. OpenCTI client: Web UI

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import (e.g. via a connector) some STIX2 JSON that includes a Relationship of type `resolves-to`
2. Observe the platform log output for an error message

## Expected Output

Error message:
```
Only stix-core-relationship can be created through this method.
```

## Actual Output

Error message:
```
Only stix-core-relationship can be created trough this method.
```

## Additional information

A search of the repo for "trough" finds these:
- Line 20: https://github.com/OpenCTI-Platform/opencti/blob/d0e2f6dbf4655ecbcf6dff5d08a5d7b58621e5ef/opencti-platform/opencti-graphql/src/domain/stixCyberObservableRelationship.js
- Lines 123 and 135: https://github.com/OpenCTI-Platform/opencti/blob/4bf7be4ec8df1d9cf1e1ef8a93c08b27a251ea8b/opencti-platform/opencti-graphql/src/domain/stixCoreRelationship.js

Platform log output
```
{
  "user": {
    "ip": "XXXX",
    "user_id": "XXXX",
    "applicant_id": "XXXX",
    "call_retry_number": "1"
  },
  "type": "WRITE_ERROR",
  "operation_query": "mutation
StixCoreRelationshipAdd($input:StixCoreRelationshipAddInput!){stixCoreRelationshipAdd(input:$input){id standard_id entity_type parent_types}}",
  "inner_relation_creation": 1,
  "operation": "StixCoreRelationshipAdd",
  "time": 1,
  "size": 707,
  "error": {
    "data": {
      "reason": "Only stix-core-relationship can be created trough this method.",
      "http_status": 400,
      "category": "business"
    },
    "stacktrace": [
      "FunctionalError: Business validation",
      "at m (/opt/opencti/build/index.js:1:5275)",
      "at T (/opt/opencti/build/index.js:1:6191)",
      "at /opt/opencti/build/index.js:1:187066",
      "at et.stixCoreRelationshipAdd (/opt/opencti/build/index.js:1:187204)",
      "at et.authenticationControl (/opt/opencti/build/index.js:1:231764)",
      "at t.resolve (/opt/opencti/build/index.js:1:232336)",
      "at field.resolve (/opt/opencti/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)",
      "at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:464:18)",
      "at /opt/opencti/node_modules/graphql/execution/execute.js:261:18",
      "at /opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10",
      "at Array.reduce (<anonymous>)",
      "at promiseReduce (/opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)",
      "at executeFieldsSerially (/opt/opencti/node_modules/graphql/execution/execute.js:258:37)",
      "at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:236:55)"
    ]
  },
  "category": "APP",
  "version": "4.5.5",
  "level": "warn",
  "message": "API Call",
  "timestamp": "2021-09-XXTXX:XX:XX.XXXZ"
}
```

**Comment by h1lll0ck** [comment]
The error message can also be seen in a screenshot in issue 1108: https://github.com/OpenCTI-Platform/opencti/issues/1108
