### ISSUE TITLE
Unhandled Promise rejection while yarn start

### ISSUE THREAD

**Issue by AhmedAkkarii** [OpenCTI-Platform/opencti#190]
I just followed every step on the guide for the development environments, and when it gets to the **yarn start** on graphql folder this is what happen:

root@ubuntu:/home/openctidev/opencti/opencti-platform/opencti-graphql# yarn start
```
yarn run v1.17.3
$ yarn schema --env=development && yarn migrate --env=development && babel-node -r node_modules/dotenv/config ./src/server.js --e development
$ babel-node ./src/schema/schema-init.js --env=development
🚀 OpenCTI started in development mode with embedded file
(node:7082) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: TCP Write failed
    at Object.exports.createStatusError (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:845:24)
(node:7082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7082) UnhandledPromiseRejectionWarning: ConnectionError: socket hang up
    at onResponse (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/@elastic/elasticsearch/lib/Transport.js:220:13)
    at ClientRequest.request.on.err (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/@elastic/elasticsearch/lib/Connection.js:114:9)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:7082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by richard-julien** [comment]
Its look like elasticsearch is not available. Can you check your deployment and configuration?

**Comment by AhmedAkkarii** [comment]
I have already check them, I only have the option to check on docker:

root@ubuntu:/home/openctidev# docker container ps -a
```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
83df00ff740d        graknlabs/grakn:1.5.7                                 "./grakn-docker.sh"      20 hours ago        Up About an hour    0.0.0.0:48555->48555/tcp                                                                     opencti-dev-grakn
7413ec56dd55        rabbitmq:3.7.16-management                            "docker-entrypoint.s…"   20 hours ago        Up About an hour    4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   opencti-dev-rabbitmq
2526fc99ca3e        docker.elastic.co/elasticsearch/elasticsearch:7.2.0   "/usr/local/bin/dock…"   20 hours ago        Up 14 seconds       0.0.0.0:9200->9200/tcp, 9300/tcp                                                             opencti-dev-elasticsearch-01
b38c74ba1e10        redis:5.0.5                                           "docker-entrypoint.s…"   20 hours ago        Up About an hour    0.0.0.0:6379->6379/tcp                                                                       opencti-dev-redis
```

**Comment by richard-julien** [comment]
2526fc99ca3e        docker.elastic.co ... > Up 14 seconds

It seems the elastic cannot start, and so reboot every time.
You have to check the logs of this docker to understand the problem.

**Comment by AhmedAkkarii** [comment]
I issued :
`docker logs --details 2526fc99ca3e`

and im not sure if this could actually be the problem Highlighted in listed log causing the ES to restart every time

```
{"type": "server", "timestamp": "2019-08-22T09:28:36,166+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "2526fc99ca3e",  "message": "starting ..."  }
 {"type": "server", "timestamp": "2019-08-22T09:28:36,412+0000", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "2526fc99ca3e",  "message": "publish_address {172.18.0.5:9300}, bound_addresses {0.0.0.0:9300}"  }
 {"type": "server", "timestamp": "2019-08-22T09:28:36,426+0000", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "2526fc99ca3e",  "message": "**bound or publishing to a non-loopback address, enforcing bootstrap checks**"  }
 ERROR: [1] bootstrap checks failed
 [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
 {"type": "server", "timestamp": "2019-08-22T09:28:36,454+0000", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "2526fc99ca3e",  "message": "stopping ..."  }
```

**Comment by richard-julien** [comment]
Take a look to this [doc page](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode), it should help.

**Comment by AhmedAkkarii** [comment]
I've changed the docker-compose-dev.yml file within the ES section and the problem has gone, here's the new one: 

```
version: '3'
services:
  opencti-dev-grakn:
    container_name: opencti-dev-grakn 
    image: graknlabs/grakn:1.5.7
    restart: always
    ports:
      - 48555:48555
  opencti-dev-redis:
    container_name: opencti-dev-redis
    image: redis:5.0.5
    restart: always
    ports:
      - 6379:6379
  opencti-dev-elasticsearch-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  opencti-dev-rabbitmq:
    container_name: opencti-dev-rabbitmq
    image: rabbitmq:3.7.16-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

```
and the new log output of the ES shows this:


`{"type": "server", "timestamp": "2019-08-23T10:13:37,033+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "627fc46f7a12", "cluster.uuid": "6MI9JXfHTAyrJre5Z1q7Qg", "node.id": "G8IYHdCmS8qZtOxxBpsX8g",  "message": "Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[stix_domain_entities][0], [stix_observables][0], [external_references][0]] ...])."  }`

But the main problem still persistent as the same error 

```
root@ubuntu:/home/openctidev/opencti/opencti-platform/opencti-graphql# yarn start
yarn run v1.17.3
$ yarn schema --env=development && yarn migrate --env=development && babel-node -r node_modules/dotenv/config ./src/server.js --e development
$ babel-node ./src/schema/schema-init.js --env=development
🚀 OpenCTI started in development mode with embedded file
(node:4368) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: TCP Write failed
    at Object.exports.createStatusError (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/openctidev/opencti/opencti-platform/opencti-graphql/node_modules/grpc/src/client_interceptors.js:845:24)
(node:4368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by richard-julien** [comment]
Its look like your using a old version of the docker compose file containing a bug in port declaration.
Please use the current https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose-dev.yml file. (basically its add the declaration of the port 9300 for elastic)

**Comment by AhmedAkkarii** [comment]
I tested it, but no luck, same result.
I would like to know if I'm cloning the right dev project as you've mentioned that it is an old compose file 
git clone --recursive https://github.com/LuatixHQ/opencti.git

**Comment by richard-julien** [comment]
The official dev project is https://github.com/OpenCTI-Platform/opencti
You clone the luatix fork.

**Comment by AhmedAkkarii** [comment]
Im following the doc guide as it's mentioned :
git clone --recursive https://github.com/Luatix/opencti.git 
But the link doesn't work, so I changed it from Luatix to LuatixHQ.

**Comment by richard-julien** [comment]
Hum ... the doc is false, sorry for that. I will fix it right now.

**Comment by AhmedAkkarii** [comment]
The Development environment im using till now : https://opencti-platform.github.io/docs/development/installation
Will you provide me the real Development environment for OpenCTI.

**Comment by richard-julien** [comment]
Docker compose to use is:  https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose-dev.yml 
Code is: https://github.com/OpenCTI-Platform/opencti
I currently fixing the documentation

**Comment by richard-julien** [comment]
Dont hesitate to reopen the issue or create a new one if documentation is still confusing.
