### ISSUE TITLE
CAPE / Cuckoo connector can't work

### ISSUE THREAD

**Issue by Oddluo** [OpenCTI-Platform/opencti#1977]
## Description
CAPE / Cuckoo Connector can't work. 
This is my docker log.

CONNECTOR = capeConnector()
  File "/opt/opencti-cape/main.py", line 21, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-cape/main.py", line 187, in <module>
    raise e
  File "/opt/opencti-cape/main.py", line 184, in <module>
    CONNECTOR = capeConnector()
  File "/opt/opencti-cape/main.py", line 21, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-cape/main.py", line 187, in <module>
    raise e
  File "/opt/opencti-cape/main.py", line 184, in <module>
    CONNECTOR = capeConnector()
  File "/opt/opencti-cape/main.py", line 21, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: eee
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:None
ERROR:root:Error connecting to Cape API
ERROR:root:HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f785eeb53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f785eeb53d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f785eeb53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-cape/main.py", line 187, in <module>
    raise e
  File "/opt/opencti-cape/main.py", line 185, in <module>
    CONNECTOR.run()
  File "/opt/opencti-cape/main.py", line 133, in run
    raise (err)
  File "/opt/opencti-cape/main.py", line 128, in run
    self.cape_api.getCuckooTasks()
  File "/opt/opencti-cape/cape/cape.py", line 806, in getCuckooTasks
    response = self._make_request(Method, EP)
  File "/opt/opencti-cape/cape/cape.py", line 837, in _make_request
    resp = requests.request(method, URL, verify=self.verify)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f785eeb53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

the config is the same as other connectors, just the CAPE and cuckoo can't work.

![图片](https://user-images.githubusercontent.com/67694128/159419125-70a9b52c-5dc8-4936-b580-a2d39bdf5aab.png)

## Environment

 OpenCTI version: { 5.2.1 }

**Comment by nor3th** [comment]
Closing this due double posting https://github.com/OpenCTI-Platform/connectors/issues/636
