### ISSUE TITLE
Bug when exporting objects (in this case, observables

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/opencti#2335]
## Description

When exporting observables to CSV, we get the following error: 'utf-8' codec can't encode characters in position 53024-53032: surrogates not allowed

In the end, no observables are exported

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.10
2. OpenCTI version: 5.3.7
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Go to observables page
2. Optional: filter on relevant observable type
3. Export to CSV

## Expected Output

Export completes successfully

## Actual Output

See below screenshot, which contains the error

## Additional information

This link may be relevant: [https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s](https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s)

Follow up question - is there a way to export observables via the API?

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/78382789/189191788-2f0cb8cf-7f1d-4a30-8a2f-1f6ccfb6ce3b.png)

**Comment by SamuelHassine** [comment]
Hello @securitiz,

Can you share the log of the export CSV connector please?

Kind regards,
Samuel

**Comment by securitiz** [comment]
@SamuelHassine i've attached the logs leading to the error, as well as the error itself:

`2022-09-09T09:32:55.094-05:00	INFO:root:Listing StixCyberObservables after WzE2MTQ5ODg5MDc4NjcsImZpbGUtLWEyY2JjOWFkLTFkY2MtNTljZi1hYWViLWI5N2RjNzEwYTA5NCJd
2022-09-09T09:32:55.843-05:00	INFO:root:Listing StixCyberObservables after WzE2MTM0MzI1MDI3OTQsImZpbGUtLTBiYzlhMjY3LThhMDUtNTBmYy04ZGVhLWVkOTA1NTkxMjY5NCJd
2022-09-09T09:32:56.657-05:00	INFO:root:Uploading: Stix-Cyber-Observable/all to 2022-09-09T14:32:13.706Z_TLP:ALL_(ExportFileCsv)_Stix-Cyber-Observable_all.false
2022-09-09T09:32:56.659-05:00	ERROR:root:Error in message processing, reporting error to API
2022-09-09T09:32:56.659-05:00	Traceback (most recent call last):
2022-09-09T09:32:56.659-05:00	File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler
2022-09-09T09:32:56.659-05:00	message = self.callback(json_data["event"])
2022-09-09T09:32:56.659-05:00	File "/opt/opencti-connector-export-file-csv/export-file-csv.py", line 246, in _process_message
2022-09-09T09:32:56.659-05:00	self.helper.api.stix_cyber_observable.push_list_export(
2022-09-09T09:32:56.659-05:00	File "/usr/local/lib/python3.10/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1772, in push_list_export
2022-09-09T09:32:56.659-05:00	self.opencti.query(
2022-09-09T09:32:56.659-05:00	File "/usr/local/lib/python3.10/site-packages/pycti/api/opencti_api_client.py", line 270, in query
2022-09-09T09:32:56.659-05:00	(files.name, io.BytesIO(files.data.encode()), files.mime),
2022-09-09T09:32:56.659-05:00	UnicodeEncodeError: 'utf-8' codec can't encode characters in position 56580-56588: surrogates not allowed
2022-09-09T09:32:56.659-05:00	INFO:root:Reporting work update_received opencti-work--a726f408-6dd0-4cbf-8c05-d9589b07750a
2022-09-09T09:32:56.953-05:00	INFO:root:Message (delivery_tag=6) processed, thread terminated`
