### ISSUE TITLE
Errors when importing Stix

### ISSUE THREAD

**Issue by annoyingapt** [OpenCTI-Platform/opencti#2889]
## Description

I get a invalid value for Report error when I try to import a STIX bundle. Any help getting this one sorted would be great.

## Environment

- OS (where OpenCTI server runs): Portainer stack
- OpenCTI version: OpenCTI 5.5.4

## Reproducible Steps

Export indicators out of OpenCTI into STIX.
Create new Report
Data
Upload JSON file

## Expected Output

Expect the bundle to import so I can progress to analyst workbench.

## Error logs

```
INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | timestamp=2023-02-16T02:47:39.052837Z INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | timestamp=2023-02-16T02:47:39.052837Z name=pycti.api
INFO INFO INFO INFO Importing the file http://opencti:8080/storage/get/import/Report/cde344b1-ef20-4f05-b65f-c2a0c71b77bd/2023-02-16T02 27 36.358Z_TLP ALL_(ExportFileStix2)_Indicator_full.json | INFO INFO INFO INFO Importing the file http://opencti:8080/storage/get/import/Report/cde344b1-ef20-4f05-b65f-c2a0c71b77bd/2023-02-16T02 27 36.358Z_TLP ALL_(ExportFileStix2)_Indicator_full.json | timestamp=2023-02-16T02:47:39.086111Z INFO INFO INFO INFO Importing the file http://opencti:8080/storage/get/import/Report/cde344b1-ef20-4f05-b65f-c2a0c71b77bd/2023-02-16T02 27 36.358Z_TLP ALL_(ExportFileStix2)_Indicator_full.json | INFO INFO INFO INFO Importing the file http://opencti:8080/storage/get/import/Report/cde344b1-ef20-4f05-b65f-c2a0c71b77bd/2023-02-16T02 27 36.358Z_TLP ALL_(ExportFileStix2)_Indicator_full.json | timestamp=2023-02-16T02:47:39.086111Z name=pycti.connector
INFO INFO INFO INFO Contextual import. | INFO INFO INFO INFO Contextual import. | timestamp=2023-02-16T02:47:39.098043Z INFO INFO INFO INFO Contextual import. | INFO INFO INFO INFO Contextual import. | timestamp=2023-02-16T02:47:39.098043Z name=pycti.connector
INFO INFO INFO INFO No Report in Stix file. Updating current report | INFO INFO INFO INFO No Report in Stix file. Updating current report | timestamp=2023-02-16T02:47:39.098262Z INFO INFO INFO INFO No Report in Stix file. Updating current report | INFO INFO INFO INFO No Report in Stix file. Updating current report | timestamp=2023-02-16T02:47:39.098262Z name=pycti.connector
INFO INFO INFO INFO Reading Report {cde344b1-ef20-4f05-b65f-c2a0c71b77bd}. | INFO INFO INFO INFO Reading Report {cde344b1-ef20-4f05-b65f-c2a0c71b77bd}. | timestamp=2023-02-16T02:47:39.098354Z INFO INFO INFO INFO Reading Report {cde344b1-ef20-4f05-b65f-c2a0c71b77bd}. | INFO INFO INFO INFO Reading Report {cde344b1-ef20-4f05-b65f-c2a0c71b77bd}. | timestamp=2023-02-16T02:47:39.098354Z name=pycti.entities
ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-02-16T02:47:40.088406Z ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-02-16T02:47:40.088406Z name=root ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-02-16T02:47:40.088406Z ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | ERROR ERROR ERROR ERROR Error in message processing, reporting error to API | timestamp=2023-02-16T02:47:40.088406Z name=root exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/stix2/properties.py", line 74, in _validate_id
    result = _check_uuid(uuid_part, spec_version)
  File "/usr/local/lib/python3.10/site-packages/stix2/properties.py", line 42, in _check_uuid
    uuid_obj = uuid.UUID(uuid_str)
  File "/usr/local/lib/python3.10/uuid.py", line 177, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/stix2/base.py", line 50, in _check_property
    kwargs[prop_name], has_custom = prop.clean(
  File "/usr/local/lib/python3.10/site-packages/stix2/properties.py", line 240, in clean
    valid, temp_custom = self.contained.clean(item, allow_custom)
  File "/usr/local/lib/python3.10/site-packages/stix2/properties.py", line 549, in clean
    _validate_id(value, self.spec_version, None)
  File "/usr/local/lib/python3.10/site-packages/stix2/properties.py", line 77, in _validate_id
    raise ValueError(ERROR_INVALID_ID.format(id_))
ValueError: not a valid STIX identifier, must match <object-type>--<UUID>: {'id': 'indicator--8d30e978-c6dd-5439-9ed0-bd61238915c3', 'spec_version': '2.1', 'revoked': False, 'confidence': 15, 'created': '2023-02-16T02:27:00.877Z', 'modified': '2023-02-16T02:27:00.900Z', 'pattern_type': 'stix', 'pattern': "[file:hashes.'SHA-256' = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']", 'name': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'description': 'Simple indicator of observable {e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}', 'valid_from': '2023-02-16T02:27:00.871Z', 'valid_until': '2024-02-16T02:27:00.871Z', 'x_opencti_score': 10, 'x_opencti_detection': False, 'x_opencti_main_observable_type': 'StixFile', 'labels': ['hygiene'], 'x_opencti_id': 'bb3f7d91-14ca-4113-a55b-bafd8a469c58', 'type': 'indicator'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 167, in _process_message
    json_data["internal"]["work_id"], message_task.result()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/opencti-connector-import-file-stix/import-file-stix.py", line 47, in _process_message
    bundle = self._update_report(bundle, entity_id)
  File "/opt/opencti-connector-import-file-stix/import-file-stix.py", line 80, in _update_report
    report = Report(
  File "/usr/local/lib/python3.10/site-packages/stix2/base.py", line 203, in __init__
    temp_custom = self._check_property(
  File "/usr/local/lib/python3.10/site-packages/stix2/base.py", line 58, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Report 'object_refs': not a valid STIX identifier, must match <object-type>--<UUID>: {'id': 'indicator--8d30e978-c6dd-5439-9ed0-bd61238915c3', 'spec_version': '2.1', 'revoked': False, 'confidence': 15, 'created': '2023-02-16T02:27:00.877Z', 'modified': '2023-02-16T02:27:00.900Z', 'pattern_type': 'stix', 'pattern': "[file:hashes.'SHA-256' = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855']", 'name': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'description': 'Simple indicator of observable {e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}', 'valid_from': '2023-02-16T02:27:00.871Z', 'valid_until': '2024-02-16T02:27:00.871Z', 'x_opencti_score': 10, 'x_opencti_detection': False, 'x_opencti_main_observable_type': 'StixFile', 'labels': ['hygiene'], 'x_opencti_id': 'bb3f7d91-14ca-4113-a55b-bafd8a469c58', 'type': 'indicator'}
INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | timestamp=2023-02-16T02:47:40.088838Z INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | INFO INFO INFO INFO Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-16T02:47:38.979Z | timestamp=2023-02-16T02:47:40.088838Z name=pycti.api
INFO INFO INFO INFO Message (delivery_tag=12) processed, thread terminated | INFO INFO INFO INFO Message (delivery_tag=12) processed, thread terminated | timestamp=2023-02-16T02:47:40.116604Z INFO INFO INFO INFO Message (delivery_tag=12) processed, thread terminated | INFO INFO INFO INFO Message (delivery_tag=12) processed, thread terminated | timestamp=2023-02-16T02:47:40.116604Z name=pycti.connector
```

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/55898651/219253928-26484984-1046-4fa9-9aac-bcd636966ff4.png)

**Comment by richard-julien** [comment]
Hi @annoyingapt , can you provide the stix bundle ? Thanks

**Comment by annoyingapt** [comment]
[2023-02-16T02 27 36.358Z_TLP ALL_(ExportFileStix2)_Indicator_full.zip](https://github.com/OpenCTI-Platform/opencti/files/10753895/2023-02-16T02.27.36.358Z_TLP.ALL_.ExportFileStix2._Indicator_full.zip)

Here you go

**Comment by SamuelHassine** [comment]
Taking it.
