### ISSUE TITLE
MISP connector crashing with "TypeError"

### ISSUE THREAD

**Issue by human4357** [OpenCTI-Platform/opencti#2924]
## Description

MISP connector fails to bring in events. Checking the logs shows "TypeError: argument of type 'NoneType' is not iterable"

## Environment

1. Ubuntu 20.04
2. 5.5.4
3. Python
4. Other environment details: Using Docker compose.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Launch OpenCTI via docker compose using provided instructions. 
2. Configure the MISP connector for your environment (https://github.com/OpenCTI-Platform/connectors/tree/master/external-import/misp)
3. Run connector. 

## Expected Output

Connector reaches MISP instance & pulls the events into OpenCTI

## Actual Output
Receive error:
"Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 2151, in <module>
    mispConnector.run()
  File "/opt/opencti-connector-misp/misp.py", line 374, in run
    if "current_page" in current_state:
TypeError: argument of type 'NoneType' is not iterable
Terminated"

## Additional information

MISP instance is built on ubuntu 20.04 with the provided install script. One feed is connected (CIRCL.LU)

## Screenshots (optional)
![misp_error](https://user-images.githubusercontent.com/45048796/220999497-dd126258-866e-4dc7-9824-fa29b82e742f.png)
![misp_error2](https://user-images.githubusercontent.com/45048796/220999502-7132894b-aa89-4f38-8a2f-6e97be2e1fda.png)

**Comment by thezolin** [comment]
Same scenario here.

**Comment by human4357** [comment]
> Same scenario here.

Building the image locally appears to have resolved the issue

**Comment by thezolin** [comment]
Hello, 
Any idea how can I do this? I'm trying to using docker-compose with --build flag but still the same. 
`docker-compose -f docker-compose.yml up -d --build connector-misp`

Thank you in advance
