### ISSUE TITLE
Error when running Mandiant Connector: "An URL must be set"

### ISSUE THREAD

**Issue by Aspidoquelona** [OpenCTI-Platform/opencti#3849]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04 LTS
3. OpenCTI version: OpenCTI 5.9.6
4. OpenCTI client: python
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Manual activation: cd opencti/connectors/external-import/mandiant/src
2. pip3 install -r requirements.txt
3. cp config.yml.sample config.yml
4. Change the config.yml content according to the parameters of the platform and of the targeted service (opencti: , connector: and mandiant:)
5. launch the connector: python3 connector.py

## Expected Output

I expected the connector to contact with Mandiant https://api.intelligence.mandiant.com, retrieve the corresponding data and update opencti objects accordingly.

## Actual Output

Instead, the following error message appears: "An URL must be set"

## Additional information

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PATH_HIDDEN/opencti/connectors/external-import/mandiant/src/mandiant/base.py", line 17, in __init__
    self.helper = OpenCTIConnectorHelper({})
  File "PATH_HIDDEN/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 661, in __init__
    self.api = OpenCTIApiClient(
  File "PATH_HIDDEN/python3.10/site-packages/pycti/api/opencti_api_client.py", line 133, in __init__
    raise ValueError("An URL must be set")
ValueError: An URL must be set
Terminated
</pre>
Hint: an empty dictionary "{}" is passed as a parameter to "OpenCTIConnectorHelper({})" instead of the config.yml file

**Comment by Aspidoquelona** [comment]
Sorry. Wrong place. I'll put it in the "connectors" project.

**Comment by Aspidoquelona** [comment]
Sorry. Wrong place. I'll put it in the "connectors" project.
