### ISSUE TITLE
OpenCTI (manual installation) cannot start. "stack":"TypeError: e.matchAll is not a function

### ISSUE THREAD

**Issue by EtherealCod3** [OpenCTI-Platform/opencti#399]
## Description

Installing OpenCTI manually. All dependecies are installed and running. Starting the server fails with an error related to grakn.js (Grakn server version 1.5.9 as per documentation.). Unable to start the environment. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 16.4
2. OpenCTI version: OpenCTI rolling release 20191231 (also tried 2.1.1)
3. OpenCTI client: n.a. (wannabe frontend)
4. Other environment details: OpenCTI manual installation. Tried Grakn 1.6.1 and Grakn 1.5.9

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install all dependecies as requested
2. Extract OpenCTI rolling release
3. Run the node server

## Expected Output

The server should be running

## Actual Output

info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
info: [PRE-CHECK] > Python3 is available
info: [INIT] > Grakn schema loaded
info: [INIT] > Elasticsearch indexes loaded
info: [MIGRATION] > Starting migration process
error: [GRAKN] executeRead error > e.matchAll is not a function {"stack":"TypeError: e.matchAll is not a function\n    at Q (/home/dev/opencti/build/index.js:1:6591)\n    at $ (/home/dev/opencti/build/index.js:1:12170)\n    at $ (/home/dev/opencti/build/index.js:1:4443)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}
error: [OPENCTI] GraphQL initialization fail > TypeError: e.matchAll is not a function
    at Q (/home/dev/opencti/build/index.js:1:6591)
    at $ (/home/dev/opencti/build/index.js:1:12170)
    at $ (/home/dev/opencti/build/index.js:1:4443)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by EtherealCod3** [comment]
NodeJS > 12 was required. Closing.
