### ISSUE TITLE
Improve connector stack to limit concurrent injection on same elements

### ISSUE THREAD

**Issue by campeador** [OpenCTI-Platform/opencti#539]
Hi I'm getting an error. It seems is related with Grakn but I can't go deeper.

This is the console log:

```
error: [GRAKN] executeWrite error > A database error has occured! {"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-03-02T15:21:38.959Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [a8c2e3b7-a37b-5a52-a4fd-1432763c5033] of type [internal_id_key]. "},"internalData":{},"stack":"DatabaseError: A database error has occured!\n    at G (/opencti/build/index.js:1:5033)"}
error: [OPENCTI] Technical error > A database error has occured! {"locations":[{"line":4,"column":29}],"path":["reportEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-03-02T15:21:38.959Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [a8c2e3b7-a37b-5a52-a4fd-1432763c5033] of type [internal_id_key]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at G (/opencti/build/index.js:1:5033)","stacktrace":["DatabaseError: A database error has occured!","    at G (/opencti/build/index.js:1:5033)"]}}}
```

When I stop the "yarn serv" and the grakn server and start it again, the error dissapear. Could you help me?

Thanks in advanced.

-----

Ticket edition by @richard-julien 
We need to test another way to inject stix2 to limit the concurrency errors. Idea:
1. Check the consistency of a stix2.
2. Split the stix2 in unit element, ordered by consistency
3. Send everything to rabbit
4. Worker handle the job in order
5. Because of multiple workers you can have a moment where a worker start to work on relation before the end of all entities creation. So this injection will fail for element not found. In this case we need to handle this kind of error to prevent the acknowledge of the message and retry it 10 times (each time after 1sec of waiting). After all the retry we can consider that the message will never be injected correctly and discard it.
Expected benefits: Improve speed / limit concurrency problems
Error to come: Some rejection sometimes for element not found before actually founding them

**Comment by powerade661** [comment]
I am getting this error too. I wonder if wiping the database and starting over will help. I think the error is saying that it has duplicate items in the database. Not really sure how to do that, but I wonder if that will fix it.

**Comment by SamuelHassine** [comment]
@campeador @powerade661: this error is not "critical", it just means that the relation you are trying to add already exists (in your case @campeador the entity you are adding to the report is already in there). You can ignore this error but we want to fix it, please could you describe more precisely the scenario you played to get these errors?

**Comment by campeador** [comment]
Hi again, thank you for your help. Actually i don't know what event produce this error. I can tell you what I have.
I have the normal version installed [No docker](all the systems with the correct version like the docs say).
 I have these connectors:
- AM!TT
- CVE
- ImportFilePdfObservable
- ImportFileStix2
- MISP
- Mitre ATT&CK
I have 10 workers. 153k Entities, 145k observables and 2.11k of reports.
When I Installled the app I enable de inferences (but i disabled when it starts to have this errors). It seems when this error start the app no process more messages. I now have 164k Queued messages, 0/s messages processed and 8.97k Total processed messages.

The app logs is like i put in the last message. The grakn logs are like this:

2020-03-03 10:55:21,714 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.kb.server.exception.InvalidKBException: A structural validation error has occurred. Please correct the [`1`] errors found. 
There is more than one thing of type [stix_relation_embedded] that owns the key [5a3c6aa7-359a-53f0-9b52-d173b9ecfc3d] of type [internal_id_key]. 

	at grakn.core.kb.server.exception.InvalidKBException.create(InvalidKBException.java:53)
	at grakn.core.kb.server.exception.InvalidKBException.validationErrors(InvalidKBException.java:65)
	at grakn.core.server.session.TransactionImpl.validateGraph(TransactionImpl.java:1166)
	at grakn.core.server.session.TransactionImpl.persistInternal(TransactionImpl.java:232)
	at grakn.core.server.session.TransactionImpl.commitInternal(TransactionImpl.java:223)
	at grakn.core.server.session.TransactionImpl.commit(TransactionImpl.java:1141)
	at grakn.core.server.rpc.SessionService$TransactionListener.commit(SessionService.java:331)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:226)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-03-03 10:55:22,101 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.kb.server.exception.InvalidKBException: A structural validation error has occurred. Please correct the [`1`] errors found. 
There is more than one thing of type [stix_relation_embedded] that owns the key [6df3a2ca-d112-5ce3-8deb-3b1073cb1e7e] of type [internal_id_key]. 

	at grakn.core.kb.server.exception.InvalidKBException.create(InvalidKBException.java:53)
	at grakn.core.kb.server.exception.InvalidKBException.validationErrors(InvalidKBException.java:65)
	at grakn.core.server.session.TransactionImpl.validateGraph(TransactionImpl.java:1166)
	at grakn.core.server.session.TransactionImpl.persistInternal(TransactionImpl.java:232)
	at grakn.core.server.session.TransactionImpl.commitInternal(TransactionImpl.java:223)
	at grakn.core.server.session.TransactionImpl.commit(TransactionImpl.java:1141)
	at grakn.core.server.rpc.SessionService$TransactionListener.commit(SessionService.java:331)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:226)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

If i can provide you more information about anything, just tell me.

Thank you,

**Comment by ghost** [comment]
Hi, this issue happens to me too with Docker swarm stack.

With all connectors available working right now. 

My logs of opencti platform:

```
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | There is more than one thing of type [Stix-Domain] that owns the key [identity--4ab28b13-7be4-4f13-959a-039190ab03d8] of type [stix_id_key].
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | . Please check server logs for the stack trace. {"code":3,"metadata":{"_internal_repr":{},"flags":0},"details":"InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found. \nThere is more than one thing of type [Stix-Domain] that owns the key [identity--4ab28b13-7be4-4f13-959a-039190ab03d8] of type [stix_id_key]. \n. Please check server logs for the stack trace.","stack":"Error: 3 INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found. \nThere is more than one thing of type [Stix-Domain] that owns the key [identity--4ab28b13-7be4-4f13-959a-039190ab03d8] of type [stix_id_key]. \n. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/opt/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/opt/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /opt/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [GRAKN] executeWrite error > A database error has occured! {"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-03-04T15:46:06.324Z","data":{"type":"technical","details":"There is more than one thing of type [Stix-Domain] that owns the key [identity--4ab28b13-7be4-4f13-959a-039190ab03d8] of type [stix_id_key]. "},"internalData":{},"stack":"DatabaseError: A database error
has occured!\n    at G (/opt/opencti/build/index.js:1:5033)"}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [OPENCTI] Technical error > A database error has occured! {"locations":[{"line":3,"column":21}],"path":["identityAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-03-04T15:46:06.324Z","data":{"type":"technical","details":"There is more than one thing of type [Stix-Domain] that owns the key [identity--4ab28b13-7be4-4f13-959a-039190ab03d8] of type [stix_id_key]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at G (/opt/opencti/build/index.js:1:5033)","stacktrace":["DatabaseError: A database error has occured!","    at G (/opt/opencti/build/index.js:1:5033)"]}}}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [OPENCTI] Technical error > [GRAKN] You cant create a relation with the same source and target (bb3786bf-376a-4ce9-97ba-819dfa8bed0d - corresponds) {"locations":[{"line":3,"column":21}],"path":["stixObservableRelationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: [GRAKN] You cant create a relation with the same source and target (bb3786bf-376a-4ce9-97ba-819dfa8bed0d - corresponds)","    at xe (/opt/opencti/build/index.js:1:27151)","    at Me (/opt/opencti/build/index.js:1:31062)","    at k (/opt/opencti/build/index.js:1:99511)","    at Ce.stixObservableRelationAdd (/opt/opencti/build/index.js:1:814512)","
at Ce.authenticationControl (/opt/opencti/build/index.js:1:842906)","    at t.resolve (/opt/opencti/build/index.js:1:843444)","    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","    at /opt/opencti/node_modules/graphql/execution/execute.js:244:18","
   at /opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10","    at Array.reduce (<anonymous>)","    at promiseReduce (/opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)","    at executeFieldsSerially (/opt/opencti/node_modules/graphql/execution/execute.js:241:37)","    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:55)","    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)"]}}}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [OPENCTI] Technical error > Cannot read property 'internal_id_key' of undefined {"locations":[{"line":3,"column":29}],"path":["stixRelationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'internal_id_key' of undefined","    at /opt/opencti/build/index.js:1:21083","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async Promise.all (index 0)","    at async fe (/opt/opencti/build/index.js:1:20621)","    at async xe (/opt/opencti/build/index.js:1:29628)","    at async Me (/opt/opencti/build/index.js:1:31056)","    at async o (/opt/opencti/build/index.js:1:77731)"]}}}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [OPENCTI] Technical error > Cannot read property 'internal_id_key' of undefined {"locations":[{"line":3,"column":29}],"path":["stixRelationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'internal_id_key' of undefined","    at /opt/opencti/build/index.js:1:21083","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async Promise.all (index 0)","    at async fe (/opt/opencti/build/index.js:1:20621)","    at async xe (/opt/opencti/build/index.js:1:29628)","    at async Me (/opt/opencti/build/index.js:1:31056)","    at async o (/opt/opencti/build/index.js:1:77731)"]}}}
opencti_opencti.1.fykt3yc1ljzw@ip-10-0-2-7    | error: [OPENCTI] Technical error > [GRAKN] You cant create a relation with the same source and target (704291be-ad02-44f6-ad8e-4aa0538a7c43 - corresponds) {"locations":[{"line":3,"column":21}],"path":["stixObservableRelationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: [GRAKN] You cant create a relation with the same source and target (704291be-ad02-44f6-ad8e-4aa0538a7c43 - corresponds)","    at xe (/opt/opencti/build/index.js:1:27151)","    at Me (/opt/opencti/build/index.js:1:31062)","    at k (/opt/opencti/build/index.js:1:99511)","    at Ce.stixObservableRelationAdd (/opt/opencti/build/index.js:1:814512)","
at Ce.authenticationControl (/opt/opencti/build/index.js:1:842906)","    at t.resolve (/opt/opencti/build/index.js:1:843444)","    at field.resolve (/opt/opencti/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/opt/opencti/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/opt/opencti/node_modules/graphql/execution/execute.js:434:16)","    at /opt/opencti/node_modules/graphql/execution/execute.js:244:18","
   at /opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:23:10","    at Array.reduce (<anonymous>)","    at promiseReduce (/opt/opencti/node_modules/graphql/jsutils/promiseReduce.js:20:17)","    at executeFieldsSerially (/opt/opencti/node_modules/graphql/execution/execute.js:241:37)","    at executeOperation (/opt/opencti/node_modules/graphql/execution/execute.js:219:55)","    at executeImpl (/opt/opencti/node_modules/graphql/execution/execute.js:104:14)"]}}}
```

**Comment by richard-julien** [comment]
For me this error is a concurrency problem when using multiple workers to inject data. 

Currently we split the stix2 to generate autonomous chunks, the result of that is to have same entity/relation in multiple chunks. When 2 or more chunks are processed in parallel you can have some concurrency issue. The good news is that you dont have any side effect of that, it "just" do more operation that really needed and log some errors :)

We have another concurrent strategy we want to test to limit this kind of situation and also improve the performance but its not plan yet.

**Comment by SamuelHassine** [comment]
Confirmed @richard-julien.

@campeador, @powerade661: If you want to avoid the errors in the logs, the only solution for the moment is to launch only one worker.

**Comment by richard-julien** [comment]
@campeador , @powerade661 and @EmWhyAitch ticket renamed and edited. Dont hesitate if you have any remarks or idea on this.

**Comment by toshiro92** [comment]
I have this error too on my side on Grakn:

```
2020-04-07 08:03:53,431 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
grakn.core.kb.server.exception.InvalidKBException: A structural validation error has occurred. Please correct the [`1`] errors found. 
There is more than one thing of type [stix_relation_embedded] that owns the key [d29b3dae-ae59-5bdf-9aaa-ceebdd5ee873] of type [internal_id_key]. 
	at grakn.core.kb.server.exception.InvalidKBException.create(InvalidKBException.java:53)
	at grakn.core.kb.server.exception.InvalidKBException.validationErrors(InvalidKBException.java:65)
	at grakn.core.server.session.TransactionImpl.validateGraph(TransactionImpl.java:1166)
	at grakn.core.server.session.TransactionImpl.persistInternal(TransactionImpl.java:232)
	at grakn.core.server.session.TransactionImpl.commitInternal(TransactionImpl.java:223)
	at grakn.core.server.session.TransactionImpl.commit(TransactionImpl.java:1141)
	at grakn.core.server.rpc.SessionService$TransactionListener.commit(SessionService.java:331)
	at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:226)
	at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I currently have the following connectors enabled:

- AlienVault
- AMITT
- Covid19
- MISP
- MITRE
- ImportFilePdfObservables
- ImportFileStix
- ExportFileCSV
- ExportFileSTIX

**Comment by SamuelHassine** [comment]
@toshiro92, @campeador, @powerade661 and @EmWhyAitch: we will improve the connectors stack to avoid this error during the ingestion of elements. If you want to avoid this error, you have to **launch only one worker**. So you will never have these errors again.

As we said before, these errors are not critical and the ingestion process remains consistent. It happens when the same entity is present in 2 bundles processed by 2 workers at the same time and both workers try for instance to add the same marking definition to this element (`stix_relation_embedded`) because the initial check return false in the 2 processing. To prevent duplicate marking definitions, the database will return an error.

**Comment by powerade661** [comment]
I understand this now and am not concerned by it.

**Comment by SamuelHassine** [comment]
And to precise exactly how we implement this limitation, `internal_id_key` of `stix_relation_embedded` are UUIDv5 (predictable) based on the entity ID and for instance the marking definition ID. So trying to add the same marking definition to an entity that is already linked to it will result to the same UUIDv5 and throw an error because the `internal_id_key` already exists.
