### ISSUE TITLE
3.0.3 Bug Issue Install 0 RSA Primitives 

### ISSUE THREAD

**Issue by itzdan** [OpenCTI-Platform/opencti#575]
## Description

info: 🚀 OpenCTI started in production mode with embedded file
/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/rsa_primes.js:8
const ZERO = BigInt(0)
             ^

ReferenceError: BigInt is not defined
    at Object.<anonymous> (/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/rsa_primes.js:8:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/key_utils.js:9:23)
    at Module._compile (module.js:652:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04 LTS
2. OpenCTI version: 3.0.3
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. install as per manual installation

## Expected Output

services started

## Actual Output

info: 🚀 OpenCTI started in production mode with embedded file
/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/rsa_primes.js:8
const ZERO = BigInt(0)
             ^

ReferenceError: BigInt is not defined
    at Object.<anonymous> (/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/rsa_primes.js:8:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/opencti/opencti/node_modules/jose/lib/help/key_utils.js:9:23)
    at Module._compile (module.js:652:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by SamuelHassine** [comment]
@itzdan it seems that you are not using the right version of NodeJS. Please ensure that you have installed NodeJS >= 12, as written in the [installation documentation](https://opencti-platform.github.io/docs/installation/manual) or in the [developement documentation](https://opencti-platform.github.io/docs/development/installation).

You can view your NodeJS version by using the command `node -v`.

Kind regards,
Samuel

**Comment by richard-julien** [comment]
Close for inactivity. Please reopen if the comment of Samuel doesnt fix your issue.
