### ISSUE TITLE
Grakn and OpenCTI issue from OpenCTI log on docker

### ISSUE THREAD

**Issue by cyamal1b4** [OpenCTI-Platform/opencti#589]
## Description

A couple things. I came in today and OpenCTI was down, checked the logs and that Grakn was the issue again, it seems that Grakn is unstable (which is perhaps why its rec'd to have it run separately). Is there sufficient documentation on their page (Grakn) to help get that set up? Or should I be deploying this with the Docker Stack option? It won't allow that right now either. 

I was able to get the platform back up but have noticed no new data having been ingested at least from what I can see at the UI. My msg que is continuing to grow and I received several pulses with at least several new observe's/IOCs that should have come in through AVault but I've received nothing, is it backed up or is the below log output part of the problem? 

## Environment

1. OS Ubuntu 18.04 LTS
2. OpenCTI version: 3
3. OpenCTI client: frontend
4. Other environment details: Running everything under docker with docker-compose.yml not docker stack deploy (wouldnt work)

## Reproducible Steps

Steps to create the smallest reproducible scenario:
sudo docker container logs docker_opencti_1

## Expected Output

I'm not sure if this is normal or not.

## Actual Output

2020-04-01T20:08:13.134119998Z error: [GRAKN] executeWrite error > A database error has occured! {"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-01T20:08:13.133Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [7b004ca9-cf60-5956-8cbf-7b1459dca641] of type [internal_id_key]. "},"internalData":{},"stack":"DatabaseError: A database error has occured!\n    at W (/opt/opencti/build/index.js:1:5071)"}

2020-04-01T20:08:13.134436704Z error: [OPENCTI] Technical error > A database error has occured! {"locations":[{"line":4,"column":29}],"path":["reportEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-01T20:08:13.133Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [7b004ca9-cf60-5956-8cbf-7b1459dca641] of type [internal_id_key]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at W (/opt/opencti/build/index.js:1:5071)","stacktrace":["DatabaseError: A database error has occured!","    at W (/opt/opencti/build/index.js:1:5071)"]}}}

**Comment by SamuelHassine** [comment]
@Patriot1b4: these errors are not "critical" and just indicated that the connector/worker are trying to add a relation that already exists in the platform. We were aware of these problems in certain use cases and fixed in the latest version (3.1.0). Please upgrade your OpenCTI instance and tell us if you still have this kind of error messages.

**Comment by Patriot1b4** [comment]
@SamuelHassine Thankyou that makes sense. I do have another query. My Message Que (under connectors dashboard) is growing steadily and my messages being processed is most of the time at zero with processed messages lagging far behind the que. Is this normal or an error in my deployment? I gave the platform fairly decent resources but I haven't learned enough of the overall parts of the dependencies to optimize. I ask only because I have been getting my AlienVault pulses but not getting them through the data lake where they are available at the UI. Thanks for any help!

**Comment by cyamal1b4** [comment]
@SamuelHassine Thankyou that makes sense.
