### ISSUE TITLE
Failure to update from 3.0.3 to 3.1.0 - GraphQL initialization fail

### ISSUE THREAD

**Issue by fr33tux** [OpenCTI-Platform/opencti#594]
Hello,

## Description

Upgrading from 3.0.3 to 3.1.0 fails at `[OPENCTI] GraphQL initialization fail`.

## Environment

1. OS: Ubuntu 18.04
2. OpenCTI version: 3.1.0
3. OpenCTI client: frontend
4. Other environment details:

OpenCTI is installed following the manual installation steps described in the documentation.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install OpenCTI 3.0.3
2. Update to OpenCTI 3.1.0
3. OpenCTI passes successfully the 4 `PRE-CHECK` steps but fails at the `GRAKN` one.

## Expected Output

```
$ yarn serv

info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
info: [PRE-CHECK] > Python3 is available
info: [INIT] > Grakn schema loaded
info: [INIT] > Elasticsearch indexes loaded
info: [MIGRATION] > Starting migration process
info: [MIGRATION] > Read 25 migrations from the database
info: [MIGRATION] > Migration process completed, platform is up to date
info: [INIT] > Platform default initialized
info: [ADMIN_SETUP] admin user initialized
info: OPENCTI Ready on port 4000
```

## Actual Output

```
$ yarn serv

info: 🚀 OpenCTI started in production mode with embedded file
info: [PRE-CHECK] > Grakn is alive
info: [PRE-CHECK] > Elasticsearch is alive
info: [PRE-CHECK] > Minio is alive
info: [PRE-CHECK] > Python3 is available
error: [GRAKN] Write error > 2 UNKNOWN: null. Please check server logs for the stack trace.","stack":"Error: 2 UNKNOWN: null. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/var/www/opencti/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/var/www/opencti/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}
error: [OPENCTI] GraphQL initialization fail > Error: 2 UNKNOWN: null. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/var/www/opencti/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/var/www/opencti/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /var/www/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1127:18","level":"error"}
```
 
## Additional information

Reverting to 3.0.3 everything works fine, but the update to 3.1.0 always throw out those errors.

**Comment by SamuelHassine** [comment]
Hello,

Your error is occured at the Grakn schema initialization. Could you please check your Grakn Server logs and copy/paste what you have?

Thanks.

Kind regards,
Samuel

**Comment by fr33tux** [comment]
Thanks for the quick answer.

```
2020-04-03 11:34:37,119 [main] INFO  grakn.core.server.Grakn - Grakn started in 918.0 ms
```

`grakn server status` returns that it's up and running.
Then by running a `yarn serv`  (which fails with the error above) in OpenCTI directory, the following error gets added in the Grakn log:

```
2020-04-03 11:34:54,003 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: null
        at grakn.core.concept.impl.TypeImpl.lambda$checkNonOverlapOfImplicitRelations$16(TypeImpl.java:429)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
        at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
        at grakn.core.concept.impl.TypeImpl.checkNonOverlapOfImplicitRelations(TypeImpl.java:429)
        at grakn.core.concept.impl.TypeImpl.checkLinkAttributeIsLegal(TypeImpl.java:411)
        at grakn.core.concept.impl.TypeImpl.key(TypeImpl.java:404)
        at grakn.core.graql.executor.property.HasAttributeTypeExecutor$DefineHasAttributeType.execute(HasAttributeTypeExecutor.java:177)
        at grakn.core.graql.executor.WriteExecutorImpl.write(WriteExecutorImpl.java:240)
        at grakn.core.graql.executor.WriteExecutorImpl.write(WriteExecutorImpl.java:229)
        at grakn.core.graql.executor.QueryExecutorImpl.define(QueryExecutorImpl.java:364)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:383)
        at grakn.core.server.session.TransactionImpl.stream(TransactionImpl.java:632)
        at grakn.core.server.rpc.SessionService$TransactionListener.query(SessionService.java:345)
        at grakn.core.server.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:229)
        at grakn.core.server.rpc.SessionService$TransactionListener.lambda$onNext$1(SessionService.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by fr33tux** [comment]
Note than the same error is present in Grakn logs when I launch OpenCTI 3.0.3, but it doesn't stop from doing the startup steps successfully.

**Comment by powerade661** [comment]
Same here. Are you getting a TypeError DNS?

**Comment by richard-julien** [comment]
In this version we don't change anything on the schema but it looks like I add some defensive code on this initialization error that lead to a start fail if the schema cannot be initialized correctly. So you can start in 3.0.3 but not in 3.1.0. 

It seems your Grakn database have a problem that prevent openCTI to update the schema. Unfortunately this is a grakn bug ... Do you think its possible for you to log a bug in Grakn github? Im not sure about rollbacking the defensive code because we will be able to start in 3.1.0 because we dont do any schema update but the next one will have some new attributes and so we will never be able to upgrade if your database is not fixed by grakn.

**Comment by fr33tux** [comment]
Ok, so bad news.. I will create an issue on the Grakn repository.

Is there a way to export the data I currently have to be able to import it in a fresh 3.1.0? (Like a large Stix2 export?)

**Comment by SamuelHassine** [comment]
Hello @fr33tux, @powerade661,

We managed to find the problem with Grakn Labs. @fr33tux thanks for the help!

We will implement a migration in the next version but if you have this problem, you can fix it by executing this Python script. Just change `YOUR.GRAKN.HOST:PORT` by your own Grakn Server hostname and port.

Script is here: https://gist.github.com/SamuelHassine/62e740443d75acc88c993bc9e9b6fba3.

```
$ pip3 install grakn-client===1.6.1
$ python3 ./clear_unused_roles.py
```

Errors are gone!

**Comment by fr33tux** [comment]
Thanks for the assistance :)
