### ISSUE TITLE
Grakn crashes, caused by "No node was available to execute the query"

### ISSUE THREAD

**Issue by toshiro92** [OpenCTI-Platform/opencti#595]
## Description

Grakn systematically crashes after several hours due to `No node was available to execute the query`. I'm not sure if this is a Grakn issue, or a query which provoked the crash.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 3.0.3, except for COVID-19 CTC connecteur (3.1.0)
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run OpenCTI infrastructure based on 3.0.3 with connectors, except the COVID-19 CTC, which is in 3.1.0 version, and works fine when Grakn is up.

## Expected Output

Grakn is up and running

## Actual Output

```
2020-04-03 07:12:23,257 [grpc-request-handler-35] ERROR grakn.core.server.rpc.SessionService - An error has occurred
grakn.core.graph.core.JanusGraphException: Could not call index
	at grakn.core.graph.graphdb.util.SubQueryIterator.<init>(SubQueryIterator.java:65)
	at grakn.core.graph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1246)
	at grakn.core.graph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1145)
	at grakn.core.graph.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:202)
	at grakn.core.graph.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:65)
	at grakn.core.graph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:56)
	at grakn.core.graph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:46)
	at grakn.core.graph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:73)
	at com.google.common.collect.Iterables$4.iterator(Iterables.java:578)
	at grakn.core.graph.graphdb.tinkerpop.optimize.JanusGraphStep.executeGraphCentryQuery(JanusGraphStep.java:160)
	at grakn.core.graph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$1(JanusGraphStep.java:96)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at grakn.core.graph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$2(JanusGraphStep.java:96)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:155)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at grakn.core.concept.structure.ElementFactory.getVertexWithProperty(ElementFactory.java:65)
	at grakn.core.concept.manager.ConceptManagerImpl.getConcept(ConceptManagerImpl.java:421)
	at grakn.core.concept.manager.ConceptManagerImpl.getSchemaConcept(ConceptManagerImpl.java:488)
	at grakn.core.concept.manager.ConceptManagerImpl.getMetaConcept(ConceptManagerImpl.java:508)
	at grakn.core.server.session.TransactionImpl.getMetaConcept(TransactionImpl.java:896)
	at grakn.core.server.session.SessionImpl.keyspaceHasBeenInitialised(SessionImpl.java:152)
	at grakn.core.server.session.SessionImpl.<init>(SessionImpl.java:84)
	at grakn.core.server.session.SessionFactory.session(SessionFactory.java:116)
	at grakn.core.server.rpc.ServerOpenRequest.open(ServerOpenRequest.java:41)
	at grakn.core.server.rpc.SessionService.open(SessionService.java:111)
	at grakn.protocol.session.SessionServiceGrpc$MethodHandlers.invoke(SessionServiceGrpc.java:339)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at com.datastax.oss.driver.api.core.NoNodeAvailableException.copy(NoNodeAvailableException.java:40)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:208)
	at com.datastax.oss.driver.api.core.CqlSession.execute(CqlSession.java:51)
	at grakn.core.graph.diskstorage.cql.CQLStoreManager.executeOnSession(CQLStoreManager.java:282)
	at grakn.core.graph.diskstorage.cql.CQLKeyColumnValueStore.getSlice(CQLKeyColumnValueStore.java:299)
	at grakn.core.graph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:73)
	at grakn.core.graph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:332)
	at grakn.core.graph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:329)
	at grakn.core.graph.diskstorage.util.BackendOperation.execute(BackendOperation.java:53)
	at grakn.core.graph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:400)
	at grakn.core.graph.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:329)
	at grakn.core.graph.graphdb.query.graph.MultiKeySliceQuery.execute(MultiKeySliceQuery.java:52)
	at grakn.core.graph.graphdb.database.IndexSerializer.query(IndexSerializer.java:529)
	at grakn.core.graph.graphdb.util.SubQueryIterator.<init>(SubQueryIterator.java:63)
	... 42 common frames omitted
```
 
## Additional information

It seems no issue was raised on Github's repository about that crash.

**Comment by SamuelHassine** [comment]
Hello,

This is a Grakn related issue, we advise you to open it on the Grakn Github repository or reach them through their Discord channels.

Kind regards,
Samuel

**Comment by richard-julien** [comment]
Thanks for reporting this bug in grakn project.
