### ISSUE TITLE
Docker installation won't work

### ISSUE THREAD

**Issue by MRDJR97** [OpenCTI-Platform/opencti#604]
## Description

Whenever I run 'docker-compose --compatibility up' I get the following error:

> worker_2                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
> connector-import-file-stix_1             | Token configuration must be the same as APP__ADMIN__TOKEN
> connector-mitre_1                        | Token configuration must be the same as APP__ADMIN__TOKEN
> connector-export-file-csv_1              | Token configuration must be the same as APP__ADMIN__TOKEN
> connector-opencti_1                      | Token configuration must be the same as APP__ADMIN__TOKEN
> worker_3                                 | Traceback (most recent call last):

## Environment

Ubuntu 18.04 server
latest version of opencti

My .env file has all valid UUIDs. Is there something I should have changed in the docker-compose file?

Below is a copy of my .env file:

`OPENCTI_ADMIN_EMAIL=admin@opencti.io
OPENCTI_ADMIN_PASSWORD=ChangeMe
OPENCTI_ADMIN_TOKEN=b82d0501-4892-4370-a786-b85cba9ca70e
MINIO_ACCESS_KEY=ChangeMeAccess
MINIO_SECRET_KEY=ChangeMeKey
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
CONNECTOR_EXPORT_FILE_STIX_ID=917fb07a-5847-488e-a78c-04cd8eb66cc0
CONNECTOR_EXPORT_FILE_CSV_ID=95c244e9-821d-455a-aa5b-f4b7d0405fb4
CONNECTOR_IMPORT_FILE_STIX_ID=692e7449-b4b0-490d-90f7-569a7a622ab0
CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID=d756be82-3e20-41fb-a9d5-131c82322700
CONNECTOR_OPENCTI_ID=936faf82-8ae0-45d5-a399-33746b7f7d42
CONNECTOR_MITRE_ID=67a7de77-9a5d-449e-ad09-782862570c49`

**Comment by richard-julien** [comment]
Hi @MRDJR97, can you upload here your docker compose and your env file? Do you start the docker compose command inside the directory with the 2 files? Thanks

**Comment by SamuelHassine** [comment]
Closing this issue due to inactivity. Please re-open if you still have problems.

**Comment by parmarth-1208** [comment]
I'm trying to manually install opencti to my linux os and I'm getting the below error, how can i resolve this please help me with it:
$ python3 worker.py 
Traceback (most recent call last):
  File "/home/parmarth/project/opencti/worker/worker.py", line 466, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/parmarth/project/opencti/worker/worker.py", line 385, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
  File "/home/parmarth/project/opencti/src/python/venv/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 126, in __init__
    raise ValueError("A TOKEN must be set")
ValueError: A TOKEN must be set
