### ISSUE TITLE
Update : Grakn is down | OpenCTI is not reachable

### ISSUE THREAD

**Issue by rishdang** [OpenCTI-Platform/opencti#618]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

Encountering error on vanilla OpenCTI installation (docker) when using docker-up. I have tested this on 3 different VPS, now I am feeling like I am missing something really basic. 
Post setting variables in .env as per documentation, and running OpenCTI via docker-compose, the system never comes up and continuously throws the below error.

Update : looks like grakn container is not coming up

Update 2 : I think it resembles to #603 

Update 3 : #322 fixed it. Closing this.

"OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration"

## Environment

1. OS (where OpenCTI server runs): Tested on Ubuntu 18.04.4 LTS, Debian 10 buster
2. OpenCTI version: 3.1.0
3. OpenCTI client: Default frontend
4. Other environment details:

VPS details
```
H/W path      Device           Class      Description
=====================================================
                               system     Standard PC (i440FX + PIIX, 1996)
/0                             bus        Motherboard
/0/0                           memory     96KiB BIOS
/0/400                         processor  Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
/0/1000                        memory     16GiB System Memory
/0/1000/0                      memory     16GiB DIMM RAM
/0/100                         bridge     440FX - 82441FX PMC [Natoma]
/0/100/1                       bridge     82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1.1                     storage    82371SB PIIX3 IDE [Natoma/Triton II]
/0/100/1.2                     bus        82371SB PIIX3 USB [Natoma/Triton II]
/0/100/1.2/1  usb1             bus        UHCI Host Controller
/0/100/1.3                     bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/2                       display    SVGA II Adapter
/0/100/3                       generic    Virtio memory balloon
/0/100/3/0                     generic    Virtual I/O device
/0/100/5                       storage    Virtio SCSI
/0/100/5/0                     generic    Virtual I/O device
/0/100/12                      network    Virtio network device
/0/100/12/0   eth0             network    Ethernet interface
/0/100/1e                      bridge     QEMU PCI-PCI bridge
/0/100/1f                      bridge     QEMU PCI-PCI bridge
/0/1          scsi2            storage
/0/1/0.0.0    /dev/sda         disk       429GB QEMU HARDDISK
/0/1/0.0.0/1  /dev/sda1        volume     953MiB EXT4 volume
/0/1/0.0.0/2  /dev/sda2        volume     399GiB EXT4 volume
/1            br-7d7e02ae9521  network    Ethernet interface
/2            docker0          network    Ethernet interface

```

`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Follow documentation exactly, set UUIDs via uuidgen, change keys in .env, add connectors in docker-compose.yml
2. docker-compose up
3.  docker continuously throws this error
"OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."

## Expected Output

OpenCTI to work correctly

## Actual Output

`Starting docker_connector-export-file-stix_1 ...
Starting docker_connector-import-file-stix_1 ...
Starting docker_connector-export-file-stix_1
Starting docker_minio_1 ...
Starting docker_connector-import-file-stix_1
Starting docker_minio_1
Starting docker_grakn_1 ...
Starting docker_grakn_1
Starting docker_rabbitmq_1 ...
Starting docker_connector-mitre_1 ...
Starting docker_rabbitmq_1
Starting docker_connector-import-file-pdf-observables_1 ...
Starting docker_connector-mitre_1
Starting docker_redis_1 ...
Starting docker_connector-import-file-pdf-observables_1
Starting docker_connector-opencti_1 ...
Starting docker_connector-export-file-csv_1 ...
Starting docker_redis_1
Starting docker_elasticsearch_1 ...
Starting docker_connector-export-file-csv_1
Starting docker_connector-opencti_1
Starting docker_rabbitmq_1 ... done
Starting docker_opencti_1 ...
Starting docker_opencti_1 ... done
Starting docker_worker_1 ...
Starting docker_worker_1 ... done
Attaching to docker_connector-import-file-stix_1, docker_connector-export-file-stix_1, docker_connector-mitre_1, docker_redis_1, docker_connector-export-file-csv_1, docker_elasticsearch_1, docker_grakn_1, docker_minio_1, docker_connector-opencti_1, docker_connector-import-file-pdf-observables_1, docker_rabbitmq_1, docker_opencti_1, docker_worker_1
connector-import-file-stix_1             | INFO:root:Listing Threat-Actors with filters null.
connector-import-file-stix_1             | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
connector-mitre_1                        | INFO:root:Listing Threat-Actors with filters null.
connector-export-file-stix_1             | INFO:root:Listing Threat-Actors with filters null.
connector-export-file-stix_1             | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
redis_1                                  | 1:C 11 Apr 2020 09:10:33.691 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                                  | 1:C 11 Apr 2020 09:10:33.691 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                                  | 1:C 11 Apr 2020 09:10:33.691 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 * Running mode=standalone, port=6379.
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 # Server initialized
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 * DB loaded from disk: 0.000 seconds
redis_1                                  | 1:M 11 Apr 2020 09:10:33.694 * Ready to accept connections
connector-export-file-csv_1              | INFO:root:Listing Threat-Actors with filters null.
elasticsearch_1                          | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,183Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda2)]], net usable_space [364.5gb], net total_space [391.8gb], types [ext4]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,197Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "heap size [989.8mb], compressed ordinary object pointers [true]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,475Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "node name [1aac174af0d1], node ID [kyZDhpI7RM2BRBnoebW5yA], cluster name [docker-cluster]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,476Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "version[7.6.2], pid[1], build[default/docker/ef48eb35cf30adf4db14086e8aabd07ef6fb113f/2020-03-26T06:34:37.794943Z], OS[Linux/4.15.0-96-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/13.0.2/13.0.2+8]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,476Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:39,477Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=COMPAT, -Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-16106058156741446518, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
grakn_1                                  | ====================================================================================================
grakn_1                                  |       ________  _____     _______  __    __  __    __      _______  _______  _____     _______
grakn_1                                  |      |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
grakn_1                                  |      |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
grakn_1                                  |      |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
grakn_1                                  |      |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
grakn_1                                  |      |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
grakn_1                                  |      |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|
grakn_1                                  |
grakn_1                                  |                                          THE KNOWLEDGE GRAPH
minio_1                                  |
minio_1                                  |  You are running an older version of MinIO released 1 month ago
minio_1                                  |  Update: docker pull minio/minio:RELEASE.2020-04-10T03-34-42Z
minio_1                                  |
minio_1                                  |
minio_1                                  | Endpoint:  http://172.18.0.10:9000  http://127.0.0.1:9000
minio_1                                  |
minio_1                                  | Browser Access:
minio_1                                  |    http://172.18.0.10:9000  http://127.0.0.1:9000
minio_1                                  |
minio_1                                  | Object API (Amazon S3 compatible):
minio_1                                  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_1                                  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_1                                  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_1                                  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_1                                  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
grakn_1                                  | ====================================================================================================
connector-opencti_1                      | INFO:root:Listing Threat-Actors with filters null.
grakn_1                                  |                                                                                       Version: 1.6.2
opencti_1                                | yarn run v1.19.1
opencti_1                                | $ node --max_old_space_size=8192 build/index.js
connector-import-file-pdf-observables_1  | INFO:root:Listing Threat-Actors with filters null.
connector-mitre_1                        | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_1                                 | INFO:root:Listing Threat-Actors with filters null.
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 174, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 120, in __init__
worker_1                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 111, in __init__
worker_1                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_1                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,801Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [aggs-matrix-stats]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,803Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [analysis-common]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,806Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [flattened]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,806Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [frozen-indices]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,807Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [ingest-common]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,807Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [ingest-geoip]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,807Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [ingest-user-agent]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,808Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [lang-expression]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,808Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [lang-mustache]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,808Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [lang-painless]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,809Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [mapper-extras]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,817Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [parent-join]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,818Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [percolator]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,824Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [rank-eval]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,824Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [reindex]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,830Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [repository-url]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,830Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [search-business-rules]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,831Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [spatial]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,831Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [transform]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,831Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [transport-netty4]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,832Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [vectors]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,832Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-analytics]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,832Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-ccr]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,832Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-core]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,833Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-deprecation]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,833Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-enrich]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,833Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-graph]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,834Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-ilm]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,834Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-logstash]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,834Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-ml]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,834Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-monitoring]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,835Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-rollup]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,835Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-security]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,836Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-sql]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,836Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-voting-only-node]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,837Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "loaded module [x-pack-watcher]" }
elasticsearch_1                          | {"type": "server", "timestamp": "2020-04-11T09:10:44,838Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "1aac174af0d1", "message": "no plugins loaded" }
connector-export-file-csv_1              | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti_1                                | {"code":14,"metadata":{"_internal_repr":{},"flags":0},"details":"failed to connect to all addresses","level":"error","message":"[GRAKN] Seems down > 14 UNAVAILABLE: failed to connect to all addresses","stack":"Error: 14 UNAVAILABLE: failed to connect to all addresses\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/opt/opencti/node_modules/grpc/src/client_interceptors.js:847:24)"}
opencti_1                                | {"message":"[OPENCTI] GraphQL initialization fail > Error: Grakn seems down\n    at /opt/opencti/build/index.js:1:4871\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/opencti/build/index.js:1:128547\n    at async n.b (/opt/opencti/build/index.js:1:128531)\n    at async /opt/opencti/build/index.js:1:858301","level":"error"}
o`
 
## Additional information

have tried it on 3 different VPS instances on 2 different operating systems, 2 with Debian 10 buster, one with Ubuntu 18.04 LTS. Have not touched docker-compose.yml, all changes done in .env only.

**Comment by rishdang** [comment]
#322 fixed it, closing it.
