### ISSUE TITLE
OpenCTI docker - Unable to run Ubuntu 18.04 OpenCTI 3.1.0 

### ISSUE THREAD

**Issue by jbabbin** [OpenCTI-Platform/opencti#625]
Issue: 
openCTI API appears to be unavailable tried several of the tricks mentioned in bugs here with no luck. (#416, #322, etc)  

Pre-Execution:  
- Set the  vm.max_map_count=1048575
- created a new .env file (also tried copying over .env.example) 
Execution: docker-compose --compatibility up 

Any help would be appreciated 
Thanks! 

Tried and all failed: 
1) changing the ports (8080 to 4000) thought that 'testing' the documentation seems a bit unclear if you are using the docker-compose to start OpenCTI 
2) creating unique UUID's in the .env file 
3) simply copying over .env.example to .env  
Though I might change the '.env.example' to a non-hidden file 'example.env' for reference in the future might help to get up and running faster 

I can get to RabbitMQ, Minio, and Grakn all appear to be running.  

Environment: 
Clean Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)
(tried with RHEL 7 and Ubunut 16.04 as well) 
OpenCTI : 3.1.0 
```
root@opencti:/opt/docker# docker images
REPOSITORY                                      TAG                            IMAGE ID            CREATED             SIZE
opencti/connector-opencti                       3.1.0                          9ef248d7c9a3        4 days ago          126MB
opencti/connector-mitre                         3.1.0                          46133899c7bb        4 days ago          126MB
opencti/connector-export-file-csv               3.1.0                          a74011257af9        4 days ago          126MB
opencti/connector-export-file-stix              3.1.0                          2e696182b3d6        4 days ago          126MB
opencti/connector-import-file-pdf-observables   3.1.0                          6560ee0f3f11        4 days ago          218MB
opencti/connector-import-file-stix              3.1.0                          a02e82083e44        4 days ago          126MB
rabbitmq                                        3.7-management                 fac238dafa8e        4 days ago          182MB
opencti/worker                                  3.1.0                          bf33dff175d8        13 days ago         130MB
opencti/platform                                3.1.0                          4688422706ac        13 days ago         698MB
redis                                           5.0.8                          4cdbec704e47        2 weeks ago         98.2MB
docker.elastic.co/elasticsearch/elasticsearch   7.6.2                          f29a1ee41030        2 weeks ago         791MB
minio/minio                                     RELEASE.2020-02-27T00-23-05Z   5836a22e6092        6 weeks ago         54MB
graknlabs/grakn                                 1.6.2                          f84f5a9e0600        50 years ago        648MB

```
Docker Versions 
root@opencti:/opt/docker# docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

root@opencti:/opt/docker# docker version
 Version:           19.03.6

Docker Logs 
```
docker logs docker_opencti_1
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"code":14,"metadata":{"_internal_repr":{},"flags":0},"details":"failed to connect to all addresses","level":"error","message":"[GRAKN] Seems down > 14 UNAVAILABLE: failed to connect to all addresses","stack":"Error: 14 UNAVAILABLE: failed to connect to all addresses\n    at Object.exports.createStatusError (/opt/opencti/node_modules/grpc/src/common.js:91:15)\n    at Object.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:1209:28)\n    at InterceptingListener._callNext (/opt/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at callback (/opt/opencti/node_modules/grpc/src/client_interceptors.js:847:24)"}
{"message":"[OPENCTI] GraphQL initialization fail > Error: Grakn seems down\n    at /opt/opencti/build/index.js:1:4871\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/opencti/build/index.js:1:128547\n    at async n.b (/opt/opencti/build/index.js:1:128531)\n    at async /opt/opencti/build/index.js:1:858301","level":"error"}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.

```
Execution Error that repeats 
```
worker_2                                 | Traceback (most recent call last):
worker_2                                 |   File "worker.py", line 174, in <module>
worker_2                                 |     worker = Worker()
worker_2                                 |   File "worker.py", line 120, in __init__
worker_2                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_2                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 111, in __init__
worker_2                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_2                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 174, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 120, in __init__
worker_1                                 |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 111, in __init__
worker_1                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_1                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```

**Comment by jbabbin** [comment]
Looking deeper it looks like Grakn starts then fails with a Storage issue 
```
 docker logs docker_grakn_1
====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                      Version: 1.6.2
Unable to start Storage.
Starting Storage....FAILED!

```

**Comment by richard-julien** [comment]
Hi @jbabbin, sometimes grakn fail to start in a container environment and it seems related to the amount of io/process of other containers starting a the same time. So we recommend to start grakn alone in another stack to mitigate this problem.  An issue is open on grakn https://github.com/graknlabs/grakn/issues/5570 for that.

**Comment by jbabbin** [comment]
Thanks I did try that 
docker run --name graknlabs/grakn:latest 
it still fails after a while 
I also just upping the VM's memory above 4GB to see if that helps since the JVM can use a lot of memory. 

Next am going to try from scratch building all of the components.

**Comment by cyamal1b4** [comment]
Grakn is a hunger monster, try that Ram upgrade and try to manually start as @richard-julien stated. Docker restart [CONTAINER] may work as well.
