### ISSUE TITLE
OpenCTI - Front end crashes - Out of memory

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/opencti#638]
## Description

OpenCTI index.js crashes after a couple of days of parsing messages in queue 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: 3.1.0
3. OpenCTI client: Frontend
4. Other environment details:
OpenCTI Setup : 
- OpenCTI + RabbitMQ + Minio : 16vCPU , 64GB RAM [ On a single server]
- ElasticSearch Cluster : 2 Servers ( 4vCPU , 16GB RAM) [ separate cluster]
- Grakn Server - 16vCPU , 128GB RAM [ Separate server]

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Frontend is manually stood up using ```node build/index.js```
2. Main connectors running : CrowdStrike and MISP. CS connect has report fetch date of April 20th, 2020
3. Queue Size : 269.25K Messages , 3 Workers

Observations : I have noticed that while there are 3 python3 workers in the backend , the front end only recognizes 2. However all 3 are pulling from RabbitMQ . 

## Actual Output

Last Output from openCTI index.js process : 
```
{"message":"[OPENCTI] Technical error > A database error has occured!","locations":[{"line":4,"column":25}],"path":["reportEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-21T18:36:14.309Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at /opt/opencti/opencti/build/index.js:1:4389\n    at async R (/opt/opencti/opencti/build/index.js:1:4554)\n    at async Te (/opt/opencti/opencti/build/index.js:1:26068)\n    at async je (/opt/opencti/opencti/build/index.js:1:28669)\n    at async h (/opt/opencti/opencti/build/index.js:1:57699)","stacktrace":["DatabaseError: A database error has occured!","    at /opt/opencti/opencti/build/index.js:1:4389","    at async R (/opt/opencti/opencti/build/index.js:1:4554)","    at async Te (/opt/opencti/opencti/build/index.js:1:26068)","    at async je (/opt/opencti/opencti/build/index.js:1:28669)","    at async h (/opt/opencti/opencti/build/index.js:1:57699)"]}},"level":"error"}
{"code":3,"metadata":{"_internal_repr":{},"flags":0},"details":"InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found. \nThere is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. \n. Please check server logs for the stack trace.","level":"error","message":"[GRAKN] CommitWriteTx error > 3 INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found. \nThere is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. \n. Please check server logs for the stack trace.","stack":"Error: 3 INVALID_ARGUMENT: InvalidKBException-A structural validation error has occurred. Please correct the [`1`] errors found. \nThere is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. \n. Please check server logs for the stack trace.\n    at Object.exports.createStatusError (/opt/opencti/opencti/node_modules/grpc/src/common.js:91:15)\n    at ClientDuplexStream._emitStatusIfDone (/opt/opencti/opencti/node_modules/grpc/src/client.js:233:26)\n    at ClientDuplexStream._receiveStatus (/opt/opencti/opencti/node_modules/grpc/src/client.js:211:8)\n    at Object.onReceiveStatus (/opt/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1311:15)\n    at InterceptingListener._callNext (/opt/opencti/opencti/node_modules/grpc/src/client_interceptors.js:568:42)\n    at InterceptingListener.onReceiveStatus (/opt/opencti/opencti/node_modules/grpc/src/client_interceptors.js:618:8)\n    at /opt/opencti/opencti/node_modules/grpc/src/client_interceptors.js:1127:18"}
{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-21T18:36:14.615Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. "},"internalData":{},"level":"error","message":"[GRAKN] executeWrite error > A database error has occured!","stack":"DatabaseError: A database error has occured!\n    at /opt/opencti/opencti/build/index.js:1:4389\n    at async R (/opt/opencti/opencti/build/index.js:1:4554)\n    at async Te (/opt/opencti/opencti/build/index.js:1:26068)\n    at async je (/opt/opencti/opencti/build/index.js:1:28669)\n    at async h (/opt/opencti/opencti/build/index.js:1:57699)"}
{"message":"[OPENCTI] Technical error > A database error has occured!","locations":[{"line":4,"column":25}],"path":["reportEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-21T18:36:14.615Z","data":{"type":"technical","details":"There is more than one thing of type [stix_relation_embedded] that owns the key [e3caf292-1dab-521e-b791-503e0fdbc100] of type [internal_id_key]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at /opt/opencti/opencti/build/index.js:1:4389\n    at async R (/opt/opencti/opencti/build/index.js:1:4554)\n    at async Te (/opt/opencti/opencti/build/index.js:1:26068)\n    at async je (/opt/opencti/opencti/build/index.js:1:28669)\n    at async h (/opt/opencti/opencti/build/index.js:1:57699)","stacktrace":["DatabaseError: A database error has occured!","    at /opt/opencti/opencti/build/index.js:1:4389","    at async R (/opt/opencti/opencti/build/index.js:1:4554)","    at async Te (/opt/opencti/opencti/build/index.js:1:26068)","    at async je (/opt/opencti/opencti/build/index.js:1:28669)","    at async h (/opt/opencti/opencti/build/index.js:1:57699)"]}},"level":"error"}

<--- Last few GCs --->

[16404:0x2cde7a0] 194095778 ms: Mark-sweep 1969.5 (2076.7) -> 1956.6 (2080.2) MB, 3356.2 / 0.2 ms  (average mu = 0.105, current mu = 0.032) allocation failure scavenge might not succeed
[16404:0x2cde7a0] 194099786 ms: Mark-sweep 1971.7 (2080.2) -> 1956.7 (2077.0) MB, 3895.6 / 0.4 ms  (average mu = 0.065, current mu = 0.028) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13c03d9]
    1: StubFrame [pc: 0x13fd410]
Security context: 0x31901bf008d1 <JSObject>
    2: replace [0x31901bf163c1](this=0x233e59c24f39 <String[#1]: ->,0x3ccccc89c4f1 <JSRegExp <String[#21]: [-\/\\^$*+?.()|[\]{}]>>,0x233e59c27901 <String[#3]: \$&>)
    3: unescapeFormat(aka unescapeFormat) [0x17ffb4d0f571] [/opt/opencti/opencti/node_modules/moment/moment.js:~677] [pc=0x304ae9bdac05](this=0x161f5b1c04b1 <undefined...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa02f90 node::Abort() [node]
 2: 0xa033b5 node::OnFatalError(char const*, char const*) [node]
 3: 0xb76ffe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb77379 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd23ad5  [node]
 6: 0xd24166 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd309e5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd31895 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3434c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd021fc v8::internal::Factory::NewRawOneByteString(int, v8::internal::AllocationType) [node]
11: 0x10bb17d v8::internal::ReplacementStringBuilder::ToString() [node]
12: 0x106a30b  [node]
13: 0x106b4ca v8::internal::Runtime_RegExpReplaceRT(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x13c03d9  [node]
```

Grakn Output : 
```
2020-04-21 18:36:46,272 [grpc-request-handler-28] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:864)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-04-21 18:36:46,273 [grpc-request-handler-31] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener:
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:524)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:864)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Wo
```
 
## Additional information
I've not encountered this error before. Usually it is Grakn that runs out of memory, however this time based on the logs, it seems the opencti index.js ran out of memory. Any suggestions on what I can do for better optimization?

**Comment by cvdsouza** [comment]
HI, 
So this issue occurred again today 
```
{"message":"[OPENCTI] Technical error > A database error has occured!","locations":[{"line":3,"column":21}],"path":["indicatorAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"name":"DatabaseError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2020-04-24T04:20:48.896Z","data":{"type":"technical","details":"There is more than one thing of type [Indicator] that owns the key [[ipv4-addr:value = '92.253.23.7']] of type [indicator_pattern]. "},"internalData":{},"_stack":"DatabaseError: A database error has occured!\n    at /opt/opencti/opencti/build/index.js:1:4389\n    at async R (/opt/opencti/opencti/build/index.js:1:4554)\n    at async Fe (/opt/opencti/opencti/build/index.js:1:30467)\n    at async f (/opt/opencti/opencti/build/index.js:1:113789)","stacktrace":["DatabaseError: A database error has occured!","    at /opt/opencti/opencti/build/index.js:1:4389","    at async R (/opt/opencti/opencti/build/index.js:1:4554)","    at async Fe (/opt/opencti/opencti/build/index.js:1:30467)","    at async f (/opt/opencti/opencti/build/index.js:1:113789)"]}},"level":"error"}

<--- Last few GCs --->

[3613:0x33e77a0] 217941886 ms: Mark-sweep 2024.3 (2050.3) -> 2004.8 (2049.8) MB, 3149.7 / 1.2 ms  (average mu = 0.179, current mu = 0.201) allocation failure scavenge might not succeed
[3613:0x33e77a0] 217942547 ms: Scavenge 2005.7 (2049.8) -> 2005.3 (2050.1) MB, 658.0 / 0.0 ms  (average mu = 0.179, current mu = 0.201) allocation failure
[3613:0x33e77a0] 217942572 ms: Scavenge 2005.8 (2050.1) -> 2005.5 (2050.6) MB, 19.6 / 0.0 ms  (average mu = 0.179, current mu = 0.201) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13c03d9]
Security context: 0x27cb4ef808d1 <JSObject>
    1: push [0x27cb4ef975b9](this=0x284a75449eb9 <JSArray[0]>,10)
    2: /* anonymous */ [0x1dfeb90e2e89] [/opt/opencti/opencti/node_modules/google-protobuf/google-protobuf.js:455] [bytecode=0x277e7ff74221 offset=157](this=0x284a75449dc1 <JSObject>,10)
    3: /* anonymous */ [0x1dfeb90e3789] [/opt/opencti/opencti/node_modules/google-protobuf/google-protobuf.js:47...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200424.074355.3613.0.001.json
Node.js report completed
 1: 0xa02f90 node::Abort() [node]
 2: 0xa033b5 node::OnFatalError(char const*, char const*) [node]
 3: 0xb76ffe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb77379 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd23ad5  [node]
 6: 0xd24166 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd309e5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd31895 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3434c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xcfaf1b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x103d85e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13c03d9  [node]
```

I'm not sure why this is occurring. @SamuelHassine , or @richard-julien would you guys have any suggestion for this ? The servers have enough cpu and ram and I don't see more that 30% of memory being utilized on them when the app crashes. 

Please let me know if I can provide further information on this, as I"m having issues pin-pointing what is causing the memory exhaustion issue.

**Comment by TechBurn0ut** [comment]
I am seeing this as well.  I only have seen it when we enabled the CS connector.

**Comment by richard-julien** [comment]
Hi @cvdsouza , the v8 engine have a default limitation in term of memory. Maybe we have a memory leak ... I will start soon the ticket around performance and it seems i will also take a look into the nodejs process memory allocation. As a workaround you can try to add more memory to the nodejs process through the --max-old-space-size option.

Example for 8go of memory allocation
`node --max-old-space-size=8192 build/index.js`

**Comment by cvdsouza** [comment]
hi @richard-julien , so actually I have. I used 8gb . I'll try increasing. Basically for me every 2 or 3 days, I noticed the UI slowing down and I have to do a restart. I Will increase the memory now.

**Comment by TechBurn0ut** [comment]
Any guidance on how to fix this?  no problem doing it, I just want to make sure its in the right place.

**Comment by cvdsouza** [comment]
@richard-julien  , anychance of taking a look at this for the next release ? or maybe it will be fixed. I just got this again for 3.2.2.

**Comment by richard-julien** [comment]
Hi @cvdsouza , unfortunately no time to handle this for now. We take a long time to bootstrap the performance test. Now i need to work on multiple workers usage and then profiling the memory of the API. Any idea of how to reproduce the oom? Any specific behavior in the UI, any specific connector running (like @TechBurn0ut )? thanks

**Comment by cvdsouza** [comment]
Hi @richard-julien , completely understood and looking forward to the performance testing :) 
This is pretty much reproducible in my environment because it is a recurring issue every week) : 
- We have 18 connectors in total : 
  - AM!TT
  - AlienVault
  - Common Vulnerabilities & Exposures
  - Crowdstrike
  - Cryptolaemus
  - CyberThreatCoalition
  - ExportFileCSV
  - ExportFileStix
  - ImportFilePDFObservables
  - MITRE ATT&CK
  - Malpedia
  - Malware bazaar (Custom Enrichment) 
  - OpenCTI
  - URLHaus (Custom data connector)
  - Valhalla
  - Virustotal
  - iSight FireEye (Custom data connector) 
  - Import File Text Observables

We have tested with and without our custom connectors, but issue persists. 
Our users haven't performed any specific actions that would cause this. Or atleast to my knowledge, I just notice a gradual response lag increase over the course of a couple of a week 

Our current workaround is to do a restart when we see a lag in the UI that crosses 80 seconds in loading the front page. We have noticed this lag via the API as well. 
For production , I'm currently thinking of setting up a monitor to check response lag and do a restart of OpenCTI index.js only, if it crosses a threshold.

**Comment by SamuelHassine** [comment]
We will try to reproduce this by reaching 1M entities on the demo.

**Comment by SamuelHassine** [comment]
We will try to reproduce this by reaching 1M entities on the demo.

@richard-julien if we have any memory leak in the application, do you think the migration to NodeJS 13 could help?

**Comment by cvdsouza** [comment]
Hey @richard-julien , @SamuelHassine 
After upgrading to latest version yesterday morning, our instance UI was really laggy and it crashed in the night. This was the error output: 

```
{"type":"WRITE_ERROR","operation_query":"mutation StixObservableAdd($input:StixObservableAddInput){stixObservableAdd(input:$input){id stix_id_key entity_type parent_types}}","inner_relation_creation":1,"operation":"StixObservableAdd","time":43460,"variables":{"input":{"type":"File-MD5","observable_value":"814da68cbe6ab9aca35ba8105135b14d","description":null,"internal_id_key":null,"stix_id_key":null,"createdByRef":"363cc9e9-d7ec-4134-beb1-43dd361bd47c","markingDefinitions":null,"tags":null,"createIndicator":false}},"size":260,"error":{"stacktrace":["Error: channel closed","at ConfirmChannel.<anonymous> (/opt/opencti/opencti/node_modules/amqplib/lib/channel.js:39:18)","at ConfirmChannel.emit (events.js:315:20)","at ConfirmChannel.C.toClosed (/opt/opencti/opencti/node_modules/amqplib/lib/channel.js:175:8)","at Connection.C._closeChannels (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:394:18)","at Connection.C.toClosed (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:401:8)","at Object.accept (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:96:18)","at Connection.mainAccept (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:64:3events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Heartbeat timeout
    at Heart.<anonymous> (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:427:19)
    at Heart.emit (events.js:315:20)
    at Heart.runHeartbeat (/opt/opencti/opencti/node_modules/amqplib/lib/heartbeat.js:88:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on ChannelModel instance at:
    at Connection.emit (events.js:315:20)
    at Heart.<anonymous> (/opt/opencti/opencti/node_modules/amqplib/lib/connection.js:428:12)
    at Heart.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at processTimers (internal/timers.js:492:7)
node[6453]: ../src/node.cc:637:void node::ResetStdio(): Assertion `(0) == (err)' failed.
 1: 0xa08900 node::Abort() [node]
 2: 0xa0897e  [node]
 3: 0x9d5487 node::ResetStdio() [node]
 4: 0x7fa754232041  [/lib/x86_64-linux-gnu/libc.so.6]
 5: 0x7fa75423213a  [/lib/x86_64-linux-gnu/libc.so.6]
 6: 0x9b1831  [node]
 7: 0xa0a5a7 node::errors::TriggerUncaughtException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>, bool) [node]
 8: 0xa0abf0 node::errors::PerIsolateMessageListener(v8::Local<v8::Message>, v8::Local<v8::Value>) [node]
 9: 0xce4bc6 v8::internal::MessageHandler::ReportMessageNoExceptions(v8::internal::Isolate*, v8::internal::MessageLocation const*, v8::internal::Handle<v8::internal::Object>, v8::Local<v8::Value>) [node]
10: 0xce4d92 v8::internal::MessageHandler::ReportMessage(v8::internal::Isolate*, v8::internal::MessageLocation const*, v8::internal::Handle<v8::internal::JSMessageObject>) [node]
11: 0xcd681f v8::internal::Isolate::ReportPendingMessagesImpl(bool) [node]
12: 0xcc0f08  [node]
13: 0xcc1218 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [node]
14: 0xb90c3b v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [node]
15: 0x9a0508 node::Environment::RunTimers(uv_timer_s*) [node]
16: 0x132c0c5  [node]
17: 0x133054a uv_run [node]
18: 0xa4baf5 node::NodeMainInstance::Run() [node]
19: 0x9d9a08 node::Start(int, char**) [node]
20: 0x7fa754210b97 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
21: 0x977215  [node]
```

Usually we would see this error every 3 - 4 days, now it seemed to be occurring sooner.

**Comment by richard-julien** [comment]
Hi. We currently working on the v4 on so i check the memory profile on a 10 minutes run injecting the mitre with 10 workers. 

![image](https://user-images.githubusercontent.com/285555/91331772-82f9ae80-e7cb-11ea-9a6e-b9d62d7f1dcb.png)

As you can see it looks good :)

In the same time if you still have some memory issue with the v3, can you please send me the report generated when the nodejs process crash? Thanks

**Comment by cvdsouza** [comment]
@richard-julien for sure. I usually see a crash every 4 -5 days. How do I generate the report ?

**Comment by richard-julien** [comment]
The report is auto generated when the process crash.

**Comment by SamuelHassine** [comment]
I close this issue for the moment. Please re-open it if the problem persists on the V4.
