### ISSUE TITLE
Migration failed due to incorrect function call

### ISSUE THREAD

**Issue by kirintwn** [OpenCTI-Platform/opencti#700]
## Description

Migration failed after upgrade from 3.0.2 to 3.2.2.

## Environment

1. OS (where OpenCTI server runs): Docker (K8S)
2. OpenCTI version: OpenCTI 3.2.2
3. OpenCTI client: frontend
4. Other environment details: None

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Migrate from existing platform
2. Trigger applyMigration()
3. Start to execute files in `src/migrations`

## Expected Output

```
[MIGRATION] > Migration process completed, platform is up to date
[INIT] > Platform default initialized
[ADMIN_SETUP] admin user initialized
OPENCTI Ready on port 8080
```

## Actual Output
```
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"message":"[PRE-CHECK] > Grakn is alive","level":"info"}
{"message":"[PRE-CHECK] > ElasticSearch is alive","level":"info"}
{"message":"[PRE-CHECK] > Minio is alive","level":"info"}
{"message":"[PRE-CHECK] > RabbitMQ is alive","level":"info"}
{"message":"[PRE-CHECK] > Redis is alive","level":"info"}
{"message":"[PRE-CHECK] > Python3 is available","level":"info"}
{"message":"[INIT] > Existing platform detected, migration...","level":"info"}
{"message":"[INIT] > Grakn schema loaded","level":"info"}
{"message":"[INIT] > Elasticsearch indexes loaded","level":"info"}
{"message":"[ADMIN_SETUP] admin user initialized","level":"info"}
{"message":"[MIGRATION] > Read 1 migrations from the database","level":"info"}
{"message":"[MIGRATION] > 2 migrations will be executed","level":"info"}
{"message":"[MIGRATION] report-published-utc > 200 reports to modify","level":"info"}
{"error":{"name":"ResponseError","meta":{"body":{"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] query does not support [key]","line":1,"col":112}],"type":"parsing_exception","reason":"[term] query does not support [key]","line":1,"col":112},"status":400},"statusCode":400,"headers":{"content-type":"application/json; charset=UTF-8","content-length":"227"},"warnings":null,"meta":{"context":null,"request":{"params":{"method":"POST","path":"/stix_domain_entities_v2%2Cstix_relations%2Cstix_observables%2Cwork_jobs_index/_search","body":"{\"query\":{\"bool\":{\"must\":[{\"term\":{\"internal_id_key.keyword\":\"Report\"}},{\"term\":{\"parent_types.keyword\":{\"key\":\"published\",\"value\":[\"2018-11-05T10:30:40.000Z\"]}}}]}}}","querystring":"_source_excludes=rel_*","headers":{"User-Agent":"elasticsearch-js/7.6.1 (linux 4.14.154-128.181.amzn2.x86_64-x64; Node.js v12.13.1)","Content-Type":"application/json","Content-Length":"166"},"timeout":30000},"options":{"warnings":null},"id":19},"name":"elasticsearch-js","connection":{"url":"http://es-es-http:9200/","id":"http://es-es-http:9200/","headers":{},"deadCount":0,"resurrectTimeout":0,"_openRequests":2,"status":"alive","roles":{"master":true,"data":true,"ingest":true,"ml":false}},"attempts":0,"aborted":false}}},"level":"error","message":"[GRAKN] executeWrite error"}
{"message":"[GRAKN] Error during migration","level":"error"}
{"message":"[MIGRATION] > Migration process completed, platform is up to date","level":"info"}
{"error":"ResponseError: parsing_exception\n    at IncomingMessage.<anonymous> (/opt/opencti/node_modules/@elastic/elasticsearch/lib/Transport.js:296:25)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","level":"error","message":"[OPENCTI] GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The elasticsearch has the following log:
```
"level": "DEBUG"
"message": "All shards failed for phase: [query]"
"stacktrace": ["org.elasticsearch.index.query.QueryShardException: No mapping found for [published] in order to sort on" "at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:387) ~[elasticsearch-7.4.0.jar:7.4.0]"
```

The execution of `report-published-utc` migration seems to be failed.
 
## Additional information

I noticed that we have changed `updateAttribute()` parameters since we introduced technical logs:
https://github.com/OpenCTI-Platform/opencti/blob/ea8d97f7d7b34fc4c6f2bfd27e73a6e4f0e3dffa/opencti-platform/opencti-graphql/src/database/grakn.js#L1714

But evey function call of  `updateAttribute()` in the `src/migrations` directory is still using the old parameters which lacking the `user` parameter.

https://github.com/OpenCTI-Platform/opencti/blob/88a343865b8778e9a51848b32270435e76dcdad1/opencti-platform/opencti-graphql/src/migrations/1583491791006-report-published-utc.js#L22-L31

I am not sure if it is the root cause, but I do believe these incorrect function call is a bug. thanks.

**Comment by kirintwn** [comment]
Update:
I can confirmed that if I add the parameter `user` like this one
https://github.com/OpenCTI-Platform/opencti/blob/ea8d97f7d7b34fc4c6f2bfd27e73a6e4f0e3dffa/opencti-platform/opencti-graphql/tests/utils/testQuery.js#L13-L19

and apply it to every files under `src/migrations` that calls `updateAttribute()`, then the migration is executed without any error, so it should be the root cause.

The bug is critical and is fairly simple to fix, if we want to use `admin user` specified in `tests/utils/testQuery`, I can create a PR to do it.

**Comment by kirintwn** [comment]
Just found another related bug:
The tag migration script named `1585468407235-tags.js` is lacking an option `noLog: true` when calling `updateAttribute()`.

https://github.com/OpenCTI-Platform/opencti/blob/cac1996590650c8fc1b73b1e3ae9eac671299040/opencti-platform/opencti-graphql/src/migrations/1585468407235-tags.js#L13-L22
 
which will cause error: `Error: [STIX Entity type is unknown, cannot convert to STIX`, and the migration process will failed.

The output will be like:
```
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
{"message":"[PRE-CHECK > Grakn is alive","level":"info"}
{"message":"[PRE-CHECK > ElasticSearch is alive","level":"info"}
{"message":"[PRE-CHECK > Minio is alive","level":"info"}
{"message":"[PRE-CHECK > RabbitMQ is alive","level":"info"}
{"message":"[PRE-CHECK > Redis is alive","level":"info"}
{"message":"[PRE-CHECK > Python3 is available","level":"info"}
{"message":"[INIT > Existing platform detected, migration...","level":"info"}
{"message":"[INIT > Grakn schema loaded","level":"info"}
{"message":"[INIT > Elasticsearch indexes loaded","level":"info"}
{"message":"[ADMIN_SETUP admin user initialized","level":"info"}
{"message":"[MIGRATION > Read 2 migrations from the database","level":"info"}
{"message":"[MIGRATION > 1 migrations will be executed","level":"info"}
{"message":"{\n  \"id\": \"489265ce-cd8f-437e-93a6-26443092b9c4\",\n  \"entity_type\": \"tag\",\n  \"color\": \"#489044\"\n}","level":"error"}
{"error":{},"level":"error","message":"[GRAKN executeWrite error"}
{"message":"[GRAKN Error during migration","level":"error"}
{"message":"[MIGRATION > Migration process completed, platform is up to date","level":"info"}
{"error":"Error: [STIX Entity type is unknown, cannot convert to STIX\n    at convertDataToStix (/opt/opencti/build/webpack:/src/database/stix.js:593:13)\n    at sendLog (/opt/opencti/build/webpack:/src/database/rabbitmq.js:218:32)\n    at Le (/opt/opencti/build/webpack:/src/database/grakn.js:1788:11)\n    at process.result (internal/process/task_queues.js:93:5)\n    at L (/opt/opencti/build/webpack:/src/database/grakn.js:206:11)","level":"error","message":"[OPENCTI GraphQL initialization fail"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stream closed
```
