### ISSUE TITLE
Grakn 1.6.2 not started in RHEL 7

### ISSUE THREAD

**Issue by razzeshsingh** [OpenCTI-Platform/opencti#759]
[root@shdqsectip01 Python-3.8.2]# grakn server start
Starting Storage....FAILED!
Unable to start Storage.
Process exited with code '1': ''
An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
Process exited with code '1': ''
[root@shdqsectip01 Python-3.8.2]#

[root@shdqsectip01 Python-3.8.2]# grakn server status
Storage: NOT RUNNING
Grakn Core Server: NOT RUNNING
[root@shdqsectip01 Python-3.8.2]#

Logs :

[root@shdqsectip01 Python-3.8.2]# tail -f /var/log/grakn/grakn.log
2020-06-15 08:32:52,652 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '1': ''
        at grakn.core.daemon.executor.Storage.start(Storage.java:223)
        at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
        at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
        at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
        at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
^C
[root@shdqsectip01 Python-3.8.2]# tail -f /var/log/grakn/cassandra.log
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at org.apache.cassandra.utils.NativeLibraryLinux.<clinit>(NativeLibraryLinux.java:53)
        at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:93)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:196)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602)
        at grakn.core.server.GraknStorage.main(GraknStorage.java:39)
WARN  [main] 2020-06-15 08:32:50,874 StartupChecks.java:136 - jemalloc shared library could not be preloaded to speed up memory allocations
WARN  [main] 2020-06-15 08:32:50,875 StartupChecks.java:169 - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
ERROR [main] 2020-06-15 08:32:50,876 CassandraDaemon.java:708 - The native library could not be initialized properly.
^C
[root@shdqsectip01 Python-3.8.2]#

**Comment by cvdsouza** [comment]
Can you please share more details on your Grakn deployment ? 
Server Configurations ? 
Any changes made to grakn.properties ?

**Comment by razzeshsingh** [comment]
Hi @cvdsouza thanks for quick response,

I just installed below things, here is the below details of services :

[root@shdqsectip01 ~]# node -v
v12.18.0
[root@shdqsectip01 ~]# npm -v
6.14.4
[root@shdqsectip01 ~]# python3 -V
Python 3.8.2
[root@shdqsectip01 ~]# pip3 -V
pip 19.2.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
[root@shdqsectip01 ~]# java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
[root@shdqsectip01 ~]#


Also I didn't make any changes in grakn.properties

**Comment by cvdsouza** [comment]
could you paste the Grakn.log output as well ? 
Also how much Ram and CPU on this server ?

**Comment by razzeshsingh** [comment]
Hardware details: 
   Vcpu : 8 core
  RAM : 8 GB
 HDD : 500 GB

[root@shdqsectip01 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
[root@shdqsectip01 ~]#

[root@shdqsectip01 ~]# tail -f /var/log/grakn/grakn.log
        at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
        at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
        at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
2020-06-15 08:39:42,733 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '1': ''
        at grakn.core.daemon.executor.Storage.start(Storage.java:223)
        at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
        at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
        at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
        at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
^C
[root@shdqsectip01 ~]# tail -f /var/log/grakn/cassandra.log
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at org.apache.cassandra.utils.NativeLibraryLinux.<clinit>(NativeLibraryLinux.java:53)
        at org.apache.cassandra.utils.NativeLibrary.<clinit>(NativeLibrary.java:93)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:196)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602)
        at grakn.core.server.GraknStorage.main(GraknStorage.java:39)
WARN  [main] 2020-06-15 08:39:41,054 StartupChecks.java:136 - jemalloc shared library could not be preloaded to speed up memory allocations
WARN  [main] 2020-06-15 08:39:41,054 StartupChecks.java:169 - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
ERROR [main] 2020-06-15 08:39:41,055 CassandraDaemon.java:708 - The native library could not be initialized properly.
^C
[root@shdqsectip01 ~]#

**Comment by razzeshsingh** [comment]
[root@shdqsectip01 ~]# cat /var/log/grakn/grakn.log
2020-06-15 08:32:52,652 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '1': ''
        at grakn.core.daemon.executor.Storage.start(Storage.java:223)
        at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
        at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
        at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
        at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
2020-06-15 08:39:42,733 [main] ERROR grakn.core.daemon.GraknDaemon - An error has occurred during boot-up. Please run 'grakn server status' or check the logs located under the 'logs' directory.
grakn.core.daemon.exception.GraknDaemonException: Process exited with code '1': ''
        at grakn.core.daemon.executor.Storage.start(Storage.java:223)
        at grakn.core.daemon.executor.Storage.startIfNotRunning(Storage.java:147)
        at grakn.core.daemon.GraknDaemon.serverStart(GraknDaemon.java:188)
        at grakn.core.daemon.GraknDaemon.run(GraknDaemon.java:140)
        at grakn.core.daemon.GraknDaemon.main(GraknDaemon.java:72)
[root@shdqsectip01 ~]#

**Comment by cvdsouza** [comment]
I would recommend , reboot the server that then try starting Grakn up again. I have seen this issue before, and for me after a reboot it worked fine. Also please make sure you're running latest version of Grakn.

**Comment by SamuelHassine** [comment]
I'm closing this due to inactivity.
