### ISSUE TITLE
INTERNAL_SERVER_ERROR - "Int cannot represent non-integer value:"

### ISSUE THREAD

**Issue by fr33tux** [OpenCTI-Platform/opencti#84]
Hello,

## Description

Pages throws a "ERROR" and are not displayed correctly at the second request.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04.2, x64.
2. OpenCTI version: [opencti-20190628.tar.gz](https://github.com/OpenCTI-Platform/opencti/releases/tag/1.0.0)
3. OpenCTI client: frontend
4. Other environment details: Fresh installation.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Install OpenCTI following the manual documentation
2. Click on any page, the first request usually works, but the second throws the "ERROR" message on the top left corner.

## Expected Output

Pages correctly displayed

## Actual Output

- "ERROR" is displayed on all pages:

![Screenshot from 2019-06-28 23-42-53](https://user-images.githubusercontent.com/5955898/60373284-ee958f80-99ff-11e9-8bb0-30747ac3e464.png)

The browser console throws this error:

```
Error: ""
    i construct.js:30
    a wrapNativeSuper.js:22
    n environment.js:39
    render environment.js:108
    render ReactRelayQueryRenderer.js:216
    React 11
    handleDataChange ReactRelayQueryRenderer.js:142
    error ReactRelayQueryFetcher.js:194
    error ReactRelayQueryFetcher.js:193
    error RelayObservable.js:553
    error RelayObservable.js:553
    r RelayObservable.js:178
    error RelayObservable.js:553
    error RelayObservable.js:553
    error RelayReplaySubject.js:105
    error RelayReplaySubject.js:104
    error fetchQueryInternal.js:126
    error RelayObservable.js:553
    error RelayObservable.js:553
    _error RelayModernQueryExecutor.js:190
    error RelayModernQueryExecutor.js:85
    error RelayObservable.js:553
react-dom.production.min.js:4408
    React 7
    unstable_runWithPriority scheduler.production.min.js:274
    React 7
    handleDataChange ReactRelayQueryRenderer.js:142
    error ReactRelayQueryFetcher.js:194
    error ReactRelayQueryFetcher.js:193
    error RelayObservable.js:553
    error RelayObservable.js:553
    r RelayObservable.js:178
    error RelayObservable.js:553
    error RelayObservable.js:553
    error RelayReplaySubject.js:105
    error RelayReplaySubject.js:104
    error fetchQueryInternal.js:126
    error RelayObservable.js:553
    error RelayObservable.js:553
    _error RelayModernQueryExecutor.js:190
    error RelayModernQueryExecutor.js:85
    error RelayObservable.js:553
```

And the OpenCTI logfile is flooded with:
```
{"message":"Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","locations":[{"line":23,"column":7}],"path":["threatActors","pageInfo","globalCount"],"extensions":{"code":"INTERNAL_SERVER_ERR
OR","exception":{"stacktrace":["TypeError: Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","    at GraphQLScalarType.serializeInt [as serialize] (/var/www/opencti/node_modules/graphql/typ
e/scalars.js:43:11)","    at completeLeafValue (/var/www/opencti/node_modules/graphql/execution/execute.js:652:37)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:598:12)","
 at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField
 (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/openc
ti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)","    at completeValue (/var/www/opencti/node_modules/graphql
/execution/execute.js:609:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execu
te.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collect
AndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)"]}},"level":"error"}
{"message":"Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","locations":[{"line":23,"column":7}],"path":["threatActors","pageInfo","globalCount"],"extensions":{"code":"INTERNAL_SERVER_ERR
OR","exception":{"stacktrace":["TypeError: Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","    at GraphQLScalarType.serializeInt [as serialize] (/var/www/opencti/node_modules/graphql/typ
e/scalars.js:43:11)","    at completeLeafValue (/var/www/opencti/node_modules/graphql/execution/execute.js:652:37)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:598:12)","
 at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField
 (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/openc
ti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)","    at completeValue (/var/www/opencti/node_modules/graphql
/execution/execute.js:609:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execu
te.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collect
AndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)"]}},"level":"error"}
{"message":"Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","locations":[{"line":23,"column":7}],"path":["sectors","pageInfo","globalCount"],"extensions":{"code":"INTERNAL_SERVER_ERROR","
exception":{"stacktrace":["TypeError: Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","    at GraphQLScalarType.serializeInt [as serialize] (/var/www/opencti/node_modules/graphql/type/sca
lars.js:43:11)","    at completeLeafValue (/var/www/opencti/node_modules/graphql/execution/execute.js:652:37)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:598:12)","    at c
ompleteValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField (/va
r/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/opencti/no
de_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)","    at completeValue (/var/www/opencti/node_modules/graphql/exec
ution/execute.js:609:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js
:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndEx
ecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)"]}},"level":"error"}
```
 
## Additional information

/

**Comment by richard-julien** [comment]
Hi @fr33tux, i just try to redo it from scratch on my mac without any issue. 
Do you manage to install each dependency manually? (Grakn, etc)
Could you add the exact version of nodeJS you use?
Thanks.

**Comment by fr33tux** [comment]
Hello,

Thank you for looking into this!

>  Do you manage to install each dependency manually? (Grakn, etc)

Yes, ElasticSearch, Grakn, RabbitMQ, Redis were manually installed alongside.
In case it's related and if it helps to debug, the forcing the connectors to synchronize now doesn't seem to do anything so I don't have any data yet.

- NodeJS 10.16.0
- Grakn 1.5.6

**Comment by richard-julien** [comment]
Do you think its possible to have a quick skype and screen share session to dig into your problem? My skype: richard.julien

**Comment by fr33tux** [comment]
Sorry, I won't be able to Skype. Do you need anything specific?

I tried to upgrade to NodeJS 12.x, and same results:
```
{"message":"Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","locations":[{"line":23,"column":7}],"path":["threatActors","pageInfo","globalCount"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","    at GraphQLScalarType.serializeInt [as serialize] (/var/www/opencti/node_modules/graphql/type/scalars.js:43:11)","    at completeLeafValue (/var/www/opencti/node_modules/graphql/execution/execute.js:652:37)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:598:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:609:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)"]}},"level":"error"}
{"message":"Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","locations":[{"line":23,"column":7}],"path":["sectors","pageInfo","globalCount"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Int cannot represent non-integer value: { value: 0, relation: \"eq\" }","    at GraphQLScalarType.serializeInt [as serialize] (/var/www/opencti/node_modules/graphql/type/scalars.js:43:11)","    at completeLeafValue (/var/www/opencti/node_modules/graphql/execution/execute.js:652:37)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:598:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:609:12)","    at completeValue (/var/www/opencti/node_modules/graphql/execution/execute.js:576:21)","    at completeValueCatchingError (/var/www/opencti/node_modules/graphql/execution/execute.js:514:19)","    at resolveField (/var/www/opencti/node_modules/graphql/execution/execute.js:454:10)","    at executeFields (/var/www/opencti/node_modules/graphql/execution/execute.js:294:18)","    at collectAndExecuteSubfields (/var/www/opencti/node_modules/graphql/execution/execute.js:730:10)","    at completeObjectValue (/var/www/opencti/node_modules/graphql/execution/execute.js:720:10)"]}},"level":"error"}
```

It always happen on the `/dashboard/entities` page and `/dashboard/threats`.

**Comment by richard-julien** [comment]
Maybe it was a problem during the schema initialization.
Can you try to run again the schema and migration commands?
If its not working, try to erase the grakn database and run the commands again.

**Comment by fr33tux** [comment]
I tried after purging grakn, elasticsearch, redis and RabbitMQ but without more luck.
I then tried a fresh installation again, and same result.

**Comment by richard-julien** [comment]
I dont have any idea... Can you add copy/past (or screenshot) the graphQL network frame that fail (Headers/Response...) with your browser dev tools?

**Comment by richard-julien** [comment]
According to documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-track-total-hits.html and https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-body.html) it seems you use an elastic 7. Today we only support elastic 6. Can you confirm @fr33tux?

**Comment by richard-julien** [comment]
Dont hesitate to reopen the issue if its not link to the Elasticsearch version.

**Comment by fr33tux** [comment]
Sorry for the delay.

I confirm Elasticsearch 6.x fixes the issue, thanks!
