### ISSUE TITLE
baremetal install - workers will not start 

### ISSUE THREAD

**Issue by ehmueller** [OpenCTI-Platform/opencti#844]
## Description

I am trying to configure a bare metal install of opencti-release-3.3.2.tar.gz  using the install script. All services are starting except for the last two worker services.

## Environment

1. Ubuntu 18.04
2. OpenCTI version: 3.3.2
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

root@shdw018test:~# systemctl status opencti-server.service
â opencti-server.service - OpenCTI Server daemon
   Loaded: loaded (/etc/systemd/system/opencti-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-09-03 18:01:32 UTC; 56min ago
 Main PID: 2428 (node)
    Tasks: 24 (limit: 4915)
   CGroup: /system.slice/opencti-server.service
           ââ2428 node /usr/share/yarn/bin/yarn.js serv
           ââ2465 /bin/sh -c node --max_old_space_size=8192 build/index.js
           ââ2466 /usr/local/bin/node --max_old_space_size=8192 build/index.js

Sep 03 18:01:35 shdw018test yarn[2428]: {"level":"info","message":"[PRE-CHECK] > RabbitMQ is alive","timestamp":"2020-09-03T18:01:35.0
Sep 03 18:01:35 shdw018test yarn[2428]: {"level":"info","message":"[PRE-CHECK] > Redis is alive","timestamp":"2020-09-03T18:01:35.032Z
Sep 03 18:01:35 shdw018test yarn[2428]: {"level":"info","message":"[PRE-CHECK] > Python3 is available","timestamp":"2020-09-03T18:01:3
Sep 03 18:01:35 shdw018test yarn[2428]: {"level":"info","message":"[INIT] > New platform detected, initialization...","timestamp":"202
Sep 03 18:01:40 shdw018test yarn[2428]: {"level":"info","message":"[INIT] > Grakn schema loaded","timestamp":"2020-09-03T18:01:40.626Z
Sep 03 18:01:41 shdw018test yarn[2428]: {"level":"info","message":"[INIT] > Elasticsearch indexes loaded","timestamp":"2020-09-03T18:0
Sep 03 18:01:41 shdw018test yarn[2428]: {"level":"info","message":"[INIT] > Initialization of settings and basic elements","timestamp"
Sep 03 18:01:57 shdw018test yarn[2428]: {"level":"info","message":"[INIT] > Platform default initialized","timestamp":"2020-09-03T18:0
Sep 03 18:01:59 shdw018test yarn[2428]: {"level":"info","message":"[ADMIN_SETUP] admin user initialized","timestamp":"2020-09-03T18:01
Sep 03 18:02:00 shdw018test yarn[2428]: {"level":"info","message":"OPENCTI Ready on port 4000","timestamp":"2020-09-03T18:02:00.031Z"}

root@shdw018test:~# systemctl status opencti-worker@1
â opencti-worker@1.service - OpenCTI Worker daemon 1
   Loaded: loaded (/etc/systemd/system/opencti-worker@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-09-03 18:43:11 UTC; 16min ago
  Process: 6525 ExecStart=/usr/bin/python3.7 /opt/opencti/worker/worker.py (code=exited, status=1/FAILURE)
 Main PID: 6525 (code=exited, status=1/FAILURE)

Sep 03 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Service hold-off time over, scheduling restart.
Sep 03 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Scheduled restart job, restart counter is at 5.
Sep 03 18:43:11 shdw018test systemd[1]: Stopped OpenCTI Worker daemon 1.
Sep 03 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Start request repeated too quickly.
Sep 03 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Failed with result 'exit-code'.
Sep 03 18:43:11 shdw018test systemd[1]: Failed to start OpenCTI Worker daemon 1.

Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Main process exited, code=exited, status=1/FAILURE
Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Failed with result 'exit-code'.
Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Service hold-off time over, scheduling restart.
Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Scheduled restart job, restart counter is at 4.
Sep  3 18:43:10 shdw018test systemd[1]: Stopped OpenCTI Worker daemon 1.
Sep  3 18:43:10 shdw018test systemd[1]: Started OpenCTI Worker daemon 1.
Sep  3 18:43:10 shdw018test python3.7[6525]: INFO:root:Listing Threat-Actors with filters null.
Sep  3 18:43:10 shdw018test python3.7[6525]: Traceback (most recent call last):
Sep  3 18:43:10 shdw018test python3.7[6525]:   File "/opt/opencti/worker/worker.py", line 300, in <module>
Sep  3 18:43:10 shdw018test python3.7[6525]:     worker = Worker()
Sep  3 18:43:10 shdw018test python3.7[6525]:   File "/opt/opencti/worker/worker.py", line 212, in __init__
Sep  3 18:43:10 shdw018test python3.7[6525]:     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token)
Sep  3 18:43:10 shdw018test python3.7[6525]:   File "/usr/local/lib/python3.7/dist-packages/pycti/api/opencti_api_client.py", line 125, in __init__
Sep  3 18:43:10 shdw018test python3.7[6525]:     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
Sep  3 18:43:10 shdw018test python3.7[6525]: ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Main process exited, code=exited, status=1/FAILURE
Sep  3 18:43:10 shdw018test systemd[1]: opencti-worker@1.service: Failed with result 'exit-code'.
Sep  3 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Service hold-off time over, scheduling restart.
Sep  3 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Scheduled restart job, restart counter is at 5.
Sep  3 18:43:11 shdw018test systemd[1]: Stopped OpenCTI Worker daemon 1.
Sep  3 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Start request repeated too quickly.
Sep  3 18:43:11 shdw018test systemd[1]: opencti-worker@1.service: Failed with result 'exit-code'.
Sep  3 18:43:11 shdw018test systemd[1]: Failed to start OpenCTI Worker daemon 1.

**Comment by ehmueller** [comment]
I figured it out....the worker is trying to connect to opencti on port 8080 while opencti is configured to run on port 4000. I updated the production.json configuration by changing port from 4000 to 8080 and now workers will start.
