### ISSUE TITLE
[Graphql] {'errors': [{'message': 'The "string" argument must be one of type string'}]}

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/opencti#888]
## Description

Error message return from Graphql with python request
```
{'errors': [{'message': 'The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]}
```
Here is the piece of the python code
```python
query = """
                query{
                    indicators(first: 10000){
                        edges{
                            node{
                                indicator_pattern
                                name
                                pattern_type
                                description
                            }
                        }
                        pageInfo{
                            endCursor
                        }
                    }
                }   
            """
        a = requests.post(
            self.url,
            headers=self.headers,
            data=json.dumps({"query": query}),
            verify=False,
        )
```

I've been using this code properly in version 3.2.2, but seems like the problem happened after Opencti had been updated to version 3.3.0

If I use the query only with the "Playground" it's running, but I can get the script works. 

Please advice. 
## Environment

1. OS (where OpenCTI server runs): Docker 19
2. OpenCTI version: 3.3.0
4. Other environment details:

**Comment by phucsnguyenv** [comment]
@richard-julien I am sorry for tagging your name. But could you please help on this issue?

**Comment by richard-julien** [comment]
Hi @phucsnguyenv,

In the python lib we personally use 

```
            r = requests.post(
                self.api_url,
                json={"query": query, "variables": variables},
                headers=self.request_headers,
                verify=self.ssl_verify,
                proxies=self.proxies,
            )
```

Take a look to the source code of opencti python client project.
I also recommend to simply use the OpenCTIApiClient if you want to query OpenCTI with python code.

**Comment by phucsnguyenv** [comment]
Thanks for your reply @richard-julien 
I will try this

**Comment by phucsnguyenv** [comment]
hi @richard-julien 

I try use that 
```python
a = requests.post(
            self.url, headers=self.headers, json={"query": query}, verify=False,
        )
x = json.loads(a.text)
print(a.status_code)
print(a.json())
``` 
and here is the output
```
500
{'errors': [{'message': 'The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type undefined', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]}
```

Is there any update with the GraphQL backend from version 3.3.0? Could you please try to run the a script like that with the OpenCTI demo site which got the same problem I believe.

**Comment by phucsnguyenv** [comment]
I tried to use OpenCTIApiClient as well and here is the output

```python
client_api = OpenCTIApiClient.query(self.url, self.token)
a = client_api.query(query)
```
output
```
Traceback (most recent call last):
  File "endpoint.py", line 156, in <module>
    instance.start()
  File "endpoint.py", line 150, in start
    self.requestData()
  File "endpoint.py", line 135, in requestData
    client_api = OpenCTIApiClient.query(self.url, self.token)
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 255, in query
    self.api_url,
AttributeError: 'str' object has no attribute 'api_url'
```

Please help!

**Comment by phucsnguyenv** [comment]
Here is the output when using ApiClient
```python
client_api = OpenCTIApiClient.query(self.url, self.token)
a = client_api.query(query)
print(a.status_code)
print(a.text)
```

output
```
INFO:root:Listing Threat-Actors with filters null.
INFO:root:{"errors":[{"message":"Cannot query field \"standard_id\" on type \"ThreatActor\".","locations":[{"line":8,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"spec_version\" on type \"ThreatActor\".","locations":[{"line":11,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"createdBy\" on type \"ThreatActor\". Did you mean \"created\", \"createdByRef\", \"created_at\", or \"creator\"?","locations":[{"line":14,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"standard_id\" on type \"Identity\".","locations":[{"line":17,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"spec_version\" on type \"Identity\".","locations":[{"line":20,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"roles\" on type \"Identity\". Did you mean to use an inline fragment on \"User\"?","locations":[{"line":23,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_aliases\" on type \"Identity\".","locations":[{"line":25,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectLabel\" on type \"Identity\".","locations":[{"line":28,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_organization_type\" on type \"Organization\".","locations":[{"line":39,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"x_opencti_reliability\" on type \"Organization\". Did you mean \"reliability\"?","locations":[{"line":40,"column":21}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Unknown type \"Individual\".","locations":[{"line":42,"column":24}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectMarking\" on type \"ThreatActor\".","locations":[{"line":47,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"objectLabel\" on type \"ThreatActor\".","locations":[{"line":62,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"standard_id\" on type \"ExternalReference\".","locations":[{"line":75,"column":25}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"aliases\" on type \"ThreatActor\". Did you mean \"alias\"?","locations":[{"line":93,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"threat_actor_types\" on type \"ThreatActor\". Did you mean \"parent_types\"?","locations":[{"line":94,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"roles\" on type \"ThreatActor\". Did you mean \"notes\"?","locations":[{"line":97,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"goals\" on type \"ThreatActor\". Did you mean \"goal\"?","locations":[{"line":98,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"secondary_motivations\" on type \"ThreatActor\". Did you mean \"secondary_motivation\", \"primary_motivation\", or \"personal_motivation\"?","locations":[{"line":102,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Cannot query field \"personal_motivations\" on type \"ThreatActor\". Did you mean \"personal_motivation\", \"primary_motivation\", or \"secondary_motivation\"?","locations":[{"line":103,"column":13}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
```
I don't know how to send the query that I mentioned above with the OpenCTIApiClient

**Comment by richard-julien** [comment]
With your code I dont know exactly what missing to make the query a valid one. I dont remember we change anything in version 3.3.0 on this part. Please dig into our code to identify what is different.

When using our api client its seems the graphql query you try to execute is invalid. You ask for fields that doesn't exists.
Please take a look in https://github.com/OpenCTI-Platform/client-python/blob/master/pycti/entities/opencti_threat_actor.py to understand what kind of query you can do on threat actor for example.

**Comment by phucsnguyenv** [comment]
@richard-julien thanks for your response. 
Currently I am stuck with exporting all indicators in OpenCTI. Could you please suggest the query can do that?

Thank you!

**Comment by richard-julien** [comment]
Hi @phucsnguyenv , you have to use the indicators query with pagination to prevent fetching too much data in one query.

```
query {
  indicators(first: 10, after: "YXJyYXljb25uZWN0aW9uOjE=") {
    edges {
      cursor
      node {
        standard_id
      }
    }
  }
}
```

The after param take the result of the cursor variable you get with the data

**Comment by SamuelHassine** [comment]
Closing due to inactivity and V4 last release, please feel free to re-open if necessary.
