### ISSUE TITLE
OpenCTI is ready but login page goes blank after loading a bit

### ISSUE THREAD

**Issue by ahmadmkhan1** [OpenCTI-Platform/opencti#917]
## Description

Manually installed OpenCTI on an EC2 instance and Elasticsearch & Grakn on a separate EC2 instance. OpenCTI is ready on port 8080 after `yarn serv` but whenever I visit the login page through web browser, it loads the colored screen for a second and then results in a blank white window. Checked on Chrome, Edge and Opera.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI: 3.3.2
3. Python: 3.8.5
4. Yarn 1.22.5
5. Node: 12.20.0
6. Elasticsearch: 7.10.0
7. Grakn: 1.7.2

## Expected Output

Working login page

## Actual Output

Blank white window
 
## Additional information

Gives the following debug level error when I try to visit the login page

```
{"level":"info","message":"OPENCTI Ready on port 8080","timestamp":"2020-11-27T07:57:41.074Z"}
{"query":"match $settings isa Settings; get;","level":"debug","message":"[GRAKN - infer: false] Find","timestamp":"2020-11-27T07:58:42.887Z"}
{"level":"debug","message":"[GRAKN - infer: false] getAttributes Settings V393352","timestamp":"2020-11-27T07:58:42.909Z"}
{"type":"READ_ERROR","operation_query":"query RootQuery{me{id name lastname language user_email capabilities{name id}}settings{...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}","inner_relation_creation":0,"operation":"RootQuery","time":299,"variables":{},"size":2,"error":{"data":{"category":"technical"},"stacktrace":["AuthRequired: You must be logged in to do this.","at error (webpack-internal:///./src/config/errors.js:21:10)","at AuthRequired (webpack-internal:///./src/config/errors.js:29:40)","at AuthDirective.authenticationControl (webpack-internal:///./src/graphql/authDirective.js:44:89)","at field.resolve (webpack-internal:///./src/graphql/authDirective.js:83:131)","at field.resolve (/home/ubuntu/opencti/node_modules/graphql-extensions/dist/index.js:134:26)","at field.resolve (/home/ubuntu/opencti/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)","at resolveFieldValueOrError (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:467:18)","at resolveField (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:434:16)","at executeFields (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:275:18)","at executeOperation (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:219:122)","at executeImpl (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:104:14)","at Object.execute (/home/ubuntu/opencti/node_modules/graphql/execution/execute.js:64:35)","at /home/ubuntu/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","at Generator.next (<anonymous>)"]},"level":"warn","message":"API Call","timestamp":"2020-11-27T07:58:43.169Z"}
{"query":"match $settings isa Settings; get;","level":"debug","message":"[GRAKN - infer: false] Find","timestamp":"2020-11-27T07:58:43.681Z"}
{"level":"debug","message":"[GRAKN - infer: false] getAttributes Settings V393352","timestamp":"2020-11-27T07:58:43.696Z"}
{"type":"READ_ERROR","operation_query":"query LoginQuery{settings{platform_demo platform_providers{name type provider}...AppIntlProvider_settings id}}fragment AppIntlProvider_settings on Settings{platform_language}","inner_relation_creation":0,"operation":"LoginQuery","time":213,"variables":{},"size":2,"error":{"stacktrace":["TypeError: attributeType.dataType is not a function","at eval (webpack-internal:///./src/database/grakn.js:469:37)","at processTicksAndRejections (internal/process/task_queues.js:97:5)","at async Promise.all (index 0)","at async Promise.all (index 0)","at async getConcepts (webpack-internal:///./src/database/grakn.js:640:28)","at async executeRead (webpack-internal:///./src/database/grakn.js:156:20)","at async load (webpack-internal:///./src/database/grakn.js:1076:16)","at async getSettings (webpack-internal:///./src/domain/settings.js:48:16)"]},"level":"error","message":"API Call","timestamp":"2020-11-27T07:58:43.890Z"}
{"query":"match $settings isa Settings; get;","level":"debug","message":"[GRAKN - infer: false] Find","timestamp":"2020-11-27T07:59:12.565Z"}
```

**Comment by ahmadmkhan1** [comment]
This is due to a buggy handling of RFC 3986 characters in OpenCTI config file also mentioned by [@zweger](https://github.com/OpenCTI-Platform/opencti/issues/913#issuecomment-732233562). Using email/pass without such characters will resolve this issue.

**Comment by djds** [comment]
This is still an issue in 5.2.1. We should revisit fixing this as we really shouldn't be limiting valid password characters in a security-focused product.
