### ISSUE TITLE
Build Environment setup issue

### ISSUE THREAD

**Issue by haxpak** [OpenCTI-Platform/opencti#970]
# Trying to setup OpenCTI in build environment

- Setup a new machine
- Setup node 12.20
- Setup elasticsearch
- Setup rabbitMQ
- Setup redis

Changed `opencti-graphql/default.json` to this
```
{
  "app": {
    "port": 4000,
    "logs": "./logs",
    "logs_level": "debug",
    "rate_protection": {
      "time_window": 1,
      "max_requests": 10000
    },
    "cookie_secure": false,
    "base_path": "",
    "platform_demo": false,
    "performance_logger": false,
    "map_tile_server": "https://map.opencti.io/styles/1fdd936a-084b-46ac-a948-22ce1686aadf/{z}/{x}/{y}.png",
    "admin": {
      "email": "admin@opencti.io",
      "password": "Admin@opencti.io",
      "token": "fd300ba1-7e14-494f-9dfe-73ba55c43938"
    }
  },
  "redis": {
    "hostname": "localhost",
    "port": 6379
  },
  "elasticsearch": {
    "url": "http://localhost:9200",
    "noQueryCache": false
  },
  "minio": {
    "endpoint": "localhost",
    "port": 9000,
    "use_ssl": false,
    "access_key": "minioeyt",
    "secret_key": "my_secret_key"
  },
  "rabbitmq": {
    "hostname": "localhost",
    "port": 5672,
    "port_management": 15672,
    "management_ssl": false,
    "username": "guest",
    "password": "guest"
  },
  "providers": {
    "local": {
      "strategy": "LocalStrategy"
    }
  }
}

```

Added the following to `.env` file in folder `opencti-front`
```
SKIP_PREFLIGHT_CHECK=true
REACT_EDITOR=atom
```

- In `opencti-graphql` folder 
```
yarn install 
yarn start --unhandled-rejections=strict
```
The output is like
```
{"level":"info","message":"[MIGRATION] Read 0 migrations from the database","timestamp":"2020-12-26T07:32:02.977Z"}
{"level":"info","message":"[MIGRATION] Platform already up to date, nothing to migrate","timestamp":"2020-12-26T07:32:02.978Z"}
{"level":"info","message":"[MIGRATION] Migration process completed","timestamp":"2020-12-26T07:32:02.978Z"}
{"level":"info","message":"[STREAM] Starting streaming processor","timestamp":"2020-12-26T07:32:03.531Z"}
(node:38745) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'XINFO'
    at parseError (/home/user/ctis/opencti-platform/opencti-graphql/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/user/ctis/opencti-platform/opencti-graphql/node_modules/redis-parser/lib/parser.js:302:14)
(node:38745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

{"level":"info","message":"[OPENCTI] Servers ready on port 4000","timestamp":"2020-12-26T07:32:03.534Z"}
```

- The graphql is serving on port 4000, but this error keeps popping up

**Then in opencti-front folder**
```
yarn install
yarn start
```
the output is like
```
Compiled successfully!

You can now view opencti-front in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.190.142:3000

Note that the development build is not optimized.
To create a production build, use yarn build.

[HPM] Upgrading to WebSocket
```

However when i navigate to the website on `http://192.168.190.142:3000` :
This is what I get

```
Error: 
render
src/relay/environment.js:101
   98 |     const { error } = data;
   99 |     const types = error ? map((e) => e.name, error) : [];
  100 |     const unmanagedErrors = difference(types, managedErrorTypes || []);
> 101 |     if (!isEmpty(unmanagedErrors)) throw new ApplicationError(error);
      | ^  102 |     return render(data);
  103 |   }}
  104 | />
View compiled
```
I have also changed the filesystem watch value, without which it won't work
```
# insert the new value into the system config
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

# check that the new value was applied
cat /proc/sys/fs/inotify/max_user_watches
```

* Am i missing something?

**Comment by richard-julien** [comment]
Hi. 

(node:38745) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'XINFO'

Looks like your redis is too old. You need redis 6+
See https://www.notion.so/luatix/Manual-deployment-b911beba44234f179841582ab3894bb1

**Comment by richard-julien** [comment]
Closed due to inactivity. Feel free to reopen if needed.
