### ISSUE TITLE
yarn serv exits after Elasticsearch is started

### ISSUE THREAD

**Issue by smclinden** [OpenCTI-Platform/opencti#980]
## Description

yarn serv appears to fail on the creation of the MinIO OpenCTI bucket.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 4.0.4
3. OpenCTI client: none
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Installed all the dependencies (ES, MinIO, RabbitMQ, Redis, NodeJS ...)
2. Installed MinIO by downloading the binary for x86_64 Linux
3. Run "yarn install" and "yarn build"
4. Run "yarn serv"

## Expected Output

Dependencies are started then the front-end

## Actual Output

```
yarn run v1.22.10
$ node --max_old_space_size=8192 build/index.js
{"level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-01-05T16:52:03.640Z"}
{"level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-01-05T16:52:03.658Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
 
## Additional information

I checked the MiniIO install and the bucket local/opencti-bucket is not created. I created it, manually but it appears to fail in the same place.

**Comment by smclinden** [comment]
It appears that the Elasticsearch database is not initialized, either. Here is the log:

```
"type": "server", "timestamp": "2021-01-05T00:48:00,001-05:00", "level": "INFO", "component": "o.e.x.m.MlDailyMaintenanceService", "cluster.name": "opencti", "node.name": "host.tld", "message": "triggering scheduled
 [ML] maintenance tasks", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T00:48:00,034-05:00", "level": "INFO", "component": "o.e.x.m.a.TransportDeleteExpiredDataAction", "cluster.name": "opencti", "node.name": "host.tld", "message": "Deleting ex
pired data", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T00:48:00,078-05:00", "level": "INFO", "component": "o.e.x.m.j.r.UnusedStatsRemover", "cluster.name": "opencti", "node.name": "host.tld", "message": "Successfully deleted [0
] unused stats documents", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T00:48:00,079-05:00", "level": "INFO", "component": "o.e.x.m.a.TransportDeleteExpiredDataAction", "cluster.name": "opencti", "node.name": "host.tld", "message": "Completed d
eletion of expired ML data", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T00:48:00,079-05:00", "level": "INFO", "component": "o.e.x.m.MlDailyMaintenanceService", "cluster.name": "opencti", "node.name": "host.tld", "message": "Successfully complet
ed [ML] maintenance task: triggerDeleteExpiredDataTask", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,762-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "stopping ...", "cluster.uuid": "VAROxpVDR-C
3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,766-05:00", "level": "INFO", "component": "o.e.x.w.WatcherService", "cluster.name": "opencti", "node.name": "host.tld", "message": "stopping watch service, reason 
[shutdown initiated]", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,767-05:00", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "opencti", "node.name": "host.tld", "message": "[controller/9173] [Ma
in.cc@154] ML controller exiting", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,768-05:00", "level": "INFO", "component": "o.e.x.w.WatcherLifeCycleService", "cluster.name": "opencti", "node.name": "host.tld", "message": "watcher has stopped an
d shutdown", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,773-05:00", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "opencti", "node.name": "host.tld", "message": "Native controller process h
as stopped - no new native processes can be started", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,921-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "stopped", "cluster.uuid": "VAROxpVDR-C3glAI
05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,921-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "closing ...", "cluster.uuid": "VAROxpVDR-C3
glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:10:05,937-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "closed", "cluster.uuid": "VAROxpVDR-C3glAI0
5IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:15:08,338-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "version[7.10.1], pid[9680], build[default/d
eb/1c34507e66d7db1211f66f3513706fdf548736aa/2020-12-05T01:00:33.671820Z], OS[Linux/4.15.0-126-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]" }
{"type": "server", "timestamp": "2021-01-05T10:15:08,343-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "JVM home [/usr/share/elasticsearch/jdk], us
ing bundled JDK [true]" }
{"type": "server", "timestamp": "2021-01-05T10:15:08,344-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "JVM arguments [-Xshare:auto, -Des.networkad
dress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages,
 -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.provid
ers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-13115180712049012633, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elas
ticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/us
r/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,093-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [aggs-matrix-stats]
" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,093-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [analysis-common]" 
}
{"type": "server", "timestamp": "2021-01-05T10:15:15,093-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [constant-keyword]"
 }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [flattened]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [frozen-indices]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [ingest-common]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [ingest-geoip]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [ingest-user-agent]
" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,094-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [kibana]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,095-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [lang-expression]" 
}
{"type": "server", "timestamp": "2021-01-05T10:15:15,095-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [lang-mustache]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,095-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [lang-painless]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,095-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [mapper-extras]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,095-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [mapper-version]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,096-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [parent-join]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,096-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [percolator]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,096-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [rank-eval]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,096-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [reindex]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [repositories-meter
ing-api]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [repository-url]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [search-business-ru
les]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [searchable-snapsho
ts]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [spatial]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,097-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [systemd]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,098-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [transform]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,098-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [transport-netty4]"
 }
{"type": "server", "timestamp": "2021-01-05T10:15:15,098-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [unsigned-long]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,098-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [vectors]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,098-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [wildcard]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-analytics]"
 }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-async]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-async-searc
h]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-autoscaling
]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-ccr]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-core]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,099-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-data-stream
s]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-deprecation
]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-enrich]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-eql]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-graph]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-identity-pr
ovider]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-ilm]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,100-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-logstash]" 
}
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-ml]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-monitoring]
" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-ql]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-rollup]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-security]" 
}
{"type": "server", "timestamp": "2021-01-05T10:15:15,101-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-sql]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,102-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-stack]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,102-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-voting-only
-node]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,102-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "loaded module [x-pack-watcher]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,103-05:00", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "opencti", "node.name": "host.tld", "message": "no plugins loaded" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,297-05:00", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "opencti", "node.name": "host.tld", "message": "using [1] data paths, mounts [[/
apps (/dev/mapper/vg_apps-lv_apps)]], net usable_space [369.7gb], net total_space [392.7gb], types [ext4]" }
{"type": "server", "timestamp": "2021-01-05T10:15:15,297-05:00", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "opencti", "node.name": "host.tld", "message": "heap size [1gb], compressed ordi
nary object pointers [true]" }
{"type": "server", "timestamp": "2021-01-05T10:15:16,012-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "node name [host.tld], node I
D [dwBDP7mmTHmBjWJZKmr7MA], cluster name [opencti], roles [transform, master, remote_cluster_client, data, ml, data_content, data_hot, data_warm, data_cold, ingest]" }
{"type": "server", "timestamp": "2021-01-05T10:15:23,543-05:00", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "opencti", "node.name": "host.tld", "message": "[controller/9905] [Ma
in.cc@114] controller (64 bit): Version 7.10.1 (Build 11e1ac84105757) Copyright (c) 2020 Elasticsearch BV" }
{"type": "server", "timestamp": "2021-01-05T10:15:24,510-05:00", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "opencti", "node.name": "host.tld", "message": "parsed [0] roles from file 
[/etc/elasticsearch/roles.yml]" }
{"type": "server", "timestamp": "2021-01-05T10:15:26,625-05:00", "level": "INFO", "component": "o.e.t.NettyAllocator", "cluster.name": "opencti", "node.name": "host.tld", "message": "creating NettyAllocator with the 
following configs: [name=unpooled, suggested_max_allocation_size=256kb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=1mb, heap_size=1gb}]" }
{"type": "server", "timestamp": "2021-01-05T10:15:26,703-05:00", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "opencti", "node.name": "host.tld", "message": "using discovery type [single-nod
e] and seed hosts providers [settings]" }
{"type": "server", "timestamp": "2021-01-05T10:15:27,218-05:00", "level": "WARN", "component": "o.e.g.DanglingIndicesState", "cluster.name": "opencti", "node.name": "host.tld", "message": "gateway.auto_import_danglin
g_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
{"type": "server", "timestamp": "2021-01-05T10:15:27,790-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "initialized" }
{"type": "server", "timestamp": "2021-01-05T10:15:27,792-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "starting ..." }
{"type": "server", "timestamp": "2021-01-05T10:15:28,138-05:00", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "opencti", "node.name": "host.tld", "message": "publish_address {10.223.130.132
:9300}, bound_addresses {0.0.0.0:9300}" }
{"type": "server", "timestamp": "2021-01-05T10:15:28,622-05:00", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "opencti", "node.name": "host.tld", "message": "cluster UUID [VAROxpVDR-C3glAI05IT
-w]" }
{"type": "server", "timestamp": "2021-01-05T10:15:28,692-05:00", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "opencti", "node.name": "host.tld", "message": "elected-as-master ([1] nodes joi
ned)[{host.tld}{dwBDP7mmTHmBjWJZKmr7MA}{J7a4_tMuTX2YIAyDBmw7dQ}{10.223.130.132}{10.223.130.132:9300}{cdhilmrstw}{ml.machine_memory=55926771712, xpack.installed=true, transform.node=true, ml.max_open_jobs=20} elect le
ader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 40, delta: master node changed {previous [], current [{host.tld}{dwBDP7mmTHmBjWJZKmr7MA}{J7a4_tMuTX2YIAyDBmw7dQ}{10.223.130.132}{10.223.130.132:9300}{
cdhilmrstw}{ml.machine_memory=55926771712, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]}" }
{"type": "server", "timestamp": "2021-01-05T10:15:28,790-05:00", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "opencti", "node.name": "host.tld", "message": "master node changed {pre
vious [], current [{host.tld}{dwBDP7mmTHmBjWJZKmr7MA}{J7a4_tMuTX2YIAyDBmw7dQ}{10.223.130.132}{10.223.130.132:9300}{cdhilmrstw}{ml.machine_memory=55926771712, xpack.installed=true, transform.node=true, ml.max_open_job
s=20}]}, term: 2, version: 40, reason: Publication{term=2, version=40}" }
{"type": "server", "timestamp": "2021-01-05T10:15:28,838-05:00", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "opencti", "node.name": "host.tld", "message": "publish_address {10.
223.130.132:9200}, bound_addresses {0.0.0.0:9200}", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:15:28,839-05:00", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "opencti", "node.name": "host.tld", "message": "started", "cluster.uuid": "VAROxpVDR-C3glAI
05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:15:29,114-05:00", "level": "INFO", "component": "o.e.l.LicenseService", "cluster.name": "opencti", "node.name": "host.tld", "message": "license [65862606-188c-4ab9-b05a-
5bb0d8c9822f] mode [basic] - valid", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:15:29,116-05:00", "level": "INFO", "component": "o.e.x.s.s.SecurityStatusChangeListener", "cluster.name": "opencti", "node.name": "host.tld", "message": "Active license 
is now [BASIC]; Security is disabled", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }
{"type": "server", "timestamp": "2021-01-05T10:15:29,120-05:00", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "opencti", "node.name": "host.tld", "message": "recovered [0] indices into cluste
r_state", "cluster.uuid": "VAROxpVDR-C3glAI05IT-w", "node.id": "dwBDP7mmTHmBjWJZKmr7MA"  }

**Comment by richard-julien** [comment]
Hi @smclinden,
For now when opencti fail to connect to a dependency it fail to start without warning. Will be fixed in next release. See https://github.com/OpenCTI-Platform/opencti/commit/adb9abe14d0db98642c6ea22cfad8e86dac64797. 
After Elastic, the next check is MINIO (then rabbit, redis). 
So its look like your opencti cant access to your minio. Double check your opencti configuration for minio to provide correct uri, user, password. Please also check your network configuration

**Comment by smclinden** [comment]
Here is what I see when I open the browser to MinIO on my OpenCTI 3 installation:

![image](https://user-images.githubusercontent.com/8810661/103776633-b7913880-4ffd-11eb-8ab9-84d09529d0fa.png)

On 4.0.4 I had to MANUALLY create the local configuration for MinIO and manually create the opencti-bucket (the manual process does not result in the creation of "input" or "output"). After that

```
mc config host ls
```

returns:

```
local
  URL       : http://0.0.0.0:9000
  AccessKey : minio
  SecretKey : miniostorage
  API       : s3v4
  Path      : auto
```

My production.conf file has the following:

```
  "minio": {
    "endpoint": "localhost",
    "port": 9000,
    "use_ssl": false,
    "access_key": "minio",
    "secret_key": "miniostorage"
  },
```

Yet it appears that it isn't connecting to MinIO. I disabled IPv6 in the kernel, since some services were only listening on ::1 and ran "netstat -apn | grep 9000" and got this:

```
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      18376/minio  
```

It has to be something silly but I don't know what.

**Comment by smclinden** [comment]
Additional info:

```
yarn --verbose serv
```

returns:

```
{"level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-01-06T14:25:44.887Z"}
verbose 1.618756215 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/apps/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/apps/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/apps/usr/local/lib/node_modules/yarn/lib/cli.js:790:113)
    at /apps/usr/local/lib/node_modules/yarn/lib/cli.js:34550:30
    at Generator.throw (<anonymous>)
    at step (/apps/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /apps/usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

**Comment by smclinden** [comment]
I'm not using Docker. I am running everything as a service on the local system.

```
yarn check

```

returns

```
error "graphql-iso-date#graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" doesn't satisfy found match of "graphql@15.4.0"
error "graphql-relay#graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" doesn't satisfy found match of "graphql@15.4.0"
error "graphql-subscriptions#graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0" doesn't satisfy found match of "graphql@15.4.0"
error "graphql-tools#@graphql-tools/links#@apollo/client@~3.2.5" doesn't satisfy found match of "@apollo/client@3.3.6"
error "apollo-server-core#graphql-upload#graphql@0.13.1 - 14" doesn't satisfy found match of "graphql@15.4.0"
error Found 5 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command
```

**Comment by richard-julien** [comment]
Thats really strange. OpenCTI fail to connect to your minio but its really difficult to understand why ...

**Comment by smclinden** [comment]
Agreed. I can attach to MinIO with a browser using the credentials in the config file, above. But OpenCTI doesn't connect and there is no logging to determine why?

**Comment by richard-julien** [comment]
Ticket closed. Wrong config of minio in openCTI.
+ Improvement of error log in 4.0.6
